### ISSUE TITLE
Dynamic Default Values

### ISSUE THREAD

**Issue by benwilson512** [absinthe-graphql/absinthe#100]
Today I ran into a scenario where I wanted the default value for a field named `before` to be the current time, but any value we give to `default_value` is gonna be hard coded as it's evaluated at compile time.

Since we already go through the effort of handling anonymous functions, I think we ought to allow a default value to also be a zero arity function that would get called at runtime.

Thoughts? @bruce

**Comment by bruce** [comment]
Seems reasonable -- and that this would be both on fields (for input objects) and args.

I'm not sure on 0 arity, however. I think it's possible a default value might be dependent on some portion of the execution environment (eg, the current user, the root value, etc).

**Comment by bruce** [comment]
Simple example: a default time value could depend on the current user's location.

**Comment by benwilson512** [comment]
So I may have spoken too soon.

Because we are just grabbing AST and then putting that AST in an actual function, `default_value: :os.timestamp` actually does produce a new value on every request. This doesn't give us any ability to context based changes but I'm honestly not sure that's a good idea.
