### ISSUE TITLE
Add middleware capability

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe#106]
Copy pasting description from Sangria ( http://sangria-graphql.org/learn/#middleware )

>Support generic middleware that can be used for different purposes, like performance measurement, metrics collection, security enforcement, etc. on a field and query level. Moreover it makes it much easier for people to share standard middleware in a libraries. Middleware allows you to define callbacks before/after query and field.

It would be a great addition to Absinthe.

As in Sangria, Middleware are especially useful when you can attach arbitrary meta to your fields:

>In order to ensure generic classification of fields, every field contains a generic list or FieldTags which provides a user-defined meta-information about this field (just to highlight a few examples: Permission("ViewOrders"), Authorized, Measured, Cached, etc.)

**Comment by tlvenn** [comment]
GraphQL decorators should provide middleware features in a language agnostic way:
https://github.com/apollostack/graphql-decorators

**Comment by benwilson512** [comment]
Can you elaborate on what you mean? Absinthe is not language agnostic.

**Comment by tlvenn** [comment]
Sorry I should had been more explicit... Right now, middleware / metadata as defined in Sangria for example, is totally tied with Sangria and not really leveraging the GraphQL schema to declare them.

So each GraphQL implementations are coming up with their own way of solving this.

The GraphQL Decorators spec is aiming to integrate this concern directly in the schema in a declarative way (similarly to how you use directive).

Interesting discussion to have more background on this topic: https://github.com/graphql/graphql-js/pull/334

**Comment by tlvenn** [comment]
So the GraphQL Decorators would let us declare metadata directly in GraphQL. The middleware part which could process those decorators would of course be implementation specific.

**Comment by tlvenn** [comment]
The cool part is you can have decorators that are only processed on the server or only processed in the client or both.

**Comment by tlvenn** [comment]
I should add that decorators are more than just metadata:

>Schema decorators are similar to function decorators in Python or ES2016 — they alter the behavior of the thing they decorate. While Python decorators only apply to functions, our proposal for schema decorators can be selectively applied to arguments, fields, types or the schema.

**Comment by tlvenn** [comment]
In case you have missed it, there is an interesting ongoing discussion there https://github.com/apollostack/graphql-decorators/issues/1

**Comment by tlvenn** [comment]
Also worth noting, the latest graphql-js release (0.6.0) features RFC: Schema Language Directives
| https://github.com/graphql/graphql-js/pull/376

So metadata can now properly be implemented as directive directly in GraphQL.

We now 'just' need the middleware / plugin part that can consume them and do something :). The conversation above has some great feedback from the creator of Sangria and I find his definition of decorator runtime (the middleware) phases pretty interesting:

- __query analysis phase__ - at this phase decorator runtime may analyze the query with the help of decorator annotations and do some interesting stuff with this analyzed data (validate arguments, analyze complexity, go to database to fetch additional information, etc.). At this point query execution is not started yet, which means that decorator runtime is able stop the execution if necessary.

- __query execution phase__ - that this phase decorator is able to participate in query execution and modify the runtime behavior of fields and types is some ways (metrics, authorization, caching, etc.)

- __query validation phase__ - at this phase decorator runtime participates in query validation provided by current implementation of graphql-js. It can be done in form of a validation rule, for instance. This will make it easier for a decorator to produce validation errors in a standard format.

**Comment by bruce** [comment]
@tlvenn Support for schema definition in IDL (and materialization) is currently ongoing in a branch -- built on top of the April spec work. Thanks for the tip; I'd recommend we also chat about this in our Slack channel vs expand issues based on bleeding edge graphql-js changes.

**Comment by bruce** [comment]
Closing, as it's tagged roadmap and we use that for archiving good "big" ideas that we want to do -- but keeping our issues list focused on actionable, smaller steps/bugs. Foundational pieces of this are already being worked on.
