### ISSUE TITLE
returning {:error, nil} in resolve/3

### ISSUE THREAD

**Issue by chungwong** [absinthe-graphql/absinthe#1063]
For a mutation

```elixir
    payload field(:post_subscription) do
      input do
        field(:email, non_null(:string))
      end
        
      output do
        field(:result, :boolean)
      end
        
      resolve(&subscribe/3)
    end

```

If `subscribe/3` returns `{:error, nil}`, the response is
```json
{
  "data": {
    "postSubscription": null
  }
}
```
If `subscribe/3` returns `{:error, "I am an error"}`, the response is
```json
{
  "data": {
    "postSubscription": null
  },
  "errors": [
    {
      "locations": [
        {
          "column": 3,
          "line": 4
        }
      ],
      "message": "I am an error",
      "path": [
        "postSubscription"
      ]
    }
  ]
}
```

### Environment

* Elixir version (elixir -v): 1.11
* Absinthe version (mix deps | grep absinthe): 1.5

### Expected behavior

It should return an error resposne
### Actual behavior

It is returning a successful response

**Comment by benwilson512** [comment]
@chungwong I do wonder what the expected behaviour should be here. Absinthe does not allow for example `{:error, message: nil}`. We generally treat `{:error, message}` as shorthand for `{:error, message: message}`.

I agree that Absinthe's current response is wrong. However, my inclination is that `{:error nil}` should simply raise an error.

**Comment by chungwong** [comment]
according to the error message of resolving
```elixir
## For an error result

One or more errors for a field can be returned in a single `{:error, error_value}` tuple.

`error_value` can be:
- A simple error message string.
- A map containing `:message` key, plus any additional serializable metadata.
- A keyword list containing a `:message` key, plus any additional serializable metadata.
- A list containing multiple of any/all of these.
- Any other value compatible with `to_string/1`.

### Examples

A simple error message:

    {:error, "Something bad happened"}

Multiple error messages:

    {:error, ["Something bad", "Even worse"]

Single custom errors (note the required `:message` keys):

    {:error, message: "Unknown user", code: 21}
    {:error, %{message: "A database error occurred", details: format_db_error(some_value)}}

Three errors of mixed types:

    {:error, ["Simple message", [message: "A keyword list error", code: 1], %{message: "A map error"}]}

Generic handler for interoperability with errors from other libraries:

    {:error, :foo}
    {:error, 1.0}
    {:error, 2}

## To activate a plugin

`{:plugin, NameOfPluginModule, term}` to activate a plugin.
```

And the last case `- Any other value compatible with `to_string/1``
```
iex(3)> to_string(nil)
""
```

So I would say according to the spec, it should not raise

**Comment by benwilson512** [comment]
Yup, ok, that's a compelling argument :)

**Comment by binaryseed** [comment]
That's the Absinthe error help, but the GraphQL spec itself says:

> Every error must contain an entry with the key message with a string description of the error intended for the developer as a guide to understand and correct the error.

http://spec.graphql.org/draft/#sec-Errors.Error-result-format

Since it specifies the minimum data for an error is a map with a `message`, it's not clear to me what `{:error, nil}` would return as the message... An empty string doesn't seem great

**Comment by chungwong** [comment]
> That's the Absinthe error help, but the GraphQL spec itself says:
> 
> > Every error must contain an entry with the key message with a string description of the error intended for the developer as a guide to understand and correct the error.
> 
> http://spec.graphql.org/draft/#sec-Errors.Error-result-format
> 
> Since it specifies the minimum data for an error is a map with a `message`, it's not clear to me what `{:error, nil}` would return as the message... An empty string doesn't seem great

It is a bit tricky.
At the moment `{;error, ""}` is returned as an normal `error` response(not raising), so if `{:error, nil}` is converted to `{:error, ""}` like the `Absinthe Error` suggested, it will not introduce a breaking change. `{:error, nil}` is `corrected` to behave the same as `{:error, ""}`

It is a bit silly to raise which breaks the function if a mutation simply returns `{:error, ""}`

**Comment by benwilson512** [comment]
See PR.
