### ISSUE TITLE
Documentation missing for `%{batch: _, item: _}` map syntax in dataloader helper

### ISSUE THREAD

**Issue by Nickforall** [absinthe-graphql/absinthe#1066]
There is a helper for handling custom run_batch functions in dataloader which has been incredibly useful to me, but it doesn't seem to be [documented](https://hexdocs.pm/absinthe/Absinthe.Resolution.Helpers.html#dataloader/3) anywhere but in this issue #903.

As described in that issue, with the example given in [the Dataloader docs about custom batch queries](https://hexdocs.pm/dataloader/Dataloader.Ecto.html#module-custom-batch-queries), the following example works.

```elixir
resolve dataloader(Posts, fn user, _args, _ ->
  %{batch: {{:one, Post}, %{}}, item: [post_count: user]}
end)
```

Don't have the time to write docs for this right now, so creating an issue to keep track in case anyone wants to pick it up :)

**Comment by cheerfulstoic** [comment]
Just created PR #1067 to hopefully at least make a start of this documentation
