### ISSUE TITLE
Add query reducers

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe#107]
> Sometimes in can be helpful to perform some analysis on a query before executing it. An example is complexity analysis: it aggregates the complexity of all fields in the query and then rejects the query without executing it if complexity is too high. Another example is gathering all Permission field tags and then fetching extra user auth data from external service if query contains protected fields. This need to be done before the query started to execute.

Sangria reference:  http://sangria-graphql.org/learn/#query-reducers

**Comment by bruce** [comment]
Another big idea for the roadmap, tagged.
