### ISSUE TITLE
Protection against malicious queries

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe#108]
Given the nature of GraphQL, a client can easily send infinitely deep queries which may have high impact on server performance. Absinthe should help guard against this by analyzing query complexity before executing it and should reject it if it goes beyond a given customizable threshold.

This is the ideal use case / application for #107

Being able to limit query depth would also probably be valuable as well.

**Comment by bruce** [comment]
This is on the roadmap: http://absinthe-graphql.org/roadmap/

**Comment by tlvenn** [comment]
Hi Bruce, do you think it would be useful to have a meta issue to track the roadmap within github ?

**Comment by bruce** [comment]
@tlvenn Yes. I've added a "roadmap" label we can apply here to track the larger areas of work we have planned out.

**Comment by bruce** [comment]
Closing, as it's tagged roadmap and we use that for archiving good "big" ideas that we want to do -- but keeping our issues list focused on actionable, smaller steps/bugs. We're putting the foundations of what will support complexity and query limiting into our "internal representation" code, and will review these roadmap items as that progresses.
