### ISSUE TITLE
Int built-in is not spec compliant

### ISSUE THREAD

**Issue by kdawgwilk** [absinthe-graphql/absinthe#1087]
### Environment

* Elixir version: 1.10 | 1.11
* Absinthe version: 1.6.4 | master
* Client Framework and version: Apollo

### Expected behavior

https://spec.graphql.org/draft/#sec-Int.Input-Coercion
>Input Coercion
>
>When expected as an input type, only integer input values are accepted. All other input values, including strings with numeric content, must raise a request error indicating an incorrect type. If the integer input value represents a value less than -2^31 or greater than or equal to 2^31, a request error should be raised.

>Numeric integer values larger than 32-bit should either use String or a custom-defined Scalar type, as not all platforms and transports support encoding integer numbers larger than 32-bit.

An error when a larger than 32-bit JSON number is passed for a field marked as Int type

### Actual behavior

Absinthe does not have any issues with the number size

### Relevant Schema/Middleware Code

schema
```elixir
mutation do
  field :foo, :boolean do
    arg :some_int, non_null(:integer)
    resolve &MyResolver.resolve_foo/2
  end
end
```
mutation
```graphql
mutation ($someInt: Int!) {
  foo(someInt: $someInt)
}
```
variables
```json
{
  "variables": {
    "someInt": 5390900000 
  }
}
```

### Notes

Unfortunately, this would likely be a breaking change for absinthe consumers since they would have to change fields frequently using numbers larger than 32-bit to a custom Scalar or String type

**Comment by benwilson512** [comment]
Absinthe actually does have size checks https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/type/built_ins/scalars.ex#L103 but it uses different limits. Maybe the spec has changed over time?

**Comment by kdawgwilk** [comment]
I just reviewed the spec back to the [July 2015 version](https://spec.graphql.org/July2015/#sec-Int) and it was still only 32-bit

**Comment by kdawgwilk** [comment]
Do we have a path forward on this to become spec compliant?  Or is this too large of a breaking change to consider?

**Comment by benwilson512** [comment]
@kdawgwilk I think the path forward here should be to introduce a setting that can be enabled on a schema to make the integers spec complaint. We can also start warning on schemas that are not using that setting, and note that in Absinthe 2.0 it will change.

I do not want to simply change the limits and potentially break other scenarios where people are using 64 bit integers.

**Comment by kdawgwilk** [comment]
Duplicate of https://github.com/absinthe-graphql/absinthe/issues/921
