### ISSUE TITLE
Missing documentation: Using imported SDL

### ISSUE THREAD

**Issue by gfviegas** [absinthe-graphql/absinthe#1092]
As seen in https://hexdocs.pm/absinthe/Absinthe.Schema.Notation.html#import_sdl/1 there is no proper documentation for using external graphql schemas definitions, neither how to correctly link your query/mutation/type definition to its resolver

![image](https://user-images.githubusercontent.com/6178801/127611002-fe174d86-587b-4c5a-84b2-cd65cd615095.png)

I am trying to figure out how to use this feature by searching issues hoping for a bug reproduction repository but couldn't even find one :(

I would happily willing to write the docs myself if I could have some example repository or any reference at all.

**Comment by maartenvanvliet** [comment]
You can look into the tests for examples on how it works: https://github.com/absinthe-graphql/absinthe/blob/master/test/absinthe/schema/notation/experimental/import_sdl_test.exs

There are also some examples here: https://github.com/newrelic/absinthe-schema-stitching-example/blob/master/apps/soccer_team_app/lib/soccer_team_app/schema.ex
