### ISSUE TITLE
Fetching field including a number?

### ISSUE THREAD

**Issue by mathieuprog** [absinthe-graphql/absinthe#1115]
Hello, I try to fetch a field named:
* `is_24_hour_clock` in the schema server side
* `is24HourClock` in the document client side

but it seems not working because there is a number in the field name.

The error returned by Absinthe is the following:

> Uncaught (in promise) GraphQLError: [{"locations":[{"column":5,"line":11}],"message":"Cannot query field \"is24HourClock\" 
> on type \"Account\". Did you mean \"is24HourClock\"?"}]
>    at Client.request (client.js:20)

### Environment

* Elixir version (elixir -v):
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Elixir 1.12.3 (compiled with Erlang/OTP 22)

* Absinthe version (mix deps | grep absinthe):
absinthe 1.6.4

* Client Framework and version (Relay, Apollo, etc):
no framework

**Comment by kdawgwilk** [comment]
If you remove the `_` after the number I think it will work e.g. `is_24hour_clock` I ran into this before and it's a bit quirky

**Comment by mathieuprog** [comment]
I changed `:is_24_hour_clock` to `:is_24hour_clock` in the Absinthe schema. I still can't get the value from a request.

I tried:

1. is24HourClock
error: Cannot query field \"is24HourClock\" on type \"Account\". Did you mean \"is24hourClock\"?

2. is24hourClock
error: Cannot query field \"is24hourClock\" on type \"Account\". Did you mean \"is24hourClock\"?

**Comment by kdawgwilk** [comment]
```elixir
iex(1)> Macro.underscore("is24HourClock") 
"is24_hour_clock"
```
Looks like you need to do `:is24_hour_clock`

**Comment by mathieuprog** [comment]
Thank you! Should have tried `Macro.to_underscore` myself when Ben mentioned it, sorry.
Working perfectly now! <3
