### ISSUE TITLE
Get grandparent value in resolver function 😭 

### ISSUE THREAD

**Issue by dylan-chong** [absinthe-graphql/absinthe#1132]
I'm going to firstly rip off someone elses issue because that saves me having to write a description: https://github.com/graphql/graphql-js/issues/1098

# Ex1

![image](https://user-images.githubusercontent.com/17482349/145509462-f4ddbef4-8a24-4beb-b578-3765af6d7651.png)

We want to fetch the team for the given competition id and season id. We can get the season id from the first argument of the team resolver,  but there's no way of getting the competition id.

# Ex2

 my personal example is

```
query order() {
  order(id: ... , provider: ...) { // id/provider Is the dual primary key
    items {
      # product_for_order_item resolver.
      #   will do: select * from products where p.id = item.id and p.provider = order.provider -- NOTE We don't have the order.provider here
      product { } # 
    }
  }
}

```

# Ex3

An absinthe specific Example: https://elixirforum.com/t/access-to-grand-parent-fields-in-absinthe-resolver/40500

# Hacky solution

my current solution (re ex2) is to add an Ecto virtual `item.parent_provider` field, and *every single place where there is an order type resolver* populate each `item.parent_provider` field. spray code everywhere, much ugly

#  possible solutions

-  what if we had a way to access not only the parent, but the parent's parent.  that would solve the issue.
-  what if we had a way to pass arbitrary context into child resolvers, including being able to pass the parent resolver's result to the child

 both of these solutions would required the resolve is to be executed top level down, so I'm not sure if that is going to need a (breaking) change

**Comment by benwilson512** [comment]
Hey @dylan-chong the preference is to use the forums or other locations for discussions / questions and use the issue tracker for concrete bugs or other similar issues, thanks!

**Comment by dylan-chong** [comment]
hey @benwilson512 Have discussed a little bit in the elixir forum post linked in the original description.

They doesn't seem to be a way to implement a general, easy solution to this problem at the moment.

What would be really good is to have a list of `ancestors`  as a field in the resolution struct. This would make our lives so much easier. consider this a feature request

**Comment by benwilson512** [comment]
Hi @dylan-chong, I have replied in the forum thread and would prefer to keep the discussion there instead of doing it in 2 places.
