### ISSUE TITLE
Convert data in result to camel-case?

### ISSUE THREAD

**Issue by thojanssens** [absinthe-graphql/absinthe#1136]
I'm using the function `put_result` like so:
```elixir
Absinthe.Resolution.put_result(
  resolution,
  {
    :error,
    message: "unauthorized",
    code: "UNAUTHENTICATED",
    login_page: Routes.user_session_path(conn, :new)
  }
)
```

I realize that the key `login_page` is not converted into camel-case on the Javascript side.

Is that the desired behavior?

**Comment by kdawgwilk** [comment]
yes because this is being done after an `Absinthe.Phase` which does the conversion.  To learn more about this you can search the codebase for adapter to see where its used

**Comment by benwilson512** [comment]
This is the desired behavior, Absinthe has no idea about the inner contents of your error messages, it is opaque to Absinthe.
