### ISSUE TITLE
Duplicate Content-type header cause request to fail with an obscure error

### ISSUE THREAD

**Issue by epinault** [absinthe-graphql/absinthe#1137]
If submitting a bug, please provide the following:

### Environment

* Elixir version (elixir -v):

Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Elixir 1.12.1 (compiled with Erlang/OTP 22)

* Absinthe version (mix deps | grep absinthe):
* absinthe 1.6.3 (https://github.com/podium/absinthe.git) (mix)
* absinthe_plug 1.5.8 (Hex package) (mix)
  locked at 1.5.8 (absinthe_plug) bbb04176

* Client Framework and version (Relay, Apollo, etc):

### Expected behavior

I was expecting Absinthe to respond properly if the content-type header is duplicated since it is fine per RFC in HTTP

### Actual behavior

Instead we get an error. See https://github.com/sneako/finch/issues/170 for more details of the issue

```
"{\"errors\":[{\"locations\":[{\"column\":2,\"line\":1}],\"message\":\"syntax error before: \\\"\\\\\\\"query\\\\\\\"\\\"\"}]}",
```

**Comment by benwilson512** [comment]
From the html spec:

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list

The `if and only if` bit is important. Content type is not a comma separated list. Finch's choice to focus on performance makes sense for what it is, but basically Finch is making it your job to send valid content types. Multiple content types, as far as I can tell, are not valid. What should absinthe_plug do anyway if they have different values?
