### ISSUE TITLE
Add generic import_directives for macro based schemas

### ISSUE THREAD

**Issue by kdawgwilk** [absinthe-graphql/absinthe#1152]
We have a library that defines its own prototype schema https://github.com/DivvyPayHQ/absinthe_federation/blob/main/lib/absinthe/federation/schema/prototype.ex that defines its own directives and we have a phoenix/absinthe API app that uses this library but also wants to define its own type system directives so we need a way to merge these two prototypes together.  Having this `import_directives` would really make this pretty straightforward.

**Comment by kdawgwilk** [comment]
This has me thinking what about `import_scalars` or do those fall under `import_types`?  and why would type level directives not also fall under `import_types`?

**Comment by benwilson512** [comment]
Scalars fall under types. Directives are in their own distinct categories, everything else is part of the type system.
