### ISSUE TITLE
absinthe-graphql.org Domain is expired

### ISSUE THREAD

**Issue by brweber2** [absinthe-graphql/absinthe#1163]
Not sure exactly where to submit this but the absinthe-graphql.org domain is expired so the website is not working. 

I didn't see an existing issue so I just wanted to bring this to your attention in case you were not aware. If this was planned please feel free to close this issue. Thanks.

**Comment by benwilson512** [comment]
Hey @brweber2 we are aware and we're working on it, thanks for making an issue though!

**Comment by benwilson512** [comment]
Fixed!
