### ISSUE TITLE
Republish 1.6.6 as 1.6.8

### ISSUE THREAD

**Issue by rewritten** [absinthe-graphql/absinthe#1173]
`mix deps` does not care (except for a colored output) whether a version is retired or not. Only `mix hex.audit` complains if any _current_ version (from `mix.lock`) is removed.

Projects that have pinned `absinthe` to `~> 1.6.6` may therefore get wrongly updated to `1.6.7` (for instance dependabot does it).

If you could republish 1.6.6 as 1.6.8, a project will upgrade to 1.6.8 instead, and therefore not break for an automatic update.

**Comment by benwilson512** [comment]
Done.
