### ISSUE TITLE
Nil values from string keyed maps

### ISSUE THREAD

**Issue by Eptis** [absinthe-graphql/absinthe#118]
I am not sure if it's a bug or a feature. I have a map with strings as keys that is returned in a resolve function. Now the query resolves correctly, but all the values returned are nil. If I convert the map to use atoms for keys the values are there. 

Is this expected behavior? I know that string keyed maps are used for external data sources (I'm loading from a file) so I'm not sure if it's a safeguard for absintheql

**Comment by benwilson512** [comment]
This is indeed the default behaviour, you can set your own default resolver as covered in the `Default Resolver` section of https://hexdocs.pm/absinthe/Absinthe.Schema.html if you would like Absinthe to fall back on binary keys should atom keys fail.
