### ISSUE TITLE
Support empty string in operationName

### ISSUE THREAD

**Issue by jlevycpa** [absinthe-graphql/absinthe#119]
Currently the query will fail if `operationName: ""` is passed. Most clients (including graphiql) will send `null` when an operation name isn't provided, which works fine currently.

apollo-client is currently sending `""` but will change shortly to `null` to conform with graphiql.

@benwilson512 requested I created this issue so `""` can be supported to maximize compatibility with other clients.

**Comment by bruce** [comment]
@benwilson512 Should this be moved into absinthe_plug?
