### ISSUE TITLE
Query parameter passing

### ISSUE THREAD

**Issue by churcho** [absinthe-graphql/absinthe#121]
Could you update the documentation with an example of how one can use query parameters when using a client like GraphiQL (I can't seem to make variable substitution using the $ sign) and also an indication of how one can make api calls to the GraphQL endpoint from within an application and get results from an HTTP Client for example httpoison. This would give a brief idea of how to implement this as a server and have client applications make calls to the various queries and mutations.

**Comment by benwilson512** [comment]
Hey there. I'm happy to try to clarify stuff. http://absinthe-graphql.org/guides/plug-phoenix/ contains a fair bit of information on the whole variables and HTTP server side of things.

About GraphiQL specifically, the variables are just a JSON object. For example:

```
    field :hello, :string do
      arg :name, :string

      resolve fn %{name: name}, _ ->
        {:ok, "Hello #{name}!"}
      end
    end
```

![image](https://cloud.githubusercontent.com/assets/247817/16356851/10d0140c-3ab4-11e6-9bf5-995618c19924.png)

There's nothing absinthe specific about how any of that bit works.

Is there anything not covered in the guide there that you would like to see?

**Comment by churcho** [comment]
I have 

```
mutation MutationCreateProfile{
    profile(firstName:$firstName, lastName:$lastName, userId:$userId)
  {
 	firstName
	lastName
  }
}
```
My query variable looks like:
```
{
   	"firstName": "John",
	"lastName": "Doe",
	"userId": "8f1810f4-3a22-11e6-ac61-9e71128cae77"
	
}
```
That doesn't seem to work. What could I be doing wrong?

**Comment by benwilson512** [comment]
You're missing the variable declarations on the document. You need 
```
mutation MutationCreateProfile($firstName: String, $lastName: String, $userId: ID)
```

Obviously update the types as necessary.

**Comment by churcho** [comment]
If I do that what goes into my  `createProfile` ?

My schema looks like this:

```
mutation do
    @desc "Create a Profile"
    field :create_profile, type: :profile do
      arg :user_id, non_null(:string)
      arg :first_name, non_null(:string)
      arg :last_name, non_null(:string)
      resolve &GraphQL.Resolvers.Profile.create/2
    end

  end
```

**Comment by benwilson512** [comment]
That looks correct to me!

**Comment by benwilson512** [comment]
Just to be clear, the need to declare variables at the top of the document is not an Absinthe specific thing either, but part of the GraphQL spec.

**Comment by churcho** [comment]
Got it!

```
mutation MutationCreateProfile($firstName: String, $lastName: String, $userId: String){
  
  createProfile(firstName: $firstName, lastName: $lastName, userId: $userId)
  {
 	firstName
	lastName

  }
}
```

Thanks. Everything works well now. :+1:
