### ISSUE TITLE
Unable to use import_types or import_fields conditionally

### ISSUE THREAD

**Issue by michaelcaterisano** [absinthe-graphql/absinthe#1217]
### Environment

* Elixir version (elixir -v): 1.14.2
* Absinthe version (mix deps | grep absinthe): [Fork](https://github.com/frameio/absinthe/tree/v1_7) of 1.7 

I'm trying to use the `import_types` and `import_fields` macros conditionally, but it seems that both macros are evaluated even when used in an if statement whose condition is hard-coded to `false`. 

### Schema definition

I have a schema file like this:

```elixir
defmodule Schema do

  use Absinthe.Schema
  
  import_types(Some.Module)
  if false, do: import_types(Another.Module) # import_types is still evaluated and these types end up in the schema
  
  query name: "Query" do
    import_fields(:fields_from_some_module)
    if false, do: (:fields_from_another_module) # import_fields is still evaluated and these fields end up in the schema
  end

end
```

**Comment by benwilson512** [comment]
Hi @michaelcaterisano I would consider using a custom schema compilation phase to conditionally add these schemas in this case. Making the macro system work with conditionals like this is extremely difficult, and is not planned.

**Comment by michaelcaterisano** [comment]
Thanks @benwilson512, I was wondering if that might be the next best move. I'll try that out.
