### ISSUE TITLE
How to use Decimal type to display normal format of serialize

### ISSUE THREAD

**Issue by Naupio** [absinthe-graphql/absinthe#1229]
[defdelegate serialize(value), to: Decimal, as: :to_string](https://github.com/absinthe-graphql/absinthe/blob/34cd95d49417a73f5131f799ad3713bfba0c8889/lib/absinthe/type/custom/decimal.ex#L5)

iIn the custom decimal type module, it defdelegate the serialize function to Decimal.to_string which default display type is scientific https://github.com/ericmj/decimal/blob/master/lib/decimal.ex#L1313, how can i use normal type for this scenario.

I know we can define a new decimal type for our project and change the serialize function defdelegate to Decimal.to_string with :normal type.

Does absinthe support change the inner :decimal type serialize function?

**Comment by benwilson512** [comment]
Hi @Naupio in general please use the Elixir forums for questions, not the issue tracker.

As a short answer here: schema compilation phases allow you to alter any of the built in types. If you make a post on the Elixir forums I'm happy to go into more detail there.
