### ISSUE TITLE
Schema compilation with absinthe 1.7.1 generates warnings with elixir version < 1.14

### ISSUE THREAD

**Issue by MaeIsBad** [absinthe-graphql/absinthe#1233]
### Environment

* Elixir version (elixir -v): 1.11.2
* Absinthe version (mix deps | grep absinthe): 1.7.1 (absinthe) c0c4dbd9
This issue doesn't occur with absinthe 1.7.0
* Client Framework and version (Relay, Apollo, etc): n/a

### Expected behavior

Absinthe doesn't generate warnings during schema compilation

### Actual behavior

During compilation of a schema 4 warnings are emitted

```
root@31064b1ea5b7:/code# mix compile --warnings-as-errors
Compiling 1 file (.ex)
warning: this clause cannot match because a previous clause at line 74 always matches
  deps/absinthe/lib/absinthe/phase/schema/compile.ex:74

warning: this clause cannot match because a previous clause at line 74 always matches
  deps/absinthe/lib/absinthe/phase/schema/compile.ex:74

warning: this clause cannot match because a previous clause at line 74 always matches
  deps/absinthe/lib/absinthe/phase/schema/compile.ex:74

warning: this clause cannot match because a previous clause at line 74 always matches
  deps/absinthe/lib/absinthe/phase/schema/compile.ex:74
```

since the warnings occur during code generation this will cause `mix compile --warnings-as-errors` to fail, which causes problems for CI environments

### Relevant Schema/Middleware Code

```elixir
if not Elixir.Version.match?(System.version(), ">= 1.11.0 and < 1.14.0") do 
  IO.warn("Elixir version 1.14 or newer will not emit a warning")
end

defmodule MyAppWeb.Schema do
  use Absinthe.Schema

  # Example data
  @items %{
    "foo" => %{id: "foo", name: "Foo"},
    "bar" => %{id: "bar", name: "Bar"}
  }

  object :item do
    field(:id, :id)
    field(:name, :string)
  end

  query do
    field :item, :item do
      arg(:id, non_null(:id))

      resolve(fn %{id: item_id}, _ ->
        {:ok, @items[item_id]}
      end)
    end
  end
end
```

**Comment by MaeIsBad** [comment]
After git bisecting it seems like 7eec586ca47a17da265141ad44aad7d98cf3a355 is the first bad commit

**Comment by MaeIsBad** [comment]
After bisecting 5f1b05b2878a1075b0b2ee875b3542df58e7c8f3 is the first bad commit

**Comment by MaeIsBad** [comment]
This patch

```
diff --git a/lib/absinthe/phase/schema/build.ex b/lib/absinthe/phase/schema/build.ex
index a5b5f895..b917017f 100644
--- a/lib/absinthe/phase/schema/build.ex
+++ b/lib/absinthe/phase/schema/build.ex
@@ -5,12 +5,15 @@ defmodule Absinthe.Phase.Schema.Build do
     %{schema_definitions: [schema]} = blueprint

     types = build_types(blueprint)
-    directive_artifacts = build_directives(blueprint)
+
+    directive_artifacts =
+      (schema.directive_artifacts ++ build_directives(blueprint))
+      |> Enum.dedup_by(fn v -> v.identifier end)

     schema = %{
       schema
       | type_artifacts: types,
-        directive_artifacts: schema.directive_artifacts ++ directive_artifacts
+        directive_artifacts: directive_artifacts
     }

     blueprint = %{blueprint | schema_definitions: [schema]}
```

fixes 2/4 warnings, but a duplicate
`__absinthe_directive__(:include)`
and
`__absinthe_directive__("include")`
functions still get generated

**Comment by rlopzc** [comment]
We are using federation and 1.7.1 also broke stuff.

From our debugging session: It seems like the link directive broke? It returns null for a particular field required by the introspection query, and that in turn causes backend to throw

**Comment by MaeIsBad** [comment]
Nothing on my end

**Comment by maartenvanvliet** [comment]
When importing directives from the prototype it duplicates some of them. So something along the lines in the patch file above would work. Replacing `Enum.dedup_by` with `Enum.uniq_by` would improve upon it IMO, as there's no guarantee that the directives are consecutive. Feel free to file a PR.

Whilst investigating, I found a similar bug happens with the `extend` notation, this can also cause multiple functions with the same function heads to be generated. This is trickier to solve though. 

I'm puzzled why this gives errors for elixir < 1.13, but no longer for elixir 1.13. Cannot find anything in the changelog of elixir that points to this.

**Comment by MaeIsBad** [comment]
> Replacing Enum.dedup_by with Enum.uniq_by would improve upon it IMO, as there's no guarantee that the directives are consecutive. Feel free to file a PR.

Ahh, that's why my patch still generated errors for include directives. Thanks! I'll open a PR

**Comment by benwilson512** [comment]
Hey folks, I am having difficulty reproducing this. If I compile the example module on Elixir 1.13.4 OTP 25 I do not get any warnings. Let me see if I can get OTP 24 installed.

**Comment by benwilson512** [comment]
Ah! So I think the actual change is OTP 24 vs OTP 25. No matter what Elixir version I run on OTP 25 (within those that are supported) I get no warnings, but if I use OTP 24 I do. @maartenvanvliet is this related to the removal of the digraph stuff?

**Comment by maartenvanvliet** [comment]
The digraph removal wasn't merged yet, so it's not related. 

Seeing [Jose's comment](https://github.com/elixir-lang/elixir/issues/12523#issuecomment-1506789799), it could be very well be something in OTP changing. 

As there are multiple places where code is generated in Absinthe, this warning was helpful in catching bugs.
