### ISSUE TITLE
Subscriptions don't trigger with namespaced mutations

### ISSUE THREAD

**Issue by mbuffa** [absinthe-graphql/absinthe#1240]
Hello there.

### Environment

* Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
* Elixir 1.14.1 (compiled with Erlang/OTP 25)
* Absinthe 1.7.0

### Expected behavior

Either:
* Triggers on Subscription should trigger a broadcast on namespaced mutations, OR,
* The fact that a mutation in another namespace wouldn't trigger a subscription should be mentioned in the docs

### Actual behavior

With the schema described below, executing the mutation wouldn't execute the subscription.

For this scenario, only publishing with the subscription name manually would produce an effect:
```elixir
:ok = Absinthe.Subscription.publish(MyWeb.Endpoint, payload, something_created: "*")
```

Putting both subscription and mutation on the same level (in this case, the root node) of the GraphQL schema solves the issue.

Technically speaking, I don't think this is a bug, but I think this should be at least mentioned in the docs, or in the related guide (and I can send a PR, if you think this issue is legit). I looked into GraphQL spec, Apollo Server doc and assumed triggers aren't part of the GQL spec.

Relevant Elixir Forum post:
https://elixirforum.com/t/absinthe-subscription-trigger-doesnt-work-for-namespaced-mutation/43053

### Relevant Schema/Middleware Code

```elixir
defmodule MySchema do
  ...

  import_types(MySchema.Mutation)
  import_types(MySchema.Subscription)

  mutation do
    import_fields(:my_mutations)
  end

  subscription do
    import_fields(:my_subscriptions)
  end
end

defmodule MySchema.Mutation do
  object :my_mutations do
    payload field(:add_something) do
      ...
    end
  end
end

defmodule MySchema.Subscription do
  object :my_subscriptions do
    field :something_created, :something do
      config(fn _args, _ ->
        {:ok, topic: "*"}
      end)

      trigger(:add_something,
        topic: fn _ ->
          "*"
        end
      )

      resolve(fn parent, _, _ ->
        {:ok, parent}
      end)
    end
  end
end
```

**Comment by seivan** [comment]
Sorry, @benwilson512 you mentioned in the [forums](https://elixirforum.com/t/absinthe-subscription-trigger-doesnt-work-for-namespaced-mutation/43053/2) that it's not spec compliant to have "nested mutation field, that's incorrect.

It's a good way to namespace things so you don't have a thousand mutations on root level.

It also allows for better API


```gql
  mutation {
  posts(id: 3) {
    newComment(message: "hello") {
      id
    )
  }

  ```
  
  Afaik GQL spec does not disallow and why should it be non-compliant? 

Triggers is actually an Absinthe-only(?) concept and not something I've seen in other GQL servers, and I quite like it.
It's smarter for the subscription to define what triggers it as opposed to each individual mutation remember what subscriptions it should trigger. 

It should support nested field mutations, since GQL supports it.

**Comment by benwilson512** [comment]
Hi @seivan you are always welcome to call `publish` manually from within a resolver if you like. As you say, triggers are an Absinthe specific concept, and they're going to be reserved for fields on the root mutation object, and no other objects. Root mutation object fields are the only fields called out in the spec as having side effects https://spec.graphql.org/draft/#sec-Mutation

If you can find any examples of "nested" mutation fields in the spec I will happily reconsider.

**Comment by mbuffa** [comment]
I think we deviated here. OP was not about the GraphQL spec, but about Absinthe DSL, since it supports [the syntax I mentioned](https://hexdocs.pm/absinthe/importing-fields.html#an-example).

> As you say, triggers are an Absinthe specific concept, and they're going to be reserved for fields on the root mutation object

No problem, and that would be great to have that in the docs!
