### ISSUE TITLE
"Unknown Registry" when publishing during node startup or shutdown

### ISSUE THREAD

**Issue by aj-foster** [absinthe-graphql/absinthe#1247]
Hello there 👋🏼 

Our observation of this issue does involve `absinthe_phoenix`, however all of the relevant code appears to be in this library.

### Environment

* Elixir version (elixir -v): 1.14.2
* Absinthe version (mix deps | grep absinthe): 1.7.1
* Client Framework and version (Relay, Apollo, etc): N/A

### Expected behavior

When calling `Absinthe.Subscription.publish/3` in an Erlang cluster, it is reasonable that one of the nodes may not yet be fully started (and therefore not have an endpoint registry process yet). If this is the case, I would expect Absinthe to gracefully handle the lack of an endpoint registry on that node and continue publishing to all remaining nodes without an error.

### Actual behavior

An error occurs with the following message:

```
ArgumentError: unknown registry: [MyAppWeb].Endpoint.Registry. Either the registry name is invalid or the registry is not running, possibly because its application isn't started
  File "lib/registry.ex", line 1068, in Registry.meta/2
  File "lib/absinthe/subscription.ex", line 194, in Absinthe.Subscription.publish_remote/3
  File "lib/absinthe/subscription.ex", line 116, in Absinthe.Subscription.publish/3
  File "lib/[my_app_web]/controllers/[my_controller].ex", line 23, in [MyAppWeb].[MyController].[action_name]/2
  File "lib/[my_app_web]/controllers/[my_controller].ex", line 1, in [MyAppWeb].[MyController].action/2
    defmodule [MyAppWeb].[MyController] do
  File "lib/[my_app_web]/controllers/[my_controller].ex", line 1, in [MyAppWeb].[MyController].phoenix_controller_pipeline/2
    defmodule [MyAppWeb].[MyController] do
  File "lib/phoenix/router.ex", line 430, in Phoenix.Router.__call__/5
  File "lib/plug/error_handler.ex", line 80, in [MyAppWeb].Router.call/2
```

### Relevant Schema/Middleware Code

This error comes about due to a simple call to `Absinthe.Subscription.publish/3`:

```
Absinthe.Subscription.publish([MyAppWeb].Endpoint, data, info)
```

Note that this call is made in response to a REST request, so we can be reasonably sure that the endpoint and its registry are properly started on the node issuing the publication.

**Comment by aj-foster** [comment]
Note that this is a multi-node setup.

* Node 1 receives a REST request and publishes out to a subscription
* Node 2, which has connected to the cluster but not yet started its endpoint, appears to cause the error.

**Comment by benwilson512** [comment]
Hey @aj-foster I'm not sure that that matches the stacktrace you're showing in your logs. The stacktrace you show has:

```
  File "lib/absinthe/phoenix/channel.ex", line 57, in Absinthe.Phoenix.Channel.handle_in/3
```

`Absinthe.Phoenix.Channel.handle_in/3` means that somebody has managed to get a websocket hooked up to the node.

**Comment by aj-foster** [comment]
Hi @benwilson512 I understand where you're coming from there, and I'm not sure that second error is completely related.

However, as further data, I just encountered this error again during a deploy, and it turn out it was generated by a node that was shutting down, not a node that was starting up. Not sure if this really changes anything, but it's interesting that the endpoint could possibly still be handling requests while its registry has already disappeared. We're obviously getting into Phoenix territory, but perhaps this spawns some thoughts with you.

In general, can you confirm or deny whether a `publish` call in an Erlang cluster would fail if _a different node_ doesn't have its Endpoint registry started? Trying to create an accurate testing scenario is proving difficult.

**Comment by aj-foster** [comment]
After further investigation it looks like we have both websocket and REST requests that take long enough to get through the authentication phase that it's possible for the Endpoint (and its Registry + PubSub) to shut down before Absinthe handles the subscription document or receives the call to `publish`. This is obviously a problem on our end, and it looks like our best recourse is to rescue what we can and quickly close the connection. There are ways that Absinthe could help mitigate this situation that might be worth exploring, but I'll close this for now.
