### ISSUE TITLE
Graphiql not working with Absinthe.Adapter.Passthrough

### ISSUE THREAD

**Issue by scottschulthess** [absinthe-graphql/absinthe#125]
Using graphiql mounted via Absinthe-plug, I also get an spinner when loading the docs. (Also happens when using graphiql via mac app).  Queries work via graphiql though.

it might be related to this error on load ```typeError: Cannot read property 'kind' of undefined
    at n (http://cdn.jsdelivr.net/graphiql/0.6.0/graphiql.min.js:14:18946)
    at a (http://cdn.jsdelivr.net/graphiql/0.6.0/graphiql.min.js:14:19991)
    at Object.buildClientSchema (http://cdn.jsdelivr.net/graphiql/0.6.0/graphiql.min.js:14:23091)
    at http://cdn.jsdelivr.net/graphiql/0.6.0/graphiql.min.js:1:26604```

Same behavior in graphiql mac app.

**Comment by bruce** [comment]
What versions of absinthe and absinthe_plug?

**Comment by scottschulthess** [comment]
1.1.7 and 1.1.3

**Comment by benwilson512** [comment]
Hey there, can you gist your schema? I'm unable to reproduce with our schema but that likely means it's a matter of introspection not working properly on some type you have that we don't.

Also, the response to the introspection query may be useful.

**Comment by bruce** [comment]
@benwilson512  It's possible newer GraphIQL is expecting the GraphQL April Spec introspection response for directives, which changed a little (may work against Absinthe master)

**Comment by benwilson512** [comment]
The GraphiQL JS version is hard coded in Absinthe Plug and we're on the same version (1.1.3) he is. It does requests / loads docs for us at least. I suppose it could still be that the JS has the april changes, but it only effects some type he has and not any type we have.

**Comment by scottschulthess** [comment]
I'll check about getting a schema that I can reproduce with

**Comment by scottschulthess** [comment]
update: it works on a barebones graphql+phoenix, so I'm looking into why my specific setup is causing problems

**Comment by scottschulthess** [comment]
update: I've been trying quite hard to reproduce this issue in an example app and have been unsuccessful. also removing stuff from our app has not been successful.   I'm probably missing something.

The only clue I have is we get this error about 4x when doing the introspection query against our app but not the sample app with the same schema. 

```
{
  "errors": [
    {
      "message": "Argument `includeDeprecated': Not present in schema",
      "locations": [
        {
          "line": 24,
          "column": 0
        }
      ]
    }, 
```

Does anyone have any clue what generates this error or how I could investigate further?

**Comment by benwilson512** [comment]
If you have debug logging on you should be able to see the introspection query in the logs. Can you gist what that is for you?

**Comment by benwilson512** [comment]
I take it you're unable to gist your actual schema?

**Comment by scottschulthess** [comment]
@benwilson512 i can gist our schema but when I put it into a bare absinthe example app it does not cause this issue.  will check on the logging

**Comment by scottschulthess** [comment]
@benwilson512 I can see the introspection query, the same one works fine against a basic graphql app but generates those errors against my app.   even with the same schema! same version of absinthe, absinthe-plug

**Comment by benwilson512** [comment]
I understand, but right now I have nothing to go on at all. I get that there's been trouble reproducing the issue but if I'm gonna help I need the schema and a copy of the logs with the query you're getting.

**Comment by scottschulthess** [comment]
@benwilson512 ah-ha!   i found it finally 

if you put this line in (we have a camelcase api) it causes the issues with GraphiQL
```config :absinthe, adapter: Absinthe.Adapter.Passthrough```

**Comment by scottschulthess** [comment]
The introspection query that graphiql uses is ``` query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                }
              }
            }
          }
        }
      }
    }
  }

```

**Comment by scottschulthess** [comment]
apparently this is actually a known issue https://github.com/absinthe-graphql/absinthe/issues/76#issuecomment-194111411

**Comment by scottschulthess** [comment]
I'm going to close this as i think it's just an incompatibility with camel case schemas and Graphiql and the correct solution is documented in issue #76 - do a camel case conversion in your resolvers
