### ISSUE TITLE
False positive error for non_null validation

### ISSUE THREAD

**Issue by fuelen** [absinthe-graphql/absinthe#1256]
### Environment

* Elixir version (elixir -v): 1.14.5
* Absinthe version (mix deps | grep absinthe): 1.7.4
* Client Framework and version (Relay, Apollo, etc): -

### Expected behavior

`non_null(list_of(:string))` should not emit `Cannot return null for non-nullable field` error on a list which contains `nil`

### Actual behavior
After update 1.7.1 ->1.7.4 our tests report an error
`Cannot return null for non-nullable field`

### Relevant Schema/Middleware Code
```
    field :my_test, non_null(list_of(:string)) do
      resolve(fn _, _ -> {:ok, ["V1", nil]} end)
    end
```
^ reports `Cannot return null for non-nullable field`

```
    field :my_test, non_null(list_of(:string)) do
      resolve(fn _, _ -> {:ok, nil} end)
    end
```
^ fails with exception `** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom`

**Comment by benwilson512** [comment]
Hi @fuelen, I will review, thanks!
