### ISSUE TITLE
Using GraphQL (and perhaps Absinthe) in messages?

### ISSUE THREAD

**Issue by RichMorin** [absinthe-graphql/absinthe#1257]
<!--

### Precheck

We're a small team and Absinthe is a big project, so please keep the
following in mind when submitting an issue:

- For help and support, use:
  - Our Slack channel (#absinthe-graphql): https://elixir-slackin.herokuapp.com

I tried this (several times) and got the following nastygram:

"Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail"

I don't use Heroku, so I don't think I should try to debug this.

  - The Elixir Forum: https://elixirforum.com

I posted my question on Elixir Forum, at:

[Using GraphQL (and perhaps Absinthe) in messages?](https://elixirforum.com/t/using-graphql-and-perhaps-absinthe-in-messages/57249)

After three days, I've only received one inquiry. So, not much traction there.

  - The documentation, to include guides:  ...

I think my question is far too fanciful for the docs to cover.

- For new features, consider discussing the idea with us via Slack/Forum before submitting an issue

I would, if I could...

So, please humor me and try to tell me how crazy my idea is.  Basically, I'd like to use GraphQL (and preferably Absinthe) for communication between Elixir processes. I know that I could do this using HTTP (etc), but that seems both awkward and inefficient.

Is there a way that I could transmit Absinthe queries and responses over the Erlang message facility. Ideally, I'd like to use Erlang terms, rather than JSON, but that's not a gating issue...

**Comment by benwilson512** [comment]
Hi @RichMorin I saw your forum post about this. The forum is definitely the right place to have that discussion, not the issue tracker here. Thanks!

**Comment by RichMorin** [comment]
I'm willing to accept your decision that the initial discussion of this topic belongs in the forum, though I'm disappointed that my posting there hasn't gotten any traction. However, my issue posting here now reads "No description provided."  So, there's no easy way for anyone to find out what I posted or get to the related forum post.  Sigh.

**Comment by benwilson512** [comment]
> However, my issue posting here now reads "No description provided." 

That is not my doing, that is how it appeared to me when I first looked at this. You are welcome to edit it to anything you like.
