### ISSUE TITLE
small CSS issue on the Absinthe landing page

### ISSUE THREAD

**Issue by RichMorin** [absinthe-graphql/absinthe#1258]
I encountered a small CSS issue on the Absinthe landing page.  Here is a screenshot:

![Image 7-29-23 at 21 39](https://github.com/absinthe-graphql/absinthe/assets/31372/e7c65782-be71-4c4e-aad5-3844f36fdeae)

Note that the bottom two lines are mashed together.

FYI, I'm using the current version of Chrome on a Macbook Air running Monterey. Also, the problem only seems to occur when I use 100% scale factor.

**Comment by conradwt** [comment]
@RichMorin It works as expected in the latest version of Chrome, Chrome Canary, Firefox, and Safari on macOS 13.5 (Ventura).  However, I have been filing many bug reports with the Chrome team because Chrome has been crashing a lot on my Apple Silicon MacBook Pro.

**Comment by RichMorin** [comment]
Interesting! Thanks for the feedback.

**Comment by benwilson512** [comment]
Yeah looks fine to me.
