### ISSUE TITLE
Resolving field of type `[[Value]!]!]` seems to fail with valid values

### ISSUE THREAD

**Issue by mattbaker** [absinthe-graphql/absinthe#1274]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Absinthe version (mix deps | grep absinthe): master
* Client Framework and version (Relay, Apollo, etc): n/a

### Expected behavior

Example  — a field of type `[[String]!]!` resolving with value `[["test", nil]]` should successfully return that data to the user.

I _think_ this should work, though I do get turned around once things start nesting 😂 

### Actual behavior

In reality we end up with `%{data: nil}` and no error message that I can see. Very strange! My guess is Absinthe is viewing this as an error of some sort.

### Relevant Schema/Middleware Code

I haven't dug into Absinthe yet (and I will), but I am opening a PR now with a failing test just to kick things off: PR https://github.com/absinthe-graphql/absinthe/pull/1275

If anyone has any ideas about where to start let me know! Might save me some time :D

**Comment by benwilson512** [comment]
Lists and non null strike again! Likely related to changes made in this PR https://github.com/absinthe-graphql/absinthe/pull/1259/files

**Comment by mattbaker** [comment]
Weirdly enough we noticed this in our production system first which is on this commit from February, so it might go further back:
https://github.com/absinthe-graphql/absinthe/commits/7eec586ca47a17da265141ad44aad7d98cf3a355

```
  "absinthe": {:git, "https://github.com/absinthe-graphql/absinthe.git", "7eec586ca47a17da265141ad44aad7d98cf3a355", [ref: "7eec586ca47a17da265141ad44aad7d98cf3a355"]},
```

(We needed @stellanor's token limit work)

I'll start digging Thursday or Friday assuming no interruptions and let you know what I find!
