### ISSUE TITLE
Not having access to `conn` leads to degraded DX and performance

### ISSUE THREAD

**Issue by mathieuprog** [absinthe-graphql/absinthe#1280]
Absinthe wants to be protocol-agnostic and does not provide the `conn`. However I do not see why it can't be available optionally if Absinthe is running in a web context (which covers also most cases and so let's be pragmatic?).

Consequences for the lack of access to `conn`:

A. Updating session

This is an example from my app, where I need to log in and log out the user, using session cookies:
```elixir
forward "/api", Absinthe.Plug,
  before_send: {__MODULE__, :absinthe_before_send},
  schema: MyAppWeb.GraphQL.Schema
      
def absinthe_before_send(conn, %Absinthe.Blueprint{} = blueprint) do
  cond do
    user = blueprint.execution.context[:user_to_log_in] ->
      log_in_user(conn, user)

    blueprint.execution.context[:should_log_out_user] ->
      log_out_user(conn)

    true ->
      conn
  end
end

# in a resolver:
middleware(fn resolution, _ ->
  with %{value: %User{} = user} <- resolution do
    %{resolution | context: Map.put(resolution.context, :user_to_log_in, user), value: user}
  end
end)
```

* DX: As you can see, I need to add some value in the context from a resolver, for it to be later consumed (if hopefully the atoms are right), which adds complexity in my project, unnecessarily in my opinion.

* Performance: This also means that for *every GraphQL request* the clauses in `absinthe_before_send` are evaluated while it is necessary only for 2 endpoints (log in, log out). Note also that the `cond` clauses may increase along the development of the project. While the impact on performance might be negligible, it just seems weird and unnecessary.

B. Fetching session values

Another example is when a session value needs to be available in the resolvers.

This can be done in a plug:
```elixir
pipeline :api do
  plug :accepts, ["json"]
  plug :fetch_session
  # ...
  plug MyAppWeb.GraphQL.Context
end
  
# Plug `call/2`
def call(conn, _) do
  session_value = Plug.Conn.get_session(conn, :some_value)
  
  Absinthe.Plug.put_options(
    conn, 
    context: # add the value in the context
  )
end
```

* DX: By adding session data in the global context, it is not clear which of these data is consumed by which endpoint.

===

It also seems to me that Absinthe has been developed with JWT in mind, while actually session cookies are a superior form of authentication (in terms of security).

Manipulating session data is not made easy with Absinthe, in an already complex framework.

===

Also thank you for creating and maintaining this library, it is awesome!

**Comment by benwilson512** [comment]
Hey @mathieuprog the issue is that in order to pass in the conn to Absinthe, Absinthe would also need to return the conn. Despite appearances, `conn` is a partially mutable datastructure and it's important that functions which are passed a conn return a conn so that the mutable and immutable parts stay in sync.

You could pass the `conn` itself into the context, and then manipulate it within the context, and ultimately just return it in your `before_send`. However we do not advocate for this because it has more of a foot gun than leaving the conn manipulation to plugs alone.
