### ISSUE TITLE
Absinthe.Subscription.unsubscribe doesn't work

### ISSUE THREAD

**Issue by michaelcaterisano** [absinthe-graphql/absinthe#1283]
### Expected behavior

I called `Absinthe.Subscription.unsubscribe` from my application code. I expected this to remove the `subscriptionId` from the Registry and unsubscribe the client so that they would no longer receive events.

### Actual behavior

The `subscriptionId` is not removed, and the client still receives events.

### Notes

I've tried this against Absinthe 1.7.5 and also against the `master` branch. One puzzling thing is that this _does_ work when I modify the `Absinthe.Subscription` module and call `unsubscribe` at the end of the `subscribe` function; in this case, the `subscriptionId` (or doc_id as it's named in that module) is removed, and the client no longer receives messages. I'm not sure why it doesn't work from my application code.

**Comment by michaelcaterisano** [comment]
I ended up getting this to work by sending an `unsubscribe` message directly to the channel:

```
sub_id = "some-sub-id-i-grabbed" 

broadcast = %Phoenix.Socket.Broadcast{
      topic: "__absinthe__:control",
      event: "unsubscribe",
      payload: %{"subscriptionId" => sub_id}
    }

Phoenix.PubSub.broadcast!(My.PubSub, "__absinthe__:control", broadcast)
```

**Comment by benwilson512** [comment]
Hey @michaelcaterisano which process is calling `unsubscribe`? The caller of `unsuscribe` needs to be the process that also called `subscribe`, it can't be done from a different process.

**Comment by michaelcaterisano** [comment]
@benwilson512 I figured that was the case. I was definitely trying to call `unsubscribe` from a different process than `subscribe`. Do you have thoughts about the workaround above?

**Comment by benwilson512** [comment]
@michaelcaterisano Depending on what you are doing with those channel pids you could `send` them a message and then do it in a ` handle_info`. Otherwise the solution you have seems fine to me.
