### ISSUE TITLE
Feature Request: customizable docset runner for Subscriptions

### ISSUE THREAD

**Issue by michaelcaterisano** [absinthe-graphql/absinthe#1293]
@benwilson512  
I recently forked Absinthe because I needed to override the `run_docset` function, specifically to handle deduplication a bit differently. I ran across this PR that exposes a Behaviour that would allow me to write a custom docset runner without forking Absinthe: https://github.com/absinthe-graphql/absinthe/pull/1218#issuecomment-1906248782

Are there any objections to the direction of this PR? I'd love to see something like this merged and would be happy to help make any changes.

**Comment by michaelcaterisano** [comment]
For viz, this PR would address this issue: https://github.com/absinthe-graphql/absinthe/pull/1295

**Comment by bryanjos** [comment]
This was completed with #1305
