### ISSUE TITLE
Schema compilation fails when defining a camel cased directive

### ISSUE THREAD

**Issue by beligante** [absinthe-graphql/absinthe#1311]
Hello Absinthe Team! 

I'm currently working on introduce federated graphql on my project and in order to progress with that we need to create a custom directive ( `@interfaceObject` ) which is a [fairly new directive](https://www.apollographql.com/docs/federation/federated-types/interfaces/#interfaceobject-definitions). 

When trying to create the directive using absinthe's macro, I get a compilation error stating the directive doesn't exists. If I change the case to snake case for example it works as expected. I'm open to contribute to the repo in order to fix this, but I'm having a hard time finding the right spot to check why this is happening. I made a WIP PR with a broken test to exemplify the issue: https://github.com/absinthe-graphql/absinthe/pull/1310

If you guys point me to the place in code where is issue might be happening, I'm glad to work on a fix.

### Environment

* Elixir version (elixir -v):
  * elixir 1.14.5-otp-24
  * erlang 24.3.4.12

* Absinthe version (mix deps | grep absinthe):
  * 1.7.6
* Client Framework and version (Relay, Apollo, etc): 
  * N / A

### Expected behavior

Allow the creation of camel cased directives 

### Actual behavior

Compilation error
![image](https://github.com/absinthe-graphql/absinthe/assets/6270275/d1f4f0f6-c43e-4e82-861b-272dc2ee61de)

### Relevant Schema/Middleware Code

https://github.com/absinthe-graphql/absinthe/pull/1310

The tests on PR above, fail right on this step: https://github.com/absinthe-graphql/absinthe/blob/main/lib/absinthe/phase/schema/validation/known_directives.ex#L18

**Comment by benwilson512** [comment]
Hi @beligante The elixir schemas always use snake case, and then the adapters allow the usage of camel case.
