### ISSUE TITLE
[Bug] 1.7.7 no persistent term stored with this key

### ISSUE THREAD

**Issue by phanmn** [absinthe-graphql/absinthe#1325]
If submitting a bug, please provide the following:

### Environment

* Elixir version (elixir -v): Elixir 1.16.1 (compiled with Erlang/OTP 26)
* Absinthe version (mix deps | grep absinthe): locked at 1.7.7 (absinthe) 21455198
* Client Framework and version (Relay, Apollo, etc):

### Expected behavior

No error

### Actual behavior

no persistent term stored with this key

### Relevant Schema/Middleware Code

Work on 1.7.6, very simple schema

**Comment by phanmn** [comment]
I comfirm I have the supervision child in my supervision tree. As I said I changed to 1.7.6 it works normally

**Comment by luhagel** [comment]
This happens to me since the update as well, only with the `PersistentTerm` provider enabled though.
Turning that off leads to another problem though, in the form of a `warning: redefining module MyAppWeb.Schema.Compiled` which causes all queries to fail unless i delete the beam file in question before every server start

**Comment by benwilson512** [comment]
If either of you could provide a small sample project that exhibits this behavior that would be very helpful.

**Comment by luhagel** [comment]
@benwilson512  Trying to cobble one together when i get a bit of time 👍

**Comment by luhagel** [comment]
@benwilson512 There you go
No magic in there, create a new project with the newest `phx.new`, add `absinthe`, create a minimalistic schema, add the routing config and it goes boom once you try to run anything against it.

```elixir
defmodule AbsinthePersistentTermWeb.Schema do
  use Absinthe.Schema
  @schema_provider Absinthe.Schema.PersistentTerm

  query do
    field :hello, :string do
      resolve(& &1)
    end
  end
end
```

**Comment by benwilson512** [comment]
Hey @luhagel thanks, looking into it.

**Comment by benwilson512** [comment]
Fixed by https://github.com/absinthe-graphql/absinthe/pull/1326.

**Comment by benwilson512** [comment]
I'll release 1.7.8 here shortly if you can confirm this resolves the issue in your app too.

**Comment by VictorGaiva** [comment]
This also fixed an issue I was having when attempting to update to 1.7.7. My CI would call `mix absinthe.schema.sdl --schema Gateway.Schema`, that would fail due to not finding the definition for some fields.

**Comment by luhagel** [comment]
@benwilson512 fixed it for me 👍

**Comment by benwilson512** [comment]
1.7.8 has been pushed with this fix.
