### ISSUE TITLE
Absinthe 1.7.7 `mix absinthe.schema.sdl` breaks when using `absinthe_relay` connections

### ISSUE THREAD

**Issue by halostatue** [absinthe-graphql/absinthe#1328]
### Environment

* Elixir version (elixir -v): 1.15.8
* Absinthe version (mix deps | grep absinthe): 1.7.7
* Client Framework and version (Relay, Apollo, etc): n/a

### Expected behavior

I’m still trying to figure out how to create a minimal reproduction as well as figure out a potential fix, but I wanted to raise this ASAP in case someone else has seen it or has an idea on how to better test it and/or resolve it.

Given a Relay schema (we use modern) that looks *something* like this (super simplified):

```elixir
node object(:foo) do
  field :bar, :string
end

connection node_type: :foo
```

With Absinthe 1.7.6, `mix absinthe.schema.sdl` generates the appropriate `schema.graphql`. With Absinthe 1.7.7, `mix absinthe.schema.sdl` fails to generate the schema. Modifying the generator to inspect the output includes an `Absinthe.Phase.Error`:

```
   %Absinthe.Phase.Error{
     message: "In field Edges, :foo_edge is not defined in your schema.\n\nTypes must exist if referenced.\n",
     phase: Absinthe.Phase.Schema.Validation.TypeReferencesExist,
     …
```

If, however, I modify the schema to be:

```elixir
node object(:foo) do
  field :bar, :string
end

connection node_type: :foo do
  edge do
    import_fields :foo
  end
end
```

The `foo_edge` is defined again and the SDL is generated again.

**Comment by halostatue** [comment]
As noted, I have a workaround, but it feels weird that I have to explicitly declare the edges for the case where I am generating the SDL. This is not required or showing any errors during normal compile (but I’m not sure whether the references exists pass is done during compile).

**Comment by benwilson512** [comment]
Hey have you tried using main? There was a bug fix that may be related to this.

**Comment by halostatue** [comment]
I had not tried main. #1326 does fix this issue. Probably worth putting in the release notes when released, as the "workarounds" didn't actually work, they just *seemed* to work by suppressing the errors and not actually resolving anything.

**Comment by halostatue** [comment]
Looking forward to 1.7.8 when released.

**Comment by benwilson512** [comment]
v1.7.8 has been pushed with this fix.
