### ISSUE TITLE
Variables with custom scalars parsing to `nil` are filtered from args

### ISSUE THREAD

**Issue by jesenko** [absinthe-graphql/absinthe#143]
**Backround**

To enable setting of `nil` values on fields in mutations, we introduced custom scalar `null_or_integer`, which serializes to "null" or integer value (e.g. "1").

**Issue**

Variables that resolve to `{:ok, nil}` in scalar `parse` function are filtered from map of parameters passed to a resolver. 

I have added test cases for usage of scalar in `args` and `input_object` in #142.

**Comment by bruce** [comment]
@jesenko The reason why nils are filtered is because they're not actually supported by the GraphQL spec as an input value type -- and because by stripping `nil` we support better resolver matching patterns (it is much easier to match cases where a value _has_ been given). Until something like https://github.com/facebook/graphql/pull/83 gets resolved more clearly, I'd recommend resolving with, eg, a different  atom as a sentinel value instead.

**Comment by jesenko** [comment]
@bruce I am currently resolving to `{:ok, :blank}` and then handling `:blank` as `nil` in resolver to work around this issue; I tried implementing `null_or_integer` scalar type work around facebook/graphql#83, so that passed variable always contains non-null string `"null"` (could be also e.g. `"blank"`) and not `null`, but obtaining `nil` in resolver nonetheless.

Note that currently behaviour in absinthe is different whether `"null"` is passed as variable or directly in query. If passed in query, `"null"` is returned in resolver argument map as `nil`. If passed as variable, it is stripped from argument map. Behaviour should probably the same in both cases?

**Comment by bruce** [comment]
@jesenko I agree on consistency; I believe this is something we handle much better in the "normalization phase" that's part of v1.2.

**Comment by bruce** [comment]
Closing this issue as it's addressed in the v1.2 release. Let's reopen if we continue to see issues with consistency.

**Comment by jesenko** [comment]
@bruce Great, I will verify once v1.2 gets released.

**Comment by MrAlexLau** [comment]
Do either of you know if this was ever addressed? I'm noticing this behavior in 1.4.11 and wasn't able to find any mention of this in the [1.2 release notes](https://github.com/absinthe-graphql/absinthe/releases?after=v1.2.6).

**Comment by benwilson512** [comment]
@MrAlexLau can you provide an example? Absinthe has had `null` handling for a long time now.

**Comment by tmattio** [comment]
Is there a way to have this behavior with the current version of absinthe (i.e. not forwarding the field to the resolver if it is `nil`)?

**Comment by MrAlexLau** [comment]
@benwilson512 - sorry, I realized my issue was elsewhere - you can disregard my comment from earlier.
