### ISSUE TITLE
Error running mix absinthe.graphql or absinthe.json for schema with import_type

### ISSUE THREAD

**Issue by hisapy** [absinthe-graphql/absinthe#154]
Version: **absinthe 1.1.10**

Given a schema with **import_types**, running  `mix absinthe.schema.graphql --schema Webapp.GraphQL.PublicSchema` gives the following error

> *\* (ArgumentError) argument error
>     :erlang.binary_to_existing_atom("Elixir.Webapp.GraphQL.Auth", :utf8)
>     (elixir) src/elixir_aliases.erl:108: :elixir_aliases.safe_concat/1
>     lib/absinthe/type.ex:36: Absinthe.Type.built_in?/1
>     (elixir) lib/enum.ex:1674: anonymous fn/3 in Enum.reject/2
>     (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
>     (elixir) lib/enum.ex:1674: Enum.reject/2
>     lib/absinthe/language/idl.ex:9: Absinthe.Language.IDL.to_idl_ast/1
>     lib/mix/tasks/absinthe.schema.graphql.ex:59: Mix.Tasks.Absinthe.Schema.Graphql.run/1
>     (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
>     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
>     (elixir) lib/code.ex:363: Code.require_file/2

The schema is the as follows:

``` elixir
defmodule Webapp.GraphQL.PublicSchema do
  use Absinthe.Schema
  use Absinthe.Relay.Schema

  import_types Webapp.GraphQL.Auth.Mutations
  mutation do
    import_fields :auth_mutations
  end # END mutation
end

defmodule Webapp.GraphQL.Auth.Mutations do
  use Absinthe.Schema.Notation
  use Absinthe.Relay.Schema.Notation
  import Comeonin.Bcrypt, only: [checkpw: 2, dummy_checkpw: 0]

  object :auth_mutations do
    payload field :login do
      input do
        field :email, non_null(:string)
        field :password, non_null(:string)
      end
      output do
        field :access_token, :string
      end
      resolve fn
        %{email: email, password: password}, _ ->
          case authenticate_user(email, password) do
            {:ok, user} ->
              {:ok, jwt, _full_claims} = Guardian.encode_and_sign(user)
              {:ok, %{access_token: jwt}}
            {:error, _reason} -> # TODO: handle error correctly
              {:error, %{access_token: nil}}
          end
      end
    end
  end

  # TODO: move this to User model
  defp authenticate_user(email, password) do
    user = Webapp.Repo.get_by(Webapp.User, email: email)
    cond do
      user && checkpw(password, user.encrypted_password) ->
        {:ok, user}
      user ->
        {:error, :unauthorized}
      true ->
        dummy_checkpw()
        {:error, :not_found}
    end
  end #END authenticate_user
end
```

This error does not occur when running the same command on a schema without **import_types**ing

``` elixir
defmodule Webapp.GraphQL.PublicSchema do
  use Absinthe.Schema
  use Absinthe.Relay.Schema
  import Comeonin.Bcrypt, only: [checkpw: 2, dummy_checkpw: 0]

  # import_types Webapp.GraphQL.Auth.Mutations
  mutation do
    # import_fields :auth_mutations
    payload field :login do
      input do
        field :email, non_null(:string)
        field :password, non_null(:string)
      end
      output do
        field :access_token, :string
      end
      resolve fn
        %{email: email, password: password}, _ ->
          case authenticate_user(email, password) do
            {:ok, user} ->
              {:ok, jwt, _full_claims} = Guardian.encode_and_sign(user)
              {:ok, %{access_token: jwt}}
            {:error, _reason} -> # TODO: handle error correctly
              {:error, %{access_token: nil}}
          end
      end
    end
  end # END mutation

  # TODO: move this to User model (or resolver?)
  defp authenticate_user(email, password) do
    user = Webapp.Repo.get_by(Webapp.User, email: email)
    cond do
      user && checkpw(password, user.encrypted_password) ->
        {:ok, user}
      user ->
        {:error, :unauthorized}
      true ->
        dummy_checkpw()
        {:error, :not_found}
    end
  end
end
```

The generated output is:

``` graphql
schema {
  mutation: RootMutationType
}
input LoginInput {
  clientMutationId: String!
  email: String!
  password: String!
}
type LoginPayload {
  accessToken: String
  clientMutationId: String!
}
type RootMutationType {
  login(input: LoginInput!): LoginPayload
}
type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

```

PS.: why **type PageInfo** is in the output?

When running `mix absinthe.schema.json ...` **with import_types** version, the output does not contain email and password fields. **Without import_types**, the output DOES contain email and password fields. Notice that in both cases the schema.json output is way larger than the **graphql IDL** version. 

The IDL version is only 378 Bytes and the .json version is 12 KB. Is it necessary to output all possible types, directives, etc in the .json version for a tiny schema like this?

**Comment by bruce** [comment]
To cover some stuff we discussed in the Slack channel:

- PageInfo is part of the Relay schema -- you get it automatically if you're using connections.
- The JSON task uses the full introspection query from graphql-js; you can get a shallower view of your schema by sending your own introspection query to your server. (We would also accept a PR that added custom query support to the mix task.)
- @benwilson512 will take a look at the `import_types` disparity

**Comment by bruce** [comment]
Slating any follow-up here as part of the v1.3 milestone, as it involves concerns with schema definition imports.

**Comment by hisapy** [comment]
Just for the record, currently, I'm NOT having problems with the `mix absinthe.schema.json ... `. I'm using its schema.json output to feed my `babelRelayPlugin` and so far it's working fine **with import_types**

**Comment by benwilson512** [comment]
Are you using `import_fields` as well?

**Comment by hisapy** [comment]
Yes @benwilson512 ... I'm using `import_fields` as well.

**Comment by benwilson512** [comment]
Closing this, haven't been able to reproduce.
