### ISSUE TITLE
How to: write a macro that will add fields to object

### ISSUE THREAD

**Issue by sjchmiela** [absinthe-graphql/absinthe#155]
I would like to write a macro that would add fields to object.
```Elixir
defmacro add_field(name) do
  quote do: field unquote(name), :boolean, do: {:ok, true}
end

object :user do
  field :id, :id
  add_dynamic_field(:dynamic)
end
```
This way it doesn't work, there is no `:dynamic` field in the generated GraphQL schema. 😞 

With such macro one could use it to automatically generate fields eg. `can_create_client`, `can_create_project`, `can_destroy_client`, `can_destroy_project` not by writing these by hand, but by multiplication of `["create", "destroy"]` and `["client", "project"]`.

How to do it? 😃

**Comment by bruce** [comment]
At the current time the best way to do this is to use `import_fields` -- we hope to make schema extensibility easier in a future revision (it's fairly complicated because it's part of the module compilation process).

```elixir
object :foo do
  field :a, :string
end

object :bar do
  field :b, :integer
end

object :baz do
  import_fields :foo
  import_fields :bar
  field :c, :id
end

# baz now has 'a', 'b', 'c' fields
```
