### ISSUE TITLE
Escaped characters in input literals not correctly interpreted by lexer

### ISSUE THREAD

**Issue by bcinman** [absinthe-graphql/absinthe#165]
Writing a custom scalar for arbitrary JSON. Escaping the quotes in the JSON string results in the scalar parser receiving data with extraneous slashes. 

It appears absinthe is escaping the \'s even though they're being used to escape the quotes.

GraphQL: 

``` graphql
mutation {
    item(data: "{\"foo\": \"bar\"}") {
        id
        data
    }
}
```

The scalar parse function receives `"{\\\"foo\\\":  \\\"bar\\\"}`.

**Comment by bruce** [comment]
I put in a couple test cases to capture this issue in a branch, `v1.2-bug-165`. This is a general way in which raw escaped characters are treated in literals after they're extracted by the lexer, so we need to find a generic approach, preferably in Erlang so it can be integrated directly in the lexer/parser code.

**Comment by bruce** [comment]
Direct link to the branch: https://github.com/absinthe-graphql/absinthe/tree/v1.2-bug-165 (note this is branched from the v1.2 code, as it's imminent, vs current master).
