### ISSUE TITLE
Fragments on Interfaces not resolving (Union result)

### ISSUE THREAD

**Issue by avitex** [absinthe-graphql/absinthe#170]
Hi folks. Firstly would like to say, I've been enjoying this library quite a lot and finding the abstractions very refreshing. Thank you for your time and effort, it definitely shows 😃

**entity** returns a union of `Organisation | User`
**Entity** - An interface with the fields `avatar` and `title`
**Organisation, User** - Inherits the `Entity` interface

![They say a picture is worth a thousand words](https://i.gyazo.com/8ee5f6440387efc472218f0cc30f6a5b.png)

I'm not getting any errors, and I haven't read the full spec so do correct me if I am wrong, but I assume that the *common* fields `title` and `avatar` should be present in the response.

Note: I am using `{:absinthe_plug, "~> 1.1"}` and this does work without fragments.

**Comment by benwilson512** [comment]
Hey there, sorry we missed this. Have you had a chance to try this on the latest v1.2 alpha release?

**Comment by avitex** [comment]
I'll give it a try tonight and report back.

**Comment by benwilson512** [comment]
This appears to be fixed on v1.2
