### ISSUE TITLE
Add schema rule to ensure schema always has a query type

### ISSUE THREAD

**Issue by bruce** [absinthe-graphql/absinthe#172]
According to https://facebook.github.io/graphql/#sec-Initial-types, a query type must be provided. We should add a schema rule (under `lib/absinthe/schema/rule`) to ensure this rule is enforced.

This change will apply cleanly to master (v1.1) and v1.2, as no changes to schema compilation were made in v1.2.

**Comment by bruce** [comment]
I'm going to toss this into the v1.3 bucket, built into the planned phase-based schema validation (rules) system.

**Comment by benwilson512** [comment]
Fixed in master.
