### ISSUE TITLE
Fragments shallowly merging causing dropped fields

### ISSUE THREAD

**Issue by kenips** [absinthe-graphql/absinthe#174]
I'm experiencing the same issue as https://github.com/rmosolgo/graphql-ruby/issues/29. Basically fragments with nested keys are not deep merged properly causing resulting set to be smaller than the union of requested nested keys.

**Comment by benwilson512** [comment]
Which version are you on btw? This has been substantially reworked in v1.2, need to know if you're still experiencing it there.

**Comment by kenips** [comment]
Was on 1.1 but now seeing this on 1.2.0-alpha0 as well.

**Comment by benwilson512** [comment]
PR created with failing example test case: https://github.com/absinthe-graphql/absinthe/pull/175

**Comment by benwilson512** [comment]
Fixed in v1.2 branch, will be on the next release.
