### ISSUE TITLE
Unable to return partial field errors

### ISSUE THREAD

**Issue by shantiii** [absinthe-graphql/absinthe#177]
According to the [GraphQL Spec on Error Handling](https://facebook.github.io/graphql/#sec-Error-handling), "If an error occurs when resolving a field, it should be treated as though the field returned `null`, and an error must be added to the `"errors"` list in the response."

In the event that the field resolution problem occurs in a non-top-level field, there's no way to return both null and an error.

Schema:

``` graphql
type RootQueryType {
  items(ids: [ID]!): [Item]
}
type Item {
  id: ID!
  name: String
}
```

Query

``` graphql
query {
  items(ids: [1,2,3]) {
    id, name
   }
}
```

If there's a problem fetching the item with id 3,

``` elixir
{:ok, %{id: 1, name: "foo"}, %{id: 2, name: bar}, nil}}
```

and 

``` elixir
{:ok, %{id: 1, name: "foo"}, %{id: 2, name: bar}, %{id: 3, name: nil}}
```

are both valid responses, but there's no way to also append to the `errors` list from within the resolver, since the only way to do that is to have the entire resolver return

``` elixir
{:error, "Item id '3' not found"}
```

**Comment by aweiker** [comment]
I was thinking about this problem the other day too.

A workaround is to have a resolver for every field and then that individual resolver would have to return an  `{:error, reason}` tuple. This requires a lot more work for the schema developer, but is possible with the current implementation.

I haven't taken the time to create an example of this, let me know if that would be helpful.

**Comment by benwilson512** [comment]
The general pattern I've seen in the broader graphql community tends to follow something more like this https://medium.com/@tarkus/validation-and-user-errors-in-graphql-mutations-39ca79cd00bf#.9u9kawo7r

IE, don't use graphql errors for this purpose.

@aweiker unfortunately that wouldn't work for this because this resolver returns a list.

**Comment by bruce** [comment]
I'm in agreement with @benwilson512 on this. Seems like this is currently best handled at a domain modeling level, returning a union type. It seems like a "partial result" should be a thing that's modeled as such; given the errors are more user-facing. I'm going to close this issue.

If people feel strongly about this and can provide extant examples from other GraphQL implementations, we can discuss it in further depth in a new issue.
