### ISSUE TITLE
Should be able to define custom schema rules

### ISSUE THREAD

**Issue by aweiker** [absinthe-graphql/absinthe#185]
It would be handy if we could create rules that behave link linters on type/field names.

For example after chatting with Lee Byron this week FaceBook has several rules, some of which are fields can't end with a suffix of Id or Type. It would be nice if we could use rules to do this as they appear to be a perfect fit.

**Comment by bruce** [comment]
Yeah, I totally agree. This is probably a good fit for v1.3, which I'm going to start working on as soon as we release 1.2 -- it's going to target a reworking on the schema building (trying to make it as pluggable as phases, and supporting definition via the IDL flowing through the same pipeline).

**Comment by tlvenn** [comment]
Shopify also for example enforces some conventions:
<img width="698" alt="shopify_conventions" src="https://cloud.githubusercontent.com/assets/3340262/19875493/1945cff0-a008-11e6-8c81-c2fdedd12785.png">

**Comment by benwilson512** [comment]
Closing this. It's a bit abstract, and will likely be obviated by the 1.5 approach.
