### ISSUE TITLE
Docs - Custom Scalars

### ISSUE THREAD

**Issue by theduke** [absinthe-graphql/absinthe#195]
The `parse` and `format` functions in Timex 3 are not in the DateFormat module but directly on Timex.

> scalar :time, description: "ISOz time" do
>   parse &Timex.DateFormat.parse(&1.value, "{ISOz}")
>   serialize &Timex.DateFormat.format!(&1, "{ISOz}")
> end

Should be changed to

> scalar :time, description: "ISOz time" do
>   parse &Timex.parse(&1.value, "{ISOz}")
>   serialize &Timex.format!(&1, "{ISOz}")
> end

**Comment by benwilson512** [comment]
Can you do a PR for this?

**Comment by aweiker** [comment]
Would it make sense to use DateTime module introduced in Elixir 1.3 instead of Timex?

**Comment by benwilson512** [comment]
Quite possibly, does it serialize / parse ISOz? If so we should definitely use it.

**Comment by aweiker** [comment]
It does for parsing Dates. Just remembered that it can't do accurate times without a time zone database. So if you want an example using a time, then keep Timex.

**Comment by benwilson512** [comment]
Yeah I definitely want datetimes.

**Comment by aweiker** [comment]
I remember having an issue when returning an error in the parse function. If the documentation is getting updated can we make sure to correctly specify that it's just `:error` and not `{:error, reason}`. Unless 1.2 fixed that to allow both.

**Comment by bruce** [comment]
What's the path forward on this? @theduke, are you planning on doing a PR keeping the feedback here in mind, or @aweiker, or one of us?

I definitely want to encourage contribution when I can. 😄

**Comment by Logisig** [comment]
I think this can be closed now

**Comment by liveresume** [comment]
Just caught another update todo here:

http://absinthe-graphql.org/guides/custom-scalars/
