### ISSUE TITLE
Docs: "Writing Schema" not describing resolver arguments (especially for nested fields)

### ISSUE THREAD

**Issue by denisw** [absinthe-graphql/absinthe#200]
When I read the otherwise nice "Writing Schemas" guide, I immediately asked myself two questions:

* What exactly are the arguments of the resolver function, especially the ignored second one?
* How do I get the parent value when writing a resolver for a nested field?

Unfortunately, none of these two questions are answered in that guide. The first one is only answered at one hard-to-find point in the API docs (and only describes the two-argument version), and the second one is only indirectly addressed in the Ecto Best Practices guide, where a three-arg resolver function is used without any explanation.

**Comment by bruce** [comment]
Hi @denisw, thanks for the feedback! Can you recreate this issue in https://github.com/absinthe-graphql/website/issues please; that project houses the content for the guides, and we'd like to keep issues here focused on Absinthe's core. Also, if you have specific content that you think would be helpful, we'd be more than happy to collaborate on a PR editing the specific guide as well. Thanks!
