### ISSUE TITLE
Validation error when using list of lists as argument

### ISSUE THREAD

**Issue by jesenko** [absinthe-graphql/absinthe#205]
When using nested list of lists as argument, e.g.

    field :string_list_of_list_arg_field, :string do
      arg :string_list_of_list_arg, list_of(list_of(:string))
    end

and passing variable as 

    stringListOfListArgField(stringListOfListArg: [["one"], ["two", "three"]])

fails with error

     Argument "stringListOfListArg" has invalid value [["one"], ["two", "three"]].
     In element #1: Expected type "String", found ["one"].
     In element #2: Expected type "String", found ["two", "three"].

Related PR with failing test: #204

**Comment by benwilson512** [comment]
This is definitely an unfortunate regression as this definitely used to work. Looking into it.

**Comment by benwilson512** [comment]
Fixed in master.

**Comment by jesenko** [comment]
:astonished: That was amazingly fast... @benwilson512 Thank you so much for the quick fix and for all the work you have put into this great lib!

**Comment by benwilson512** [comment]
Of course! This was a pretty serious regression, thanks for bringing it to our attention! :)

**Comment by bruce** [comment]
@benwilson512 I'm 👍 on this being a trigger for releasing v1.2.1.
