### ISSUE TITLE
Arguments can be marked as deprecated.

### ISSUE THREAD

**Issue by aweiker** [absinthe-graphql/absinthe#207]
Based on what I could understand from the specification, the only thing that can be marked as being deprecated is a [field](http://facebook.github.io/graphql/#sec-Object-Field-deprecation). However, using the schema notation in absinthe I can [mark an argument as being deprecated](https://hexdocs.pm/absinthe/Absinthe.Schema.Notation.html#deprecate/1).

**Comment by bruce** [comment]
Yes. This was a side-effect of some early thinking, especially when the spec wasn't as clear as it is today. Also, technically, the specification doesn't support [deprecation of InputObject fields](https://github.com/facebook/graphql/issues/197) either -- which I think we do support _defining_.

Notably neither of these are introspectable, as `__inputvalue` doesn't have deprecation information.

While I'm a bit reticent to remove things, even though [the spec may add those deprecations in the future](https://github.com/facebook/graphql/issues/197), being that the arg/input value deprecation information is effectively useless at the moment, I'd be fine with a PR ripping it out.

Thoughts, @benwilson512 ?

**Comment by aweiker** [comment]
So I guess there are 3 options we can do.
1) Nothing and hope that a RFC is introduced for this change.
2) Propose an RFC to add this to the spec, and then implement the introspection pieces.
3) Remove the support for being able to deprecate things that shouldn't be allowed.

**Comment by bruce** [comment]
I'm really torn on the right course of action here. I'm leaning towards #3, but only because it's the least distracting and most "strictly correct" for the current time.

**Comment by bruce** [comment]
@aweiker and I decided to hold this at least as the v1.3 changes are being built-out, taking option 1 for the moment -- and, if we have time, doing option 2.

If we _don't_ get an RFC in, we should probably take option 3 by the time 1.3.0 is released.

**Comment by bruce** [comment]
Update on this: while schema definition changes were originally slated for v1.3, the current target is now 1.4.

The GraphQL RFC is still open.

**Comment by benwilson512** [comment]
Per https://github.com/graphql/graphql-spec/pull/525 this will be in the next spec version, so I think we can close this.
