### ISSUE TITLE
Where should I put `forward "/graphiql" call ?

### ISSUE THREAD

**Issue by collegeimprovements** [absinthe-graphql/absinthe#215]
Hi Ben, Bruce,
For some reason, I can't make `graphiql` work with my application. Here is my router file. 

```elixir
defmodule MyApp.Router do
  use MyApp.Web, :router

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth_api do
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated, handler: MyApp.SessionController
    plug MyApp.Web.Context
  end

  pipeline :ensure_staff do
    plug MyApp.Web.EnsureStaff
  end


  # NEW
  scope "/forum/v1", MyApp do
    pipe_through [:api, :auth_api]
    post "/token-auth", SessionController, :create, as: :login

    # forward "/api", Absinthe.Plug,
    # schema: MyApp.Schema
  end

  scope "/forum/v1" do
    pipe_through [:api, :auth_api, :ensure_auth]
    get "/graphql", Absinthe.Plug, schema: MyApp.Schema
    post "/graphql", Absinthe.Plug, schema: MyApp.Schema


  end

  scope "/forum/v1" do
    pipe_through [:api, :auth_api, :ensure_auth, :ensure_staff]
    get "/staff", Absinthe.Plug, schema: MyApp.SchemaStaff
    post "/staff", Absinthe.Plug, schema: MyApp.SchemaStaff
  end

  forward "/graphiql", Absinthe.Plug.GraphiQL,
  schema: MyApp.Schema


end
```

It raises `function Absinthe.parse/1 is undefined or private` exception. 
I tried to move the ` forward "/graphiql", Absinthe.Plug.GraphiQL,
                                 schema: MyApp.Schema` in the scope. But that also didn't work.

For older versions, we just get to see the schema but can't perform any query(maybe because we don't set token there!). 

Please help. 
Thank you.

**Comment by benwilson512** [comment]
Hey there, sorry you're having issues. What version of Absinthe and Absinthe.Plug are you running?

**Comment by collegeimprovements** [comment]
```elixir
   {:absinthe, "~> 1.2.0"},
   {:absinthe_plug, "~> 1.1"},
   {:absinthe_ecto, git: "https://github.com/absinthe-graphql/absinthe_ecto.git"}
```

All of them are latest now. 
The problem is : even after updating them to latest version, I still see the old gui (i.e. one without top section with http-header adding functionality). 
Maybe I'm doing something wrong, but can't figure out what! 
When I create new app(without any auth) and try to run it all works perfectly.

**Comment by benwilson512** [comment]
Per our discussion on slack, you need Absinthe.Plug at 1.2 as well.

**Comment by collegeimprovements** [comment]
Hi Ben,
I've upgraded to `Absinthe.Plug at 1.2` and now I can see the latest GUI. :+1: 

Also when I put the `forward "graphiql"` outside then I can see the GUI and also can see the options with `ctrl+space` but **nothing comes as the output** when I run it. I even set the Bearer token but it doesn't work.

Similarly when I put it inside some scope then it shows not authenticated! Which is understandable. 

Is there any way to make it work anyhow?
