### ISSUE TITLE
Add support for import_fields in input_object

### ISSUE THREAD

**Issue by ryanswapp** [absinthe-graphql/absinthe#218]
I'm building out a GraphQL API for a MongoDB datasource and came across a use case for needing import_fields to work in input_object. In Mongo you pass a selector to a find query to determine what results you get back. That selector is an object that more or less represents a collection document. Given that I will have already defined, for instance, a :user object it would be nice to do something like:
```
input_object :user_selector do
  import_fields :user 
end
```

That would allow me to pass a selector as an argument without copy pasting my entire :user object into the input_object. I don't believe this is possible after speaking with @bruce so filing an issue.

**Comment by benwilson512** [comment]
Hey there. I will make sure that input_objects work with import fields. However do note that when I do that `import_fields` inside an input_object will ONLY be able to import fields from another input_object, not from objects.

Fields in objects are permitted to form cycles, and are permitted to return types like unions and interfaces. These are not permitted with input objects.

**Comment by ryanswapp** [comment]
Ah that makes sense. I guess I should have assumed there would be some limitations to what was possible for input objects. Will it be possible to import fields from an input_object into an object? If so, I could prevent duplication by putting everything in an input_object and import all the fields into an object which can then be used elsewhere.

**Comment by benwilson512** [comment]
Honestly I would not. I realize it feels like duplication at first but after you've done it once you have this nice separation of inputs and outputs and as time goes on, those frequently diverge. Moreover it pretty quickly becomes the case that you want to surface say a "inserted_at" from your user object, but obviously nobody should be allowed to edit that. Sure you could enforce that with changesets, but why would your API list a field as a mutable input when it isnt?

**Comment by bruce** [comment]
This will be resolved in v1.3, see #219. A future PR will enforce the cycles constraint.

**Comment by ryanswapp** [comment]
@bruce @benwilson512 You guys are awesome! Thanks for this.

**Comment by benwilson512** [comment]
This also works in master now, and will be in the near term 1.2.2 release.
