### ISSUE TITLE
Is it possible to import an external schema?

### ISSUE THREAD

**Issue by liveresume** [absinthe-graphql/absinthe#222]
I was wondering if it's possible to import a preexisting GQL Schema for Absinthe to use in place of defining it again using elixir.

Does it even make sense to use Absinthe if this is the requirement?

**Comment by bruce** [comment]
Importing a schema IDL (which is the GraphQL-based string representation) is planned for v1.3, whose development is underway; expect to see an alpha in January.

Keep in mind logic will still have to be implemented in Elixir to resolve fields. In the meantime it may make sense to give the Elixir DSL a shot.

**Comment by liveresume** [comment]
Been good so far.  Waiting patiently.

**Comment by rawkode** [comment]
@bruce This would be awesome. If you need some help, please point me to some issues and I can pick them up :+1:

**Comment by benwilson512** [comment]
Update: @bruce has made significant progress on a blueprint based method of constructing schemas. This method would be able to import IDLs.

Unfortunately 1.3 is going to ship with out it, as there is a fair bit of work to be done there still and 1.3 includes features like middleware that have been a long time coming and are more overall more pressing.

**Comment by rawkode** [comment]
Hi @bruce, are you still working on this? My offer to help is still valid, I'd be keen to see this integrated into Absinthe :+1:

**Comment by bruce** [comment]
This just got pushed by subscriptions, which ended up being higher priority. This is part of a larger rework of the entire schema definition mechanism (supporting use of its own pluggable phases), so I think it's a bit bigger than we could expect anyone else to reasonably bite off. This rework _is_ my main priority after this beta goes to stable, so hopefully you'll see some progress soon.

**Comment by rawkode** [comment]
Hey @bruce, is this still on the backlog? :smile:

**Comment by benwilson512** [comment]
This is indeed at the center of the set of features planned for Absinthe 1.5, you can track progress here: https://github.com/absinthe-graphql/absinthe/pull/503
