### ISSUE TITLE
Modifying default_resolve breaks GraphiQL introspection

### ISSUE THREAD

**Issue by jswinarton** [absinthe-graphql/absinthe#227]
I've created an Absinthe schema with a `default_resolve` macro that handles resolution sources with string keys (instead of the default, which is atoms). It looks like this ([borrowed from the docs](https://hexdocs.pm/absinthe/Absinthe.Schema.html#module-default-resolver)):

```elixir
default_resolve fn
  _, %{source: source, definition: %{name: name}} when is_map(source) ->
    {:ok, Map.get(source, name)}
  _, _ ->
    {:ok, nil}
end
```

I am using the GraphiQL implementation provided by `Absinthe.Plug.GraphiQL`. When I first load the GraphiQL endpoint, it sends a query to the GraphQL server to introspect the schema. I then get this error in the GraphiQL interface:

```
Error: Type must be named.
    at n (http://cdn.jsdelivr.net/graphql-toolbox/1.0.1/graphiql.min.js:28:751)
    at new e (http://cdn.jsdelivr.net/graphql-toolbox/1.0.1/graphiql.min.js:28:13998)
    at _ (http://cdn.jsdelivr.net/graphql-toolbox/1.0.1/graphiql.min.js:30:28829)
    at c (http://cdn.jsdelivr.net/graphql-toolbox/1.0.1/graphiql.min.js:30:28456)
    at n (http://cdn.jsdelivr.net/graphql-toolbox/1.0.1/graphiql.min.js:30:27832)
    at http://cdn.jsdelivr.net/graphql-toolbox/1.0.1/graphiql.min.js:30:31052
    at Array.map (native)
    at i (http://cdn.jsdelivr.net/graphql-toolbox/1.0.1/graphiql.min.js:30:31029)
    at http://cdn.jsdelivr.net/graphql-toolbox/1.0.1/graphiql.min.js:65:12259
```

I can still send queries and receive responses through the GraphiQL interface, but the introspection facilities are broken. Query autocompletion doesn't work, and the "docs" in the sidebar don't work, either. __Removing the `default_resolve` macro from my schema fixes the issue.__

I am unsure if this is a bug—I borrowed this example directly from the docs and I can't tell if I'm overriding the `default_resolve` in the wrong way.

**Comment by jparise** [comment]
I ran into this a while back, too. The short answer is that you may still need to handle atom-based lookups for those resolvers that require them. For my case, I handle both struct- and map-based lookups like this:

```elixir
  @spec resolve(%{atom => any}, Absinthe.Resolution.t) :: Absinthe.Type.Field.resolver_output
  def resolve(_args, %{source: %{__struct__: _} = source, definition: %{name: name}}) do
    {:ok, Map.get(source, String.to_existing_atom(name))}
  end
  def resolve(_args, %{source: source, definition: %{schema_node: schema}}) do
    {:ok, Map.get(source, schema.__reference__.identifier)}
  end
```

And then use this as the default resolver:

```elixir
default_resolve &Myapp.resolve/2
```

**Comment by bruce** [comment]
I believe @jparise is correct here.  In v1.3 (underway) we're going to try to readdress the default resolver / system resolver issues (among other schema definition improvements). I'm going to close this issue for now, but if the workaround posted here doesn't help, please reopen.

Also (to either of you), a doc PR helping others that may encounter this issue (https://github.com/absinthe-graphql/website) would be cool, if you have time.
