### ISSUE TITLE
Can I import queries/mutations/subscriptions from other files?

### ISSUE THREAD

**Issue by ndarilek** [absinthe-graphql/absinthe#240]
Apologies if this is documented--your docs are excellent but I haven't found this. I want to split my API up along functional bounds. So all types/queries/mutations related to user management are in web/api/users.ex, while web/api.ex is the schema that brings it all together.

I can place types in web/api/users.ex and use import_types, but I can't figure out if I can do the same with queries, mutations and subscriptions. import_fields tells me that I can't use it at the module level. I thought about using import_fields in query/mutation blocks at the top level, but I imagine that'd pull in *all* fields into the specific type (I.e. mutations into queries) and that's not what I want.

Is this possible?

**Comment by benwilson512** [comment]
```
defmodule Foo do
  use Absinthe.Schema.Notation

  object :user_queries do
    field :foo, :string
    # etc
  end
end

defmodule MyApp.Schema do
  import_types Foo
  
  query do
    import_fields :user_queries
  end
end
```
