### ISSUE TITLE
Document best practices for error-handling in resolvers

### ISSUE THREAD

**Issue by ndarilek** [absinthe-graphql/absinthe#241]
Again, apologies if this is documented and I'm missing it. What I want to do is return a series of validation errors from Ecto through the GraphQL API. So for instance, if a model fails a uniqueness constraint, I'd like it if I got back an object split up by field, with messages associated with each. Basically, I want to pipe a changeset back from my resolver and have that returned in a form that my client can consume for nicer error-reporting in forms.

It looks like resolvers expect {:error, str} in the error case. While that is idiomatic Elixir, I don't know how it meshes with Ecto changeset errors. I've read about traversing the list of changeset errors and creating a human-readable reason, but that would result in a single error message when what I'd like is something broken down along model field lines.

Is there any way to achieve this?

**Comment by benwilson512** [comment]
This sounds like a better issue for the absinthe-website to be honest. It has an "ecto best practices" page and this would be a good subject to cover there. Handling ecto errors is not a first class concern of Absinthe.

**Comment by ndarilek** [comment]
Got it. Should I file it there then? Apologies for spamming the issue 
tracker.

**Comment by benwilson512** [comment]
yes please!
