### ISSUE TITLE
Typespec warning for call to Elixir.Absinthe.Resolution.Helpers.batch/3

### ISSUE THREAD

**Issue by nicholasjhenry** [absinthe-graphql/absinthe#245]
I’m trying to resolve a Dialyzer warning with a call to `Elixir.Absinthe.Resolution.Helpers.batch/3` but I cannot determine the cause of the warning. The warning is:

```
The call 'Elixir.Absinthe.Resolution.Helpers':batch({'Elixir.AbsintheTypeSpec', 'batch_function'},1,fun((_) -> {'ok',_})) will ne
ver return since the success typing is ({_,'atom'} | {_,'atom',_},any(),fun((_) -> {'error',binary() | [{_,_}] | map()} | {'ok',_} | {'plugin',atom(),_}))
 -> {'plugin','Elixir.Absinthe.Resolution.Plugin.Batch',{_,_,_,_}} and the contract is ('Elixir.Absinthe.Resolution.Plugin.Batch':batch_fun(),term(),'Elix
ir.Absinthe.Resolution.Plugin.Batch':post_batch_fun()) -> {'plugin','Elixir.Absinthe.Resolution.Plugin.Batch',term()}
```

I've created a dedicate application to demonstrate this issue at: https://github.com/nicholasjhenry/absinthe-type-spec

As you can see, I've created a simple version to determine the issue in my production code:

```elixir
defmodule AbsintheTypeSpec do
  def call do
    Elixir.Absinthe.Resolution.Helpers.batch({__MODULE__, :batch_function}, 1, fn batch_results ->
      {:ok, batch_results}
    end)
  end

  defp batch_function do
    :testing
  end
end
```

I've created a table to help compare the arguments and return types with the success typing and
type signature. Is there anything obvious I am missing here? Thank you.

https://db.tt/2qxfHtu5Bc

![screenshot 2017-01-03 12 02 57](https://cloud.githubusercontent.com/assets/40253/21615944/9d9193c6-d1ad-11e6-890f-2a0a7208b0bf.png)

**Comment by benwilson512** [comment]
Investigating. Do note that the batch function must be a public function.
