### ISSUE TITLE
Transforming request context

### ISSUE THREAD

**Issue by jellybob** [absinthe-graphql/absinthe#247]
I'm writing an application in which the request context can change over multiple mutations - specifically users have an account. If the user has an account associated at the start of the request then it gets loaded and included in the context as normal, but I'd like to insert it into the context if they ask to create an account so that its available on subsequent calls within the document.

As an example, the following document will fail, as the user doesn't have an account in the context due to it not existing at that point. However on the second attempt (when an account has been created), it will succeed.

```
mutation CreateAccountAndInvitation {
  // Idempotent request - if the user already has an account that account will be returned.
  createAccount {
    id
  }
  
  createAccountInvitation(key: "9762b502-d003-4b79-b42a-80c2d0bc0027") {
    acceptanceCode
  }
}
```

Is this something that's supported, or should I just accept that I can't create an account and make use of it within the same document.

**Comment by bruce** [comment]
This isn't supported yet, but mutations modifying the context is something we're planning supporting.

**Comment by benwilson512** [comment]
Handled by middleware, will be out with 1.3-beta0 here very shortly.
