### ISSUE TITLE
Improve "Unknown type" error

### ISSUE THREAD

**Issue by bruce** [absinthe-graphql/absinthe#251]
It seems that when an invalid, lowercase type name is given, the error uses the internal naming scheme to report it. We can do better.

Example; when there is no `fooBar` type, for the following query:

```elixir
{
  node(id: "123") {
    id
    ... on fooBar {
      name
    }
  }
}
```

We report it like this:

```elixir
{:ok, %{errors: [%{locations: [%{column: 0, line: 4}], message: "Unknown type \"foo_bar\"."}]}}
```

It should be `fooBar`, not `foo_bar` when reported back to the client.

**Comment by benwilson512** [comment]
This seems to be fixed in both 1.2 and 1.3
