### ISSUE TITLE
Behavior of Absinthe.Schema.Notation.non_null/1

### ISSUE THREAD

**Issue by rsjavier14** [absinthe-graphql/absinthe#252]
Hi everyone.
When I don’t send the `:id` the mutation works without it. Only when I send the `:id` with `null` or `""` the mutation is avoided because the of the non_null on `:id`. 
For example:

``` elixir
input do 
  field :id, non_null(:id)
end
```

 Is this behavior correct? Thanks.

**Comment by benwilson512** [comment]
What version of Absinthe are you on?

**Comment by rsjavier14** [comment]
Absinthe 1.2

**Comment by benwilson512** [comment]
I need the full version please, 1.2.what?

**Comment by rsjavier14** [comment]
sorry, `1.2.0`

**Comment by benwilson512** [comment]
Can you upgrade to 1.2.3 and see if the problem persists? Absinthe should indeed be enforcing internal non null tags.

**Comment by rsjavier14** [comment]
Yes, with absinthe 1.2.3 seems to work as expected.
```
{"errors":[{"message":"Argument \"input\" has invalid value $input_0.\nIn field \"id\": Expected type \"ID!\", found null."}]}
```
Thanks for your help
