### ISSUE TITLE
one_of modifier instead of using enum

### ISSUE THREAD

**Issue by avocade** [absinthe-graphql/absinthe#259]
Our enum values are non-uppercase so we can't use enums straight out of the box. Thought about adding a new `one_of(["const1", "const2"])`, similar to the `non_null()` filter, as a complement when you want to check set-inclusion but not want the value to be auto-formatted.

Maybe I've missed this feature and it already exists :)

**Comment by benwilson512** [comment]
Hey!

Enum already provides this functionality. Simply pass the `name: ` option to `value`.
```
enum :stuff do
  value :foo, name: "foo"
  value :bar, name: "bar"
end
```

**Comment by avocade** [comment]
Knew it! Thanks and sorry for searching so shallowly.
