### ISSUE TITLE
RFC: Scalar Coercion of Non Scalar Inputs

### ISSUE THREAD

**Issue by rschmukler** [absinthe-graphql/absinthe#267]
Per the discussion with @benwilson512 today in Slack, I'd like to propose that Absinthe should allow the coercion of non-scalar inputs (eg. objects) as scalars. Currently Absinthe presumes that these types are `input_object`s.

An example where this could be beneficial is in something like a GeoJSON Feature as input.  GeoJSON can differ based off the type of feature being described. The `type` field specifies which of the union types it is (`Polygon`, `MultiPolygon`, etc). and the `coordinates` field differs depending on the type. See [byanjos/geo](https://github.com/bryanjos/geo) for examples of this complexity:

```ex
 @type polygon :: %Geo.Polygon{ coordinates: [[{number, number}]], srid: integer }
 @type multi_polygon :: %Geo.MultiPolygon{ coordinates: [[[{number, number}]]], srid: integer }
```

To specify this as an input object would require some sort of union type of input object, a proposal which is currently going on in [graphql/graphql-js](https://github.com/graphql/graphql-js/issues/207).

In addition to the tedium of having to define all of the types, and an additional union type, this still limits the resolver functions to having plain old elixir maps as their input. This means that, in the case of something like Geo where you have struct definitions, an additional step in **every** resolver of something like this:

```ex
resolve _, args, _ ->
  feature =
    Geo.JSON.parse(args.geo_shape)

  # Do actual logic
```

To serialize the `Geo.feature` (ie. the union type of `Geo.polygon, Geo.multi_polygon, etc`) requires either encoding it, or creating a duplicate scalar which has a `serialize` function.

To summarize, currently to handle GeoJSON one must:

1) Specify a union input type (not even possible currently)
2) Force the coercion of input objects into structs into the resolve function
3) Specify a custom scalar type for serializing the struct back to GeoJSON (or an additional union type for the output, which forces that coercion back to the resolve function). This would be largely a duplicate of the union input type, but just not an input object.

Alternatively you can also use raw JSON input (ie. a string) and then parse it, but that still requires moving the additional encoding step on the client side to encode that JSON, escape it and then package it into the body.

Both of these seem like extra work that makes the code messier (either on the server-side or the client-side).

Looking forward to hearing people's thoughts and whether there any downsides to allowing this?

**Comment by rschmukler** [comment]
In honesty, this looks like a rehash of #206 which was concluded with not supporting it. That being said, maybe with a more concrete use-case (such as GeoJSON) it's worth a second look... But, perhaps the decision has already been made.

**Comment by benwilson512** [comment]
I think I'm gonna go with closing this at this point. There hasn't been much movement on it, and I think the general consensus is that overriding GraphQL Document syntax is error prone.

It's also worth noting that with Absinthe's pipelines you could totally add this yourself by just injecting a phase that re-wrote particular scalars.
