### ISSUE TITLE
When scalar parsing failed, it returns a server error

### ISSUE THREAD

**Issue by xingxing** [absinthe-graphql/absinthe#275]
Say I have a scalar type:
```elixir
...
@desc """
 format: {YYYY}-{M}-{D}
"""
scalar :date do
   parse &Timex.parse(&1.value, "{YYYY}-{M}-{D}")
   serialize &Timex.format!(&1, "{YYYY}-{M}-{D}")
end
...
```

and use it in my input object

```elixir
 input_object :designer_input do
   ....
   field :birthdate, :date
   ....
end
```

following  mutation will get a status 500
```graphql
mutation {
  createDesigner(designer: {birthdate:"212231213" }){
    name
  }
}
```

the log looks like:
```
[error] #PID<0.495.0> running Hall.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:error, "Expected `1-4 digit year` at line 1, column 1."}
        (absinthe) lib/absinthe/phase/document/arguments/parse.ex:35: Absinthe.Phase.Document.Arguments.Parse.build_value/3
        (absinthe) lib/absinthe/phase/document/arguments/parse.ex:23: Absinthe.Phase.Document.Arguments.Parse.handle_node/2
.....
```

It should returns 400, right?

**Comment by benwilson512** [comment]
I likely need to update the docs. Originally that function simply returned `{:ok, timex_struct} | :error.` Now it seems to return an error with reason tuple. The parse function is expected to return either `{:ok, value} | :error`. If you change your parse function to:
```
parse fn input do
  case Timex.parse(input.value, "{YYYY}-{M}-{D}") do
    {:ok, value} -> {:ok, value}
    _ -> :error
  end
end
```

It will work.

**Comment by xingxing** [comment]
@benwilson512 why not just add a pattern, a lot of parse fun return {:error, reason}, right?

**Comment by benwilson512** [comment]
Because we ignore the reason. Accepting the reason will make people think that we use it somewhere, and we're gonna get issues like "My parse function returns error reason X, but I don't see it anywhere in the response".
