### ISSUE TITLE
Error parsing json field

### ISSUE THREAD

**Issue by cgarciae** [absinthe-graphql/absinthe#279]
I am getting the error: 

> phoenix_1   | Request: POST /graphql
phoenix_1   | ** (exit) an exception was raised:
phoenix_1   |     ** (CaseClauseError) no case clause matching: %{"level" => 2}
phoenix_1   |         lib/absinthe/phase/document/arguments/parse.ex:35: Absinthe.Phase.Document.Arguments.Parse.build_value/3
phoenix_1   |         lib/absinthe/phase/document/arguments/parse.ex:23: Absinthe.Phase.Document.Arguments.Parse.handle_node/2
phoenix_1   |         lib/absinthe/blueprint/transform.ex:13: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2
phoenix_1   |         lib/absinthe/blueprint/transform.ex:105: Absinthe.Blueprint.Transform.node_with_children/5
phoenix_1   |         lib/absinthe/blueprint/transform.ex:119: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
phoenix_1   |         (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
phoenix_1   |         lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.node_with_children/5
phoenix_1   |         (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
phoenix_1   |         (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
phoenix_1   |         lib/absinthe/blueprint/transform.ex:119: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
phoenix_1   |         (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
phoenix_1   |         lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.node_with_children/5
phoenix_1   |         (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
phoenix_1   |         lib/absinthe/blueprint/transform.ex:119: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
phoenix_1   |         (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
phoenix_1   |         lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.node_with_children/5
phoenix_1   |         (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
phoenix_1   |         lib/absinthe/blueprint/transform.ex:119: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
phoenix_1   |         (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
phoenix_1   |         lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.node_with_children/5

when trying to parse a `:json` field defined as

```elixir
scalar :json do
  parse fn input ->
    case Poison.decode(input.value) do
      {:ok, result} -> result
      _ -> :error
    end
  end
  
  serialize &Poison.encode!/1
end
```
The query on the frontend is like this
```graphql
mutation UpdateUser {
  updateUser(
    id: 100,
    email: "ee@gmail.com",
    progress: "{ \"level\": 2 }"
  ){
    id, email, name
  }
}
```
The schema for user is
```elixir
object :user do
  field :id, :id
  field :user_name, :string
  field :token, :string
  field :email, :string
  field :name, :string
  field :progress, :json
end
```

**Comment by benwilson512** [comment]
I will look into this, but I would highly recommend using variables for this purpose. You could simply do:
```
mutation UpdateUser($progress: JSON) {
  updateUser(
    id: 100,
    email: "ee@gmail.com",
    progress: $progress
  ){
    id, email, name
  }
}
```

**Comment by bruce** [comment]
This has been on the backlog for awhile; escaping support is poor. I agree with @benwilson512 -- we'll look at it, but in the short term sending your `:json` type arguments as variables is the best work-around.

**Comment by cgarciae** [comment]
@benwilson512 @bruce Thanks for the comments. However, using variables does not solve the problem. I don't know the internals but Absinthe seems to be wanting to traverse this structure since in the error functions like `walk_children` are called (again I don't know the internals).

**Comment by cgarciae** [comment]
If you take a good look at the actual error you can see 
> no case clause matching: %{"level" => 2}
I know this info is redundant but `%{"level" => 2}` is a map, meaning that it decoded OK.

**Comment by benwilson512** [comment]
Ahh your parse function is wrong. It needs to return `{:ok, value}` not `value`.

**Comment by cgarciae** [comment]
@benwilson512 Thanks!
