### ISSUE TITLE
Server-Side GraphQL

### ISSUE THREAD

**Issue by zimt28** [absinthe-graphql/absinthe#281]
It seems like there is a [plan to provide GraphQL access on the server](https://elixirforum.com/t/phoenix-graphql-tutorial-with-absinthe-add-crud-using-mutations/2729/11?u=zimt28). As I couldn't find anything about it on GitHub, I think it's fine to open an issue.

With the new folder structure of `Phoenix 1.3`, applications will be separated from their interface. The introduction of `context`s seems like an approach to build proper APIs, but it comes with some drawbacks. Quite some people will afterwards build an external API anyway, so I was wondering if it would make sense to completely skip the `context` approach and just build a GraphQL API which then could be used with any interface, including the Phoenix one. 

Questions:

- Whats' the status of this project?
- Would queries return the actual structs?

**Comment by benwilson512** [comment]
Hey!

I would definitely consider still doing phoenix contexts, they would likely be things you would call from within your resolution functions.

To your questions:

1) Very experimental. We've been prioritizing core Absinthe functionality like middlware, and the roadmap on core absinthe functionality is pretty full at the moment. Maybe @bruce should put up what he has and see if someone wants to see if they can run with it?
2) I think that's the idea yes. We definitely don't want to return string keyed maps.

**Comment by bruce** [comment]
I'm going to look at getting a real example of this out as soon as 1.3 is released to stable. I think I've worked through the major concerns I had conceptually (issues with serialization, especially), and Absinthe will be in a place (with a customizable pipeline & resolution middleware) that makes it easier to address them.

**Comment by gdub01** [comment]
A potential use case:

1. Page is rendered server side by phoenix, loading data from an absinthe query.
2. Javascript connects to websockets after pageload and subscribes to the same query that was rendered on server side. 

So you get SSR with phoenix, plus real time functionality

But if you use turbolinks, you can: 
1. Prefetch the next page. 
2. Prevent the websocket part of the page from reloading when you navigate around. 

So with relay2 it won't be coupled to react. So I'm wondering if theoretically you could:

1. Pass the nodeId from the query that was rendered on server side to the websocket subscription.. potentially handled by relay.. so it could pass that nodeId/edge to the websocket channel and subscribe to updates at the appropriate location. 
2. When you move to the next page, you've essentially prefetched the next page's ssr'd graphql query with turbolinks... Then after you arrive on that page, you update the websocket with the relevant node/edge location. 

I'm not sure if that's a good idea? But it seems you'd get fast SSR that's realtime without using much javascript.

**Comment by benwilson512** [comment]
@bruce I feel like further discussion for this may make more sense on https://github.com/absinthe-graphql/absinthe_phoenix

**Comment by bruce** [comment]
Agreed.

**Comment by bruce** [comment]
Closing this. It's a good idea, and planned, but it belongs on absinthe_phoenix.

**Comment by OvermindDL1** [comment]
> Closing this. It's a good idea, and planned, but it belongs on absinthe_phoenix.

You sure?  I already call into absinthe from the server-side already, no phoenix parts at all.  It would be nice to have this pattern 'ratified'.  I find it quite nice to call absinthe on the server side as it is a singular area to access vast amounts of information in the format I want from a variety of areas.

**Comment by benwilson512** [comment]
@OvermindDL1 The existing sense of "server side graphql"  has been related to using graphql with phoenix CRUD actions. There could definitely be an `absinthe-client` library that would make it easier to make GraphQL calls from within elixir more broadly, but that too would be a separate library.

**Comment by OvermindDL1** [comment]
> There could definitely be an absinthe-client library that would make it easier to make GraphQL calls from within elixir more broadly, but that too would be a separate library.

Should an issue be opened to talk about such a suggestion?

**Comment by benwilson512** [comment]
In all honesty such a library isn't even on our radar at this time because there just isn't enough core team bandwidth between spec updates, subscriptions, the book, updated guides, and so on. If someone wants to start an absinthe-client project with the possible idea of it becoming official somewhere down the line they are more than welcome to.

**Comment by bruce** [comment]
100% agree. We would _love_ to see community packages, generally -- and if there's a decent client package made that catches on, we'd be happy to have it become official.

**Comment by dorian-marchal** [comment]
Hi @benwilson512, first of all thanks for your work and general helpfulness on Elixir Forum!
This issue has been opened 4 years ago, so I'm checking: Is calling GraphQL from server side something we can do in 1.6 (maybe via undocumented functions, as you suggested [on Elixir Forum](https://elixirforum.com/t/is-it-possible-to-do-graphql-schema-stitching-with-absinthe/12181/9))?
