### ISSUE TITLE
Module Absinthe.Type.Custom is not available

### ISSUE THREAD

**Issue by sntran** [absinthe-graphql/absinthe#290]
Using `{:absinthe, "~> 1.3.0-beta.0"}` from `hex`, `lib/absinthe/type/custom.ex` is not there. I download the tar file to check as well.

**Comment by benwilson512** [comment]
The beta.0 release does not claim that it is. https://github.com/absinthe-graphql/absinthe/blob/3da2fa883586f67d2da70c824dd8f7a3569c5363/CHANGELOG.md

There are commits on the 1.3 branch not in the current beta. There will be a beta.1 release here soon after a couple bugs are hammered out.
