### ISSUE TITLE
How to separate root schema file?

### ISSUE THREAD

**Issue by ivawzh** [absinthe-graphql/absinthe#294]
Is there a way to separate the root schema file into multiple files?

If no, I would suggest so.

Ideally, I want to be able to put queries and mutations around one resource in each schema file, like conventional REST controller.

**Comment by benwilson512** [comment]
Hey there!

We provide two different mechanisms for splitting up schema files, `import_types` and `import_fields`.

`import_types` can be used to bring the types from another module into a schema. So you can do
```elixir
defmodule MyApp.Schema.Types do
  use Absinthe.Schema.Notation

  object :user do
    field :name, :string
  end

  # other types here
end

defmodule MyApp.Schema do
  use Absinthe.Schema
  
  import_types MyApp.Schema.Types

  query do
    field :users, list_of(:user)
  end
end
```

`import_fields` takes the fields from an object and copies them into the calling object. You can use this to break up the internals of your root `query` and `mutation` objects. To use our previous example:

```elixir
defmodule MyApp.Schema.Types do
  use Absinthe.Schema.Notation

  object :user do
    field :name, :string
  end
  
  object :user_mutations do
    field :create_user, :user do
      arg :name, :string
      resolve &create_user/2
    end
  end
  # other types here
end

defmodule MyApp.Schema do
  use Absinthe.Schema
  
  import_types MyApp.Schema.Types

  query do
    field :users, list_of(:user)
  end

  mutation do
    import_fields :user_mutations
  end
end
```

Does this clarify your concerns?

**Comment by ivawzh** [comment]
I see. So the closest structure compare to conventional REST router & controller will be:

```elixir
defmodule MyApp.Schema do
  use Absinthe.Schema
  
  import_types MyApp.Schema.Types.User
  import_types MyApp.Schema.Types.Car
  import_types MyApp.Schema.Types.Robot
  import_types MyApp.Schema.Types.Monkey
  ...

  query do
    import_fields :user_queries
    import_fields :car_queries
    import_fields :robot_queries
    import_fields :monkey_queries
    ...
  end

  mutation do
    import_fields :user_mutations
    import_fields :car_mutations
    import_fields :robot_mutations
    import_fields :monkey_mutations
    ...
  end
end

defmodule MyApp.Schema.Types.User do
  use Absinthe.Schema.Notation

  object :user_querires do
    field :users, list_of(:user) do
      resolve &find_all_users/3
    end

    field :user, :user do
      resolve &find_one_user/3
    end
  end
  
  object :user_mutations do
    field :create_user, :user do
      arg :name, :string
      resolve &create_user/2
    end

    field :update_user, :user do
      arg :name, :string
      resolve &update_user/2
    end

    field :delete_user, :user do
      arg :name, :string
      resolve &delete_user/2
    end
  end
end
``` 
Am I right? 

This is not bad. It would be even more elegant if there is a helper function that can shortcut `query` and `mutation` registration to something like `import_schema`.

**Comment by benwilson512** [comment]
That would be roughly how it would go yes, although I'm not confident that a REST-like organizational model is the most idiomatic as far as graphql goes.

I could permit `query` and `mutation` to be in different files but I'm not particularly inclined to do so. These are the root entrypoints into a schema and thus I think it is fitting that they always be found in the root schema file.

**Comment by ivawzh** [comment]
I can understand your second statement, but not so well about the first one.

Why would organising the actions of one domain specific resource in one place be not idiomatic in graphql?
