### ISSUE TITLE
List + Non Null Validations

### ISSUE THREAD

**Issue by bruce** [absinthe-graphql/absinthe#31]
Make sure the following rules [from the spec](https://facebook.github.io/graphql/#sec-Combining-List-and-Non-Null) are checked during validation:

- [ ] If the modified type of a List is Non‐Null, then that List may not contain any null items.
- [ ] If the modified type of a Non‐Null is List, then null is not accepted, however an empty list is accepted.
- [ ] If the modified type of a List is a List, then each item in the first List is another List of the second List’s type.
- [ ] A Non‐Null type cannot modify another Non‐Null type.

**Comment by benwilson512** [comment]
Fixed in Master.
