### ISSUE TITLE
Absinthe.Middleware.Batch doc has some issues

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe#310]
> https://hexdocs.pm/absinthe/1.3.0-rc.0/Absinthe.Middleware.Batch.html

- [ ] In the example, the `users_by_id` returns a list yet Map.get is used on it. It should read:
```
{:ok, Enum.find(batch_results, &(&1.id == post.author_id))}
```
- [x] The paragraph `Clearly some of this could be...` need to be updated
- [x] The example in https://hexdocs.pm/absinthe/1.3.0-rc.0/Absinthe.Resolution.Helpers.html#batch/3 is broken, i believe it should be the same as in Absinthe.Middleware.Batch

**Comment by benwilson512** [comment]
Fixed.

**Comment by tlvenn** [comment]
Ha yes, scratch the first item... No idea how I have overlooked the indirection of the middleware which does create a map of results, given I use it in my own code lol...
