### ISSUE TITLE
Additional arguments to a Relay Connection

### ISSUE THREAD

**Issue by ryanwilliams** [absinthe-graphql/absinthe#311]
It would be great if we could supply additional pagination arguments to a relay connection. i.e. so we can send things like `order_by` or `filters`.

Or perhaps there's some other way of doing this, I'm pretty new to graphql?

**Comment by bruce** [comment]
This belongs in the absinthe_relay project, but this should already be possible, eg:

```elixir
connection field :pets, node_type: :pet do
  arg :custom_arg, :custom
  # other args...
  resolve fn
    pagination_args_and_custom_args, %{source: person} ->
      # ... return {:ok, a_connection}
  end
end
```
