### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by yury-dymov** [absinthe-graphql/absinthe#316]
Hey there! First of all, thank you for your efforts and great library!

It's not an issue actually. How do you manage uploading files in general with absinthe and graphql in your phoenix apps?

**Comment by benwilson512** [comment]
Hey, great question! Uploading files is handled by the `Absinthe.Plug` package, you can read more about it here: https://hexdocs.pm/absinthe_plug/Absinthe.Plug.Types.html#content
