### ISSUE TITLE
Easy way to coerce map into a schema object programmatically?

### ISSUE THREAD

**Issue by weixiyen** [absinthe-graphql/absinthe#321]
Was wondering if there was an easy way to coerce a map into an actual schema-compatible object using the scalar transformations.

My use case is I'm sending raw elixir maps through websockets, bypassing the resolvers, but I want to apply the scalar serializers to each field of the map, so it's compatible with the schema fields.

**Comment by benwilson512** [comment]
I think we got this solved on slack. In case anyone else is curious, the idea is to use the `root_value` option like so:
```
Absinthe.run(“{ whatever { field1, field2 }}“, Schema, root_value: %{whatever: %{field1: 1, field2: 2}))
```
