### ISSUE TITLE
Add LICENSE file to the root

### ISSUE THREAD

**Issue by yordis** [absinthe-graphql/absinthe#326]
I notice that Github detects when there is a LICENSE file and put a nice badge with the license and some details about it. I wouldn't hurt to add the file 😄

**Comment by cargosensedev** [comment]
License information moved to LICENSE.md and license badge added to the README. I've also added a Hex.pm badge.

Thanks for the idea!

**Comment by bruce** [comment]
(Consider the above from me -- oops! Thanks again.)

**Comment by yordis** [comment]
Funny, Github do not recognize `BSD` license
