### ISSUE TITLE
Discussion: Code of Conduct

### ISSUE THREAD

**Issue by bruce** [absinthe-graphql/absinthe#333]
All,

While Ben and I have always tried to make Absinthe's development as open and inclusive as possible, we're only two people and I'd like to make sure we have a clear Code of Conduct laid out that represents the values and standards of behavior we all expect of each other as we build the community around Absinthe.

To that end, I'd like to start a discussion in this issue about what standards to adopt. Is there a project Code of Conduct from a project or organization that you think is particularly well-crafted? I'm thinking something low-ceremony, concise, and easy to understand. I welcome your input!

**Comment by bruce** [comment]
Worth noting this feedback, from Twitter: https://twitter.com/AstonJ/status/871460253057110017

So, one recommendation to adopt [Elixir's CoC](https://github.com/elixir-lang/elixir/blob/master/CODE_OF_CONDUCT.md). My inclination is to move in that direction unless there's a consensus that it makes sense to adopt something else.

I'll keep this issue open until noon tomorrow in case anyone feels strongly about alternatives.

**Comment by mgwidmann** [comment]
I agree w/ the above, for comparison though, heres the one that comes with a newly generated ruby gem:
http://contributor-covenant.org/version/1/0/0/
