### ISSUE TITLE
Generate types, schema, and resolver from Ecto schema

### ISSUE THREAD

**Issue by tslater** [absinthe-graphql/absinthe#337]
It would be really nice to have a generator that created some starter code for the schema, types, and resolvers intelligently from an existing Ecto schema. It would make things really fast to get going. For example, on a new or prototype project, I could devise up a schema for database create Ecto models, then from those models, i could generate a GraphQL server in absinthe, all in a few commands. I could then customize the code from there. This could help spread adoption by making it easier to use, and faster to get started, with existing databases. It could also help people understand the code better, by generating examples of associations with a schema they are familiar with.

**Comment by benwilson512** [comment]
Hey!

I think this is a good idea, but it really belongs on https://github.com/absinthe-graphql/absinthe_ecto. We want to avoid having anything specific to one particular data store in this library.

**Comment by tslater** [comment]
Sorry! I wasn't aware of that repo when I made it. I'll lodge it over there.
