### ISSUE TITLE
Smarter error message when key was not found

### ISSUE THREAD

**Issue by nicolas-dular** [absinthe-graphql/absinthe#339]
When the schema is the following:
```elixir
object :user do
  field :name, non_null(:string)
end
```
   
and I'd return a map with string as keys like `%{"name" => "bar"}` instead of using an atom `:name`, the error message is the following:
`The field 'name' resolved to nil, but it is marked non-null in your schema`.

I was just querying data that is stored as jsonb and therefore confused why it didn't work - especially because in the error message it's not `:name` but `'name'`.

However I wanted to fix this by providing a smarter error message, where I check if the key converted to a string would be in the map and error with something like 
`The field 📛  resolved to nil, but is marked as non-null in your schema. There is a field with the key "name", please use atoms instead of strings` (or whatever)

If you also agree that this is message is a good idea: How can I access the result to check the map in the resolution? 
https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/phase/document/execution/resolution.ex#L319

And general question: Is there a reason to not support maps with string keys, but only atoms?

**Comment by benwilson512** [comment]
Hey there. It isn't really a matter of supporting atoms or strings, it's about what the default behaviour is. Every field has a resolver and that resolver can do basically anything to get data, including using string keys. The default resolver however is extremely simple and just looks for atom keys in the map.

If you want to use string keys the most direct thing is to write a custom resolver. This can get a bit repetitive if you do it over and over so a helper function can be handy. A basic example of this is:

```
object :user do
  field :name, :string, resolve: key("name")
end

defp key(key) do
  fn parent, _, _ ->
    {:ok, Map.get(parent, key)}
  end
end
```

If this is something that you want to do for an entire object you're best off using https://hexdocs.pm/absinthe/Absinthe.Middleware.html#content to change the default for that object.

I think we could probably document what the default behaviour is more clearly, but I don't think pushing people to use atoms is the right answer. Using strings is just as valid, it just isn't done for you 100% already.
