### ISSUE TITLE
Language support for NullValue

### ISSUE THREAD

**Issue by mpoeter** [absinthe-graphql/absinthe#344]
Hi all,

in https://github.com/facebook/graphql/pull/83 there is a long discussion about adding support for "null" as a valid value, so that there is a semantically difference between explicitly setting a parameter or member of an input object to null vs. not specifying it at all. The official graphql-js library has already been updated accordingly: https://github.com/graphql/graphql-js/pull/544

At the moment absinthe seems to handle things the "old" way, i.e., there is no difference whether the query contains an explicit null value or not - parameters with null values are filtered out (not passed to the resolver) or replaced with the configured default.

Are you aware of this extension of the GraphQL specification? Do you have plans to add this to Absinthe anytime soon?
I suppose you have plenty of other things on your plate, so I would be happy to help as good as I can. :-)

Cheers,
Manuel

**Comment by benwilson512** [comment]
Hey! We've actually got a PR in for this already https://github.com/absinthe-graphql/absinthe/pull/198 it's just part of the `next` branch. We hope to have Absinthe 1.4 out in beta this week.

**Comment by mpoeter** [comment]
Awsome! :+1: 
I did search the issues before posting, but apparently I missed this one...
