### ISSUE TITLE
shutdown: failed to start child: Absinthe.Subscription.ProxySupervisor

### ISSUE THREAD

**Issue by joshuataylor** [absinthe-graphql/absinthe#346]
Using `~> 1.4.0-beta.1`, sorry if this is not the correct repo, I'll reopen it elsewhere if it is not.

Starting up gives me this error:
```
=INFO REPORT==== 13-Jul-2017::15:12:30 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application frontend: Frontend.Application.start(:normal, []) returned an error: shutdown: failed to start child: Absinthe.Subscription
    ** (EXIT) shutdown: failed to start child: Absinthe.Subscription.ProxySupervisor
        ** (EXIT) shutdown: failed to start child: 1
            ** (EXIT) an exception was raised:
                ** (ArgumentError) argument error
                    (stdlib) :ets.lookup(nil, :subscribe)
                    (phoenix_pubsub) lib/phoenix/pubsub.ex:288: Phoenix.PubSub.call/3
                    (absinthe) lib/absinthe/subscription/proxy.ex:19: Absinthe.Subscription.Proxy.init/1
                    (stdlib) gen_server.erl:365: :gen_server.init_it/2
                    (stdlib) gen_server.erl:333: :gen_server.init_it/6
                    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by benwilson512** [comment]
Hey there. I'm 99% certain this is because your Absinthe.Subscription supervisor child is prior to your Phoenix endpoint child, which is totally my fault for not mentioning in the guides. If you put your supervision tree like:

```
#...,
supervisor(MyApp.Endpoint),
supervisor(Absinthe.Subscription, [MyApp.Endpoint]),
#...
```
Does the problem go away?

**Comment by joshuataylor** [comment]
No matter which order I put the supervisor in it returns the same result.

**Comment by benwilson512** [comment]
Can you show me your endpoint config? Is a pubsub configured?

**Comment by joshuataylor** [comment]
Ah sorry! Forgot about this. I gave this a try again the other day, and it is now working. ¯\_(ツ)_/¯

**Comment by benwilson512** [comment]
@joshuataylor it's looking like it's related to pubsub config, @skosch may have found the issue. We're gonna check with the phoenix folks to make sure a good error gets raised. Keeping this open in the mean time so others who run into this issue can see it.

**Comment by benwilson512** [comment]
Update to Phoenix has been merged, it'll produce a nicer error.

**Comment by ItzaMi** [comment]
Piggy backing this issue, sorry, but it was the first one that I saw with this error.

The error I'm getting
```
** (Mix) Could not start application backend: Backend.Application.start(:normal, []) returned an error: shutdown: failed to start child: Absinthe.Subscription
    ** (EXIT) shutdown: failed to start child: Absinthe.Subscription.ProxySupervisor
        ** (EXIT) shutdown: failed to start child: {Absinthe.Subscription.Proxy, 0}
            ** (EXIT) an exception was raised:
                ** (UndefinedFunctionError) function BackendWeb.Endpoint.node_name/0 is undefined or private
                    (backend 0.1.0) BackendWeb.Endpoint.node_name()
                    (absinthe 1.7.0) lib/absinthe/subscription/proxy.ex:30: Absinthe.Subscription.Proxy.init/1
                    (stdlib 3.17.2) gen_server.erl:423: :gen_server.init_it/2
                    (stdlib 3.17.2) gen_server.erl:390: :gen_server.init_it/6
                    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

These are my deps
```elixir
{:phoenix, "~> 1.6.8"},
{:phoenix_ecto, "~> 4.4"},
{:ecto_sql, "~> 3.6"},
{:postgrex, ">= 0.0.0"},
{:phoenix_live_dashboard, "~> 0.6"},
{:swoosh, "~> 1.3"},
{:telemetry_metrics, "~> 0.6"},
{:telemetry_poller, "~> 1.0"},
{:gettext, "~> 0.18"},
{:jason, "~> 1.2"},
{:plug_cowboy, "~> 2.5"},
{:absinthe, "~> 1.6"},
{:absinthe_plug, "~> 1.5"},
{:cors_plug, "~> 3.0"}
```

My `application.ex` looks like this

```elixir
def start(_type, _args) do
  children = [
    Backend.Repo,
    BackendWeb.Telemetry,
    {Phoenix.PubSub, name: Backend.PubSub},
    BackendWeb.Endpoint,
    {Absinthe.Subscription, [BackendWeb.Endpoint]}
  ]
  opts = [strategy: :one_for_one, name: Backend.Supervisor]
  Supervisor.start_link(children, opts)
end
```

**Comment by tlux** [comment]
> Piggy backing this issue, sorry, but it was the first one that I saw with this error.
> 
> The error I'm getting
> 
> ```
> ** (Mix) Could not start application backend: Backend.Application.start(:normal, []) returned an error: shutdown: failed to start child: Absinthe.Subscription
>     ** (EXIT) shutdown: failed to start child: Absinthe.Subscription.ProxySupervisor
>         ** (EXIT) shutdown: failed to start child: {Absinthe.Subscription.Proxy, 0}
>             ** (EXIT) an exception was raised:
>                 ** (UndefinedFunctionError) function BackendWeb.Endpoint.node_name/0 is undefined or private
>                     (backend 0.1.0) BackendWeb.Endpoint.node_name()
>                     (absinthe 1.7.0) lib/absinthe/subscription/proxy.ex:30: Absinthe.Subscription.Proxy.init/1
>                     (stdlib 3.17.2) gen_server.erl:423: :gen_server.init_it/2
>                     (stdlib 3.17.2) gen_server.erl:390: :gen_server.init_it/6
>                     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
> ```
> 
> These are my deps
> 
> ```elixir
> {:phoenix, "~> 1.6.8"},
> {:phoenix_ecto, "~> 4.4"},
> {:ecto_sql, "~> 3.6"},
> {:postgrex, ">= 0.0.0"},
> {:phoenix_live_dashboard, "~> 0.6"},
> {:swoosh, "~> 1.3"},
> {:telemetry_metrics, "~> 0.6"},
> {:telemetry_poller, "~> 1.0"},
> {:gettext, "~> 0.18"},
> {:jason, "~> 1.2"},
> {:plug_cowboy, "~> 2.5"},
> {:absinthe, "~> 1.6"},
> {:absinthe_plug, "~> 1.5"},
> {:cors_plug, "~> 3.0"}
> ```
> 
> My `application.ex` looks like this
> 
> ```elixir
> def start(_type, _args) do
>   children = [
>     Backend.Repo,
>     BackendWeb.Telemetry,
>     {Phoenix.PubSub, name: Backend.PubSub},
>     BackendWeb.Endpoint,
>     {Absinthe.Subscription, [BackendWeb.Endpoint]}
>   ]
>   opts = [strategy: :one_for_one, name: Backend.Supervisor]
>   Supervisor.start_link(children, opts)
> end
> ```

I got the same error. Did you manage to get it running?

**Comment by skosch** [comment]
Wild-ass guess, but my config says (equivalently)  `{Absinthe.Subscription, BackendWeb.Endpoint}`, instead of `... [BackendWeb.Endpoint]}` – give that a try?

**Comment by tlux** [comment]
I figured it out after some digging in the code. The `node_name/0` function is defined in `Absinthe.Phoenix.Endpoint` which was  not being `use`d on top of my `BackendWeb.Endpoint`.

```
defmodule TemplerClanWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :templer_clan
  use Absinthe.Phoenix.Endpoint # !!!

  # ...
```

It is also stated in the docs, but I was stupid enough to miss it.
