### ISSUE TITLE
GraphiQL ignores `default_url` value

### ISSUE THREAD

**Issue by samphilipd** [absinthe-graphql/absinthe#354]
Here is where I specified my default_url:

```
 forward "/graphiql",
      Absinthe.Plug.GraphiQL,
      schema: Eggl.Schema,
      default_headers: {__MODULE__, :graphiql_headers},
      default_url: "/graphql"
```

But when I visit `/graphiql`, the URL is always `http://localhost:4000/graphiql` (notice the `i`). I would have expected it to be `http://localhost:4000/graphql`.

This persists across different browsers and even different machines so its not a local storage cache issue.

**Comment by benwilson512** [comment]
Hey @samphilipd sorry for just getting to this. Can you open this on `absinthe_plug`? That's where our graphiql integration exists.

Thanks!
