### ISSUE TITLE
Subscription Next Steps

### ISSUE THREAD

**Issue by benwilson512** [absinthe-graphql/absinthe#355]
- [x] Permit a mutation to trigger multiple topics.
- [ ] Build out Subscription behaviour. The goal is to permit document storage mechanisms beyond Registry.
- [x] Document auth story
- [ ] Develop race condition avoidance story. IE when doing `query { orders { id state } }` and then subscribing to each order by id, there's a chance that state updates can be missed.

Proposed solution: `after_subscribe` that triggers a manual subscription push.

**Comment by freshtonic** [comment]
@benwilson512 any chance there will be a way to trigger subscriptions manually - i.e. not via a mutation? My use case is that I have a read-only GraphQL API for consuming notifications but the data updates do not happen via the GraphQL API for legacy reasons.

**Comment by bruce** [comment]
@freshtonic Hello!

Take a peek at the `@doc` here: https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/subscription.ex#L41 – it sounds like that's what you're looking for.

**Comment by freshtonic** [comment]
Hi @bruce!  That looks like what I need. Thanks.

**Comment by matthiasfehr** [comment]
@benwilson512 is there already the possibility to subscribe to multiple topics in one request? Or will it be added in the future?
My use case: I'm doing a chat application and in a single subscribe request i pass an array of group_ids I want to subscribe to.

the schema looks like this (note: the topic function doesn't work like that ATM)
```
subscription do
    field :message_added, :message do
      arg :group_ids, non_null(list_of(:integer))

      topic fn args ->
        args.group_ids
      end
    end
end
```

**Comment by benwilson512** [comment]
@matthewlehner I can definitely look in to it, however I'm not convinced you wouldn't be better off doing 1 subscription per group. Then you can properly unsubscribe from each individual if necessary.

**Comment by matthewlehner** [comment]
@matthiasfehr I believe https://github.com/absinthe-graphql/absinthe/issues/355#issuecomment-325350407 was meant for you ;)

**Comment by benwilson512** [comment]
My apologies!

**Comment by CarmineM74** [comment]
Hi @freshtonic, I'm more or less in the same scenario as yours.
My toy application received data from 2 different sources (Telegram and a Rect app).
So far so good on the React side.
I tried to trigger subscriptions when receiving data from Telegram like this:

```
query = """
mutation {
    createTodo(name: "#{todo_name}") {
        id
        name
    }
}
"""
result = {:ok, %{data: %{"createTodo" => new_todo}}} = query |> Absinthe.run(Schema)
publish_result = Absinthe.Subscription.publish(TodoapiWeb.Endpoint, new_todo, [])
```

With the code above nothing the notification doesn't happen even though the
mutation is run and data persisted.

I also tried to pass the whole result from Absinthe.run to the publish call with
no apparent change.

My subscription is defined as follows:

```
  subscription do
    field :todo_added, :todo do

      config fn _args, _info  ->
        {:ok, topic: "todo_added"}
      end

      trigger :create_todo, topic: fn args ->
        Logger.debug("TRIGGER: #{inspect args}")
        "todo_added"
      end
    end
  end
```

Have you been able to trigger subscriptions manually? If so can you, please, give
me some advices?

Thanks in advance for your help.

**Comment by benwilson512** [comment]
Tabling this issue for now. Subscription feature set is solid for 1.4.0, further additions will happen in 1.4.1
