### ISSUE TITLE
Root Query not using description

### ISSUE THREAD

**Issue by DavidVII** [absinthe-graphql/absinthe#358]
It appears that the `RootQueryType` is not using the `@desc` module attribute above `query`.

```ex
@desc "Documentation for Root Query"
query do
  # ...
end
```

Compiling this bit of code results in an error and no description is passed to the client (using GraphiQL).

Here's the compile error:

```
warning: module attribute @desc was set but never used
  lib/MyApp/graphql/schema.ex:8  # This is where I added @desc above query
```

I'll try and see if I can open a PR to fix this, but I figure I'd open an issue as well.

Cheers!

**Comment by benwilson512** [comment]
@bruce I don't see anything in the spec that forbids this, there's just general discussion of having a description on objects. Seems like it's something we should support, as it'd be a natural place to put high level API documentation.

**Comment by bruce** [comment]
@benwilson512 Right, an object is an object is an object. Supporting a description on the root query object is clearly an oversight on our part.

**Comment by bruce** [comment]
Worth mentioning, btw, that I think there's a workaround; you should still be able to pass a `description: "Your description here"` option to the `query` macro. The `@desc` is (basically) syntactic sugar for doing that.

**Comment by benwilson512** [comment]
Fixed in master!
