### ISSUE TITLE
Issue with the latest plug(1.4.3) 

### ISSUE THREAD

**Issue by zhhz** [absinthe-graphql/absinthe#360]
I'm very new to Elixir, playing around with Absinthe, after upgrade to Elixir 1.5, I did a

`
 $mix deps.update --all
`

Now I'm getting the error:

> 

Server: localhost:4000 (http)
Request: OPTIONS /graphql
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in anonymous fn/2 in Plug.Conn.merge_resp_headers/2
        (plug) lib/plug/conn.ex:663: anonymous fn({"access-control-expose-headers", []}, [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "s83p1st550ks4i88vkahrdlopo2nk6am"}, {"vary", "Origin"}, {"access-control-allow-origin", "http://localhost:3000"}]) in Plug.Conn.merge_resp_headers/2
        (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
        (plug) lib/plug/conn.ex:663: Plug.Conn.merge_resp_headers/2
        (cors_plug) lib/cors_plug.ex:33: CORSPlug.call/2

I really wish I could be more helpful or can contribute to the project, but still in the learning process...

Thanks.

P.S. sorry for not helping much...

**Comment by benwilson512** [comment]
Hey there. I'm sorry you're running into issues. This issue however has to do with your cors_plug dependency not Absinthe. You can tell this from two things:

1) It's an OPTIONS request which is the kind of thing that'll get handled by cors
2) The error is in the `cors_plug` module.

**Comment by zhhz** [comment]
@benwilson512 Thanks for the prompt response, you're right, the cors_plug got updated to 1.4.0, that could be issue.

Thanks again.
