### ISSUE TITLE
Unsubscribe does not actually remove the subscription?

### ISSUE THREAD

**Issue by kciombor** [absinthe-graphql/absinthe#361]
**Expected result**
After unsubscribing and subscribing again the subscription data should be received once.

**Actual result**
After unsubscribing and subscribing again the subscription data is received multiple times, equal to the number of times a subscription request was sent.

**Steps to reproduce**
GraphQL schema:
```elixir
mutation do
        field :create_user, :user do
            arg :first_name, non_null(:string)
            arg :last_name, non_null(:string)

            resolve &Web.UserResolver.create/3
        end
end

subscription do
        field :user_added, :user do
            topic fn _args ->
                ""
            end

            trigger :create_user, topic: fn _user ->
                ""
            end
        end
end
```

Now, I've been able to reproduce this using a GraphiQL interface.
1. Go to GraphiQL explorer and input:
```graphql
subscription {
  userAdded {
    id
  }
}
```
2. Execute the query. The message: "Your subscription data will appear here after server publication!" is displayed
3. Repeat the query execution multiple times and observe the websocket network messages. Each time this query is executed the following two messages are sent:
```json
{"topic":"__absinthe__:control","event":"unsubscribe","payload":{"subscriptionId":"__absinthe__:doc:125735578"},"ref":"29"}
{"topic":"__absinthe__:control","event":"doc","payload":{"query":"subscription {\n userAdded {\n id\n }\n}","variables":null},"ref":"30"}
```
and the following responses are received:
```json
{"topic":"__absinthe__:control","ref":"29","payload":{"status":"ok","response":{"subscriptionId":"__absinthe__:doc:125735578"}},"join_ref":null,"event":"phx_reply"}
{"topic":"__absinthe__:control","ref":"30","payload":{"status":"ok","response":{"subscriptionId":"__absinthe__:doc:125735578"}},"join_ref":null,"event":"phx_reply"}
```
Interestingly, the new subscription always gets the same exact `subscriptionId`.
4. Execute a mutation query, for example:
```graphql
mutation {
  createUser(firstName: "Test", lastName: "Test") {
    id
  }
}
```
5. The subscription is received multiple times, with the following data:
```json
{"topic":"__absinthe__:doc:125735578","ref":null,"payload":{"subscriptionId":"__absinthe__:doc:125735578","result":{"data":{"userAdded":{"id":"41"}}}},"join_ref":null,"event":"subscription:data"}
```

Here are my absinthe dependencies:
```elixir
{:absinthe, "~> 1.4.0-beta.3"},
{:absinthe_phoenix, "~> 1.4.0-beta.2"},
{:absinthe_ecto, "~> 0.1.0"},
{:absinthe_plug, "~> 1.4.0-beta.1"},
```

**Comment by benwilson512** [comment]
Hey! I think that I'm forgetting to unsubscribe inside the Absinthe.Phoenix project. Will investigate.

**Comment by arathunku** [comment]
I've just bumped into that and fixed it locally.

There's `Phoenix.PubSub.subscribe` used but `Phoenix.PubSub.unsubscribe` is nowhere to be found in the channel implementation. 

```elixir
  def handle_in("unsubscribe", %{"subscriptionId" => doc_id}, socket) do
    Phoenix.PubSub.unsubscribe(socket.pubsub_server, doc_id) # added, fixes the issue
    Absinthe.Subscription.unsubscribe(socket.endpoint, doc_id)
    {:reply, {:ok, %{subscriptionId: doc_id}}, socket}
  end
```

Should I submit a PR with that?

**Comment by kciombor** [comment]
I can confirm that this does indeed fix the issue.

**Comment by benwilson512** [comment]
Fixed in Absinthe.Phoenix master!
