### ISSUE TITLE
field names ending with _ number

### ISSUE THREAD

**Issue by baldmountain** [absinthe-graphql/absinthe#367]
I have a set of fields like:

```
      logo_url
      logo_url_1
```

When entering a query into graphiql it says that logo_url_1 should be queried as logoUrl1 but this generates an error. I can query with logo_url_1 or logoUrl_1 but not logoUrl1 as graphiql suggests. I can work around this by having folks using the API use logo_url_1 so it isn't critical. Just thought I'd mention it.

**Comment by baldmountain** [comment]
Actually. THis happens for a number anywhere in a field name that is preceeded with an underscore `_`.

**Comment by benwilson512** [comment]
Hey! Absinthe uses `Macro.underscore` to map external values to internal values:
```
iex(1)> "logoUrl1" |> Macro.underscore
"logo_url1"
```

The field name then should be `:logo_url1`

**Comment by baldmountain** [comment]
I'm mapping an existing database field name: logo_url_1. It's not something I can change.

**Comment by benwilson512** [comment]
You don't need to change the DB column, just add a resolver then.

```
field :logo_url1, :string do
  resolve fn parent, _, _ -> {:ok, parent.logo_url_1} end
end
```

Part of the point of GraphQL is that you don't need to have a 1:1 mapping of internal data to external representations. In this case I'd even consider dropping the `1` entirely.
