### ISSUE TITLE
How could I make some fields reachable only for certain types of contexts/operations?

### ISSUE THREAD

**Issue by asiniy** [absinthe-graphql/absinthe#373]
subj

Can't get how to restrict some field of the `object`. Haven't found any documentation too

**Comment by bruce** [comment]
See http://absinthe-graphql.org/guides/context-and-authentication/.

**Comment by asiniy** [comment]
Hm, I still can't figure out which mutation is called from the `context`. `%Absinthe.Resolution{}` is kinda complicated struct

**Comment by asiniy** [comment]
The only thing I found now - is to search for mutation inside results of `Absinthe.Resolution.path_string(context)`. Is there any better way?
