### ISSUE TITLE
(MatchError) no match of right hand side value: {:error, :enoent}

### ISSUE THREAD

**Issue by Aleksion** [absinthe-graphql/absinthe#376]
I'm receving this error whenever I try to generate a schema.json from my schema.

I've tried slimming down the schema to almost nothing to see whether it was a change I made. But no matter what, it keeps throwing this error:

```
-m: inotifywait: command not found
** (MatchError) no match of right hand side value: {:error, :enoent}
    (absinthe) lib/mix/tasks/absinthe.schema.json.ex:59: Mix.Tasks.Absinthe.Schema.Json.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2
-m: line 0: kill: (42854) - No such process
```

Any ideas?

**Comment by Aleksion** [comment]
This error only happens on 1.4.0-beta 
I just downgraded to 1.3 and it works again.

**Comment by benwilson512** [comment]
Can you upgrade back to 1.4.0-beta and do an `rm -rf _build`? Sometimes priv artifacts aren't copied over during compilation for some reason.

**Comment by Aleksion** [comment]
That did the trick! And it fixed another problem i was having. Gonna keep that in mind going forward. Thank you!
