### ISSUE TITLE
Using `field` without a type raises at run-time instead of compile time

### ISSUE THREAD

**Issue by hanrelan** [absinthe-graphql/absinthe#381]
If I have in my schema:
```
  object :dataset do
    field :latest_version, :version
    field :name
  end
```
I would expect that I would get an error at compile time, but I only see the error at run-time ("Can't query field 'name'")

**Comment by benwilson512** [comment]
Proposed solution: `field/1` macro in `Absinthe.Schema.Notation` module to explicitly raise with a helpful error message.

Root issue: non-macros are basically elided in schemas due to how execution works. Not fully fixable without a rework of how schemas are built.

**Comment by benwilson512** [comment]
Closed in favor of https://github.com/absinthe-graphql/absinthe/issues/410
