### ISSUE TITLE
Beta 4 compile error - parse_decimal

### ISSUE THREAD

**Issue by jatsrt** [absinthe-graphql/absinthe#383]
== Compilation error in file lib/absinthe/type/custom.ex ==
** (CompileError) lib/absinthe/type/custom.ex:68: undefined function parse_decimal/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

**Comment by bruce** [comment]
I've reproduced this. Thanks for reporting it; will get a new version out shortly.

**Comment by bruce** [comment]
@jatsrt I'll be releasing Beta 5 here shortly. Can you confirm your project doesn't have a requirement on `decimal` (eg, you're not using Ecto)? That looks like the cause of the issue––my guess is that you're just the first person to try it out with that setup since `:decimal` was introduced.

**Comment by bruce** [comment]
Fix in 1.4.0-beta.5. Please reopen if that doesn't resolve the problem, and thank you again for reporting it.

**Comment by jatsrt** [comment]
@bruce you are correct, no ecto
Confirmed 1.4.0-beta.5 fixes
