### ISSUE TITLE
Args of fields inside an input object

### ISSUE THREAD

**Issue by nitingupta910** [absinthe-graphql/absinthe#391]
I'm not sure if this is absinthe bug or a limitation of graphql spec itself. I see that defining arguments of fields defined inside `input_object`s don't have any effect: all input_object fields are treated as if they don't take any arguments. For example:

```
  input_object :node_input do
    field :id, :string
    field :out, list_of(:node_input) do
      arg :edge, non_null(:string)
    end
    field :prop, :literal_input do
      arg :id, non_null(:string)
    end
  end
```

Above compiles fine, but when trying to use args of fields like `out` and `prop`, I get query parsing error. An example query:

```

mutation MyMutation {
  node(input: {
      prop(id: "prop_id"): {
        value: "foo"
        lang: "en"
      }
  }) {
    id
    name
  }
}
```

Above mutation gives parse error at prop(id: ..). Removing the id arg over there works.

For reference, here is schema.ex:
```
  mutation do
    field :node, type: :node do
      arg :input, :node_input
    end
  end
```

Versions:
elixir 1.5.1
erlang 20
absinthe 1.5-rc

**Comment by benwilson512** [comment]
Hey! Per the spec, input object fields don't take arguments, nor resolvers.

The fact that it compiles is unfortunate, but it's largely a function of how the macro based DSL works at the moment. We do have a planned re-work of the macro system for version 1.5, that will hopefully make it clearer at compile time that this isn't supported.
