### ISSUE TITLE
Unreferenced object appears in graphiql documentation

### ISSUE THREAD

**Issue by rzane** [absinthe-graphql/absinthe#392]
I'm using absinthe version 1.3.2, and I'm trying to pull shared fields into an object for the sole purpose of using `import_fields` in other objects.

My types look like this:

```elixir
object :organization_abstract do
  field :name, :string
end

object :organization do
  field :id, :id
  import_fields :organization_abstract
end

input_object :organization_input do
  field :value, :string
  import_fields :organziation_abstract
end
```

I expected `OrganizationAbstract` not to appear in the graphiql documentation section, but it seems to be showing:

<img width="340" alt="screen shot 2017-09-16 at 4 21 29 pm" src="https://user-images.githubusercontent.com/2731572/30515732-5606e778-9afb-11e7-8c03-3789540b488f.png">

Note: I haven't referenced `:organization_abstract` anywhere else in my schema.

**Comment by bruce** [comment]
Thanks for reporting this issue; it finally gave us the nudge to solve it!

I believe this is fixed in `master` (and will be released within the next day or so). Please reopen if this doesn't solve the problem as expected.
