### ISSUE TITLE
Modify & persist context in middlewares

### ISSUE THREAD

**Issue by G3z** [absinthe-graphql/absinthe#398]
Currently the context is rebuilt on each connection and discarded after resolution.
This works well with http where each document is sent in a different request but it's an issue when using a persistent connection (in my case WebSockets).

My use case: Authentication
using WS the connection is anonymous and after a certain mutation the user is authenticated. 
At the moment I'm forced to disconnect and reconnect to generate the correct context with the `current_user` populated (from a token)

From what i could understand: the context is discarded in the pipeline after `Absinthe.Phase.Document.Result`, would it be possible to obtain the context modified by middlewares this way https://github.com/absinthe-graphql/absinthe_phoenix could simply use `assign(socket,:context, new_context` to automagically update the execution context

**Comment by benwilson512** [comment]
The context isn't discarded as far as I know, it's still inside the blueprint. The issue is that absinthe_phoenix is discarding the context returned when running a document. I think this issue belongs there.
