### ISSUE TITLE
Manual publish does not work w/ ecto structs

### ISSUE THREAD

**Issue by mgwidmann** [absinthe-graphql/absinthe#401]
The example shown here:
https://hexdocs.pm/absinthe/1.4.0-rc.2/Absinthe.Schema.html#subscription/2
(specifically the line `Absinthe.Subscription.publish(pubsub, user, [new_users: user.account_id])`)

doesn't actually work since there is a type mismatch between the subscribed topic and the published one.

Basically, in the config function, `args.id` is a string since the absinthe `ID` type comes in as a string, but since ecto structs get typecasted to numbers and so the `publish/3` call ends up publishing to topics clients are not listening to.

_WORKAROUND_: To get this to work you can either turn your topic key in your publish call into a string to match the topic subscribed like: `Absinthe.Subscription.publish(pubsub, user, [new_users: to_string(user.account_id)]) # Note the to_string at the end here` **OR** convert the topic in the config function to an integer.

Since all phoenix topics are strings, I don't think restricting the topic to strings only is of any major limitation as users will probably expect this is happening under the hood (as I did). Either the docs should be updated to note this, or that key should be converted here: https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/subscription/local.ex#L49 (and above on 46).

**Comment by tlvenn** [comment]
I got bitten by this previously as well and for now I end up using to_string as in your example. I agree that most probably Absinthe should cast to string by itself, it will save some trouble for anyone digging into subscription and trying to publish manually.

@benwilson512 what do you think ?

**Comment by benwilson512** [comment]
Originally I wasn't sure what would be more useful, automatic string coercion or the ability to have topics like `{foo, bar}`. In practice, this string issue has bitten a number of people, and neither I nor anyone else as far as I know has gotten much out of letting it be any term.

I think at this point it makes the most sense to just `to_string` everything and if someone has a compelling use case for arbitrary topics then we'll look at solutions then.

**Comment by mgwidmann** [comment]
`{foo, bar}` can always become `"#{foo}:#{bar}"` as long as you're consistent within your own application it'll all work as expected... Debugging broadcasting issues in general isn't easy so anything that makes that more understandable from the user's point of view is a big win IMO.
