### ISSUE TITLE
List coercion

### ISSUE THREAD

**Issue by bruce** [absinthe-graphql/absinthe#45]
Ensure the coercion parts of https://facebook.github.io/graphql/#sec-Lists are implemented.

**Comment by benwilson512** [comment]
This has been done for Inputs, but not outputs.

**Comment by bruce** [comment]
@benwilson512 Is this worth/quick enough to get into v1.1?

**Comment by benwilson512** [comment]
I'm not sure, this is all resolution logic stuff at this point which isn't an area I'm very familiar with yet.

**Comment by bruce** [comment]
@benwilson512 Now that you're an expert at resolution, what's your feeling on the complexity here? ;-)

**Comment by bruce** [comment]
Superseded by v1.2 work.
