### ISSUE TITLE
Function is called more than 3 times?

### ISSUE THREAD

**Issue by AlexanderChen1989** [absinthe-graphql/absinthe#450]
https://github.com/absinthe-graphql/absinthe/blob/ac7431e8620c3ae2079e4a66c74369a1c2e93f49/lib/absinthe/middleware.ex#L147

```elixir
defmodule Schema do
  use Absinthe.Schema

  def middleware(middleware, field, object) do
    middleware |> IO.inspect

    middleware
  end

  object :user do
    field :name, :string
    field :age, :integer
  end

  query do
    field :lookup_user, :user do
      resolve fn _, _ ->
        {:ok, %{name: "Bob"}}
      end
    end
  end
end


defmodule Main do
  @query "{ lookupUser { name } }"

  def run do
    Absinthe.run(@query, Schema)
  end
end
```

<img width="1058" alt="2017-11-18 10 30 35" src="https://user-images.githubusercontent.com/2957936/32981373-2a2e7e40-ccb0-11e7-8f50-39c05a8a84f9.png">

**Comment by benwilson512** [comment]
Hey! The documentation could be reworded slightly. The exact number of times that the `middleware` callback is called is something of an implementation detail. What the documentation is trying to get at is that at some point, the function will get called with those values. I'll update the docs.

**Comment by benwilson512** [comment]
I have updated the middleware docs.
