### ISSUE TITLE
Introspection query is missing interface types

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe#454]
Similarly to #431, @craig-day reported in https://github.com/absinthe-graphql/absinthe_plug/issues/123 that he cant see some interface types in GraphiQL anymore, meaning the Introspection query is not returning them anymore.

**Comment by benwilson512** [comment]
Can you provide a minimal schema that exhibits this behaviour? I'm having trouble reproducing. We have an existing test case that seems like it would cover this, I wonder what is different? https://github.com/absinthe-graphql/absinthe/blob/master/test/lib/absinthe/schema_test.exs#L204-L210

**Comment by tlvenn** [comment]
@benwilson512 he posted his schema there: https://github.com/absinthe-graphql/absinthe_plug/issues/123#issue-274774172

**Comment by craig-day** [comment]
@benwilson512 for full disclosure and so you can see all of the code, here is a brand new phoenix project with `absinthe_plug` that will repro the error. https://github.com/craig-day/broken_interface

**Comment by benwilson512** [comment]
Ahhh I see, it isn't returning types that are only linked to the root VIA an interface. Will have a fix up shortly.

**Comment by craig-day** [comment]
Wow. Thanks for the quick fix! Any chance we can get a patch released?

**Comment by benwilson512** [comment]
v1.4.3 is now live :)

**Comment by craig-day** [comment]
Woo! Thanks again. ❤️
