### ISSUE TITLE
Circular reference in interface

### ISSUE THREAD

**Issue by stefanoferretti** [absinthe-graphql/absinthe#460]
Hi all,
I've a problem with circular references in interfaces.

Sample code:
```
interface :service do
  field :parent, :service
end
```
This compiles correctly but if I try to introspect or prime the Schema (Absinthe.Test.prime) Absinthe.Type.referenced_types never exits from the recursion (recurse indefinitely on service type).

The same is true also with the following code
```
interface :service do
  field :activities, list_of(:activities)
end

interface :activity do
  field :service, :service
end
```

This has been tested on 1.4.3 (everything works well in 1.3.2)

**Comment by benwilson512** [comment]
Fixed in v1.4.4, thanks!
