### ISSUE TITLE
Redefining a type should throw a warning or an error

### ISSUE THREAD

**Issue by knewter** [absinthe-graphql/absinthe#466]
Presently, if we define a type twice the last definition wins. It would be nice if instead we could blow up at compile time, either with a warning or (preferably) an error, because it's never going to be what someone wants to do. I wasted an hour debugging until I found that I'd double-defined a type with the same name :-\ Not the fault of absinthe, but it seems like it would be nice to save all the "future-me"s that time :)

**Comment by benwilson512** [comment]
This works in 1.5 / master

**Comment by ckruse** [comment]
Great news! I wasted a couple of hours debugging this ;-)
