### ISSUE TITLE
timeout on complex query?

### ISSUE THREAD

**Issue by mydearxym** [absinthe-graphql/absinthe#469]
hi there ~ 

i am working on a GraphQL-related project with absinthe and Face a [situation](https://www.howtographql.com/advanced/4-security/):  

> For example, a server configured with a 5 seconds timeout would stop the execution of any query that is taking more than 5 seconds to execute.

i read the [question on Elixir/forum](https://www.howtographql.com/advanced/4-security/), but it seems unsolved .

may i ask is there a official solution for this kind of situation ?

**Comment by benwilson512** [comment]
Hey @mydearxym. In general this kind of thing is handled by the caller of a function, not the function itself. For example:

```
task = Task.async(fn -> Absinthe.run(some_query, some_schema)
Task.yield(task, timeout: 30_000)
```

If you wanted to work this into a plug:

```
defmodule TimeLimitedPlug do
  def init(opts), do: Absinthe.Plug.init(opts)
  def call(conn, opts) do
  task = Task.async(fn -> Absinthe.Plug.call(conn, opts) end)
    case Task.yield(task, timeout) || Task.shutdown(task) do
      {:ok, conn} ->
        conn
      nil ->
        Logger.warn "Absinthe failed to run in #{timeout}ms"
        conn
        |> # put whatever response you want here if it timesout
    end
  end
end
```

In short, there are a variety of built in ways to handle time limits, there isn't really anything Absinthe itself needs to do here.
