### ISSUE TITLE
Mutation to trigger multiple topics

### ISSUE THREAD

**Issue by Yamilquery** [absinthe-graphql/absinthe#475]
I found a way to trigger a subscription with multiple topics, however, I don't know if it is the best way to do it.

Here is my code.

```
object :attention_added_subscription do
    field :attention_added, type: :attention do
      arg :employee_id, non_null(:integer)
      arg :dt_start, :string

      config fn args, _ ->
        date = Date.from_iso8601!(args.dt_start) |> Date.to_string
        {:ok, topic: "#{args.employee_id}-#{date}"}
      end

      trigger :create_attention, topic: fn attention ->
        "#{attention.employee_id}-#{Date.to_iso8601(attention.dt_start)}"
      end
      resolve fn attention, _, _ ->
        {:ok, attention}
      end

    end
  end
```

In my example I subscribed to the mutation _create_attention_ and this is triggered when _employee_id_ and _dt_start_ (only date) are equal.

Thank you!

**Comment by benwilson512** [comment]
hey @Yamilquery. Per the issue template, please ask questions on the forums or in slack. The issue tracker is for issues, not help requests.
