### ISSUE TITLE
nil value for payload returned from dataloader

### ISSUE THREAD

**Issue by jerelmiller** [absinthe-graphql/absinthe#485]
First of all, I'd like to say thank you for the package. Absinthe has made writing GraphQL backends so much fun. Thanks for all the work put into it so far. 

### Environment

* Elixir version (elixir -v): 1.5.1
* Absinthe version (mix deps | grep absinthe): 1.4.5
* Client Framework and version (Relay, Apollo, etc): Relay

### Expected behavior

Given this mutation:

```
mutation JoinRoom($roomId:ID!) {
  joinRoom(input: {roomId: $roomId}) {
    participant {
      id
      account {
        id
        __typename
      }
    }
    room {
      id
      participants(first: 50) {
        edges {
          node {
            id
            account {
              id
              __typename
            }
          }
        }
      }
    }
  }
}
```

That `account` field is a non-null field. In this mutation, I'm returning the newly created `participant` and its associated `account`, then also selecting the room with all participants listed. This `participants` connection includes the same record as the top-level `participant` field. I use the `dataloader` helper in my schema to batch the `account` call from participant -> account (account is polymorphic, but shouldn't matter in this case).

I would expect that all records within the `participants` connection properly include `participant`.

### Actual behavior

The record within `participants` that matches the top-level `participant` field, curiously has a `null` value for `account`. The top-level record includes the `account` properly, and so do all the other `participants` in the connection. The issue only arises for the `participant` in that list that matches the top-level.

### Relevant Schema/Middleware Code

**schema.ex**
```elixir
defmodule MyAppWeb.Schema do
  # ... definitions

  mutation do
    payload field :join_room do
      input do
        field :room_id, :id
      end

      output do
        field :participant, :participant
        field :room, :room
      end

      middleware Absinthe.Relay.Node.ParseIDs, room_id: :room

      resolve &Resolvers.Room.join/2
    end
  end

  def context(context) do
    loader = 
      Dataloader.new()
      |> Dataloader.add_source(:accounts, GenericLoader.source(context))
      |> Dataloader.add_source(:participants, GenericLoader.source(context))

    context
    |> Map.put(:loader, loader)
  end

  def plugins do
    [Absinthe.Middleware.Dataloader | Absinthe.Plugin.defaults()]
  end
end
```

**types.ex**
```elixir
  interface :account do
    # other fields ...

    resolve_type fn
      %Account.User{}, _ -> :user
      %Account.Guest{}, _ -> :guest
      _, _ -> nil
    end
  end

  node object :room do
    # other fields ...
    connection field :participants, node_type: :participant do
      resolve dataloader(:participants)
    end
  end

  node object :participant do
    # other fields ...
    field :account, :account, dataloader(:accounts, fn
      %{guest_id: nil} -> :user
      %{user_id: nil} -> :guest
    end)
  end
```

Let me know if there is any other relevant code I can provide. Thanks in advance for the help!

**Comment by benwilson512** [comment]
Hey, sorry I didn't get to this earlier.

Dataloader is not yet compatible with the connection macros. I need to find a place to document this because this comes up a fair bit. The only way to do batched SQL queries with limits is via lateral joins or window functions, neither of which are well supported by ecto.

**Comment by Aleksion** [comment]
@benwilson512 is this still the case?

**Comment by benwilson512** [comment]
Yes. Ecto has support for window functions now, a PR would be welcome to utilize this within Dataloader.

**Comment by tlvenn** [comment]
Ya that would be awesome.
