### ISSUE TITLE
inline Fragment get error hint

### ISSUE THREAD

**Issue by mydearxym** [absinthe-graphql/absinthe#488]
Hi guys ~

defined schema like this: 

```elixir
interface :content_result do
    field(:id, :id)
    field(:title, :string)
    field(:body, :string)
    field(:author, :author, resolve: assoc(:author))
    # comments / author ...
    resolve_type(fn
      %CMS.Post{}, _ -> :post
      _, _ -> :fuck
  end)
end
```

```elixir
object :post do
    interface(:content_result)
    field(:id, :id)
    field(:title, :string)
    field(:body, :string)
    field(:author, :author, resolve: assoc(:author))
    field(:views, :integer)
end
```

query in graphQL-playground , it worked, but got error hint : 

>  Fragment cannot condition on non composite type "Post"

![error](https://user-images.githubusercontent.com/6184465/34980010-069e3892-fade-11e7-87ad-7f26c5a1b797.png)

**Comment by benwilson512** [comment]
Can you show your `:content` field? Also, do note that resolvers on an interface type are never used.

**Comment by benwilson512** [comment]
If `:content` returns `:post` then that hint seems wrong:

https://github.com/facebook/graphql/blob/master/spec/Section%205%20--%20Validation.md#fragments-on-composite-types

> Fragments can only be declared on unions, interfaces, and objects. They are invalid on scalars. They can only be applied on non-leaf fields. This rule applies to both inline and named fragments.

Fragments on an object are valid. Not sure what playground is upset about.

**Comment by mydearxym** [comment]
sorry, it seems the playground issue ..
