### ISSUE TITLE
nested input_object support 

### ISSUE THREAD

**Issue by mydearxym** [absinthe-graphql/absinthe#491]
Hi guys ~

i defined a input_object inside a input_object, and the returned schema to front seems not right ?

```elixir
input_object :sort_input do
  field(time: :time_enum, default_value: :all)
  field(trend: :trend_enum, default_value: :year)
end

input_object :article_filter do
   field(:tag, :string, default_value: :all)
   field(:sort, :sort_input)
end
```

```elixir
 ...
field :posts, non_null(list_of(non_null(:post))) do
   ...
   arg(:filter, :article_filter)
   ...resolver... 
end
```
parse error in GraphQL-playground ..

![image](https://user-images.githubusercontent.com/6184465/35132954-bb36a15a-fd08-11e7-8590-0dff31f2f79e.png)

**Comment by bruce** [comment]
Your field definitions for `:sort_input` appear to be passing a keyword list instead of the identifier and type, so the fields are likely misconfigured. Try:

```elixir
input_object :sort_input do
  field :time, :time_enum, default_value: :all
  field :trend, :trend_enum, default_value: :year
end
```

**Comment by bruce** [comment]
You _can_ provide the type as part of the options keyword list, but not the identifier. If you wanted to do that, it would look like:

```elixir
input_object :sort_input do
  field :time, type: :time_enum, default_value: :all
  field :trend, type: :trend_enum, default_value: :year
end
```

I find that especially helpful for readability when the field identifier and the type are the same. Probably less an issue with your schema as you're suffixing with `_enum`.

**Comment by mydearxym** [comment]
@bruce  thanks , your advise make more sense, but i think nested input_object is a nice-to-have function.

**Comment by benwilson512** [comment]
@mydearxym What do you mean by nested input object? `filter: {sort: {time: YEAR}` is completely possible. The problem is that your `:sort_input` is improperly configured it looks like.

**Comment by mydearxym** [comment]
@benwilson512  nested input object is a input-object defined inside a input-object,  `filter: {sort: {time: YEAR}` is causing error in GraphQL-playground .

**Comment by benwilson512** [comment]
@mydearxym can you follow up on the forums? Everything you're asking for in terms of usage is entirely possible, so I think this is more of a question and learning thing an issue. Thanks!
