### ISSUE TITLE
Introspection compiles but returns invalid schema at runtime if you include a `resolve` on an input object

### ISSUE THREAD

**Issue by samphilipd** [absinthe-graphql/absinthe#506]
Introspection compiles but returns invalid schema at runtime if you include a `resolve` on an input object.

This is a big problem because it is easily done by accident and can be a while before the problem is discovered, making it really hard to track down and debug.

### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.1 (compiled with OTP 20)
```

* Absinthe version (mix deps | grep absinthe):

```
* absinthe 1.4.7 (Hex package) (mix)
  locked at 1.4.7 (absinthe) c9241130
```

* Client Framework and version (Relay, Apollo, etc):

Any client.

### Expected behavior

Invalid input objects raise a compile time, or at least a runtime error.

### Actual behavior

Schema with invalid input object does not raise any error, but the generated introspection schema is invalid. Different clients fail in different ways. GraphiQL fails like this:

```
invariant@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:18:18624
t@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:25638
m@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:28058
keyValMap/<@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:18:19449
keyValMap@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:18:19411
y@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:27983
fields@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:27746
resolveThunk@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:19:26631
[256]</exports.GraphQLInputObjectType</e.prototype._defineFieldMap@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:20:5776
[256]</exports.GraphQLInputObjectType</e.prototype.getFields@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:20:5699
typeMapReducer@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:2991
typeMapReducer@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:2283
typeMapReducer/<@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:2877
typeMapReducer@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:2773
e@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:6282
buildClientSchema@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:29467
value/<@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:14:12748
```

### Steps to reproduce

Create an input object like this:

```
input_object :my_input do
  field :my_field, :integer do
    resolve(fn -> do_something end)
  end
end
```

**Comment by SkyLeite** [comment]
Hey. I came across this 4 year old issue when I had an empty / missing `query` object in my schema.

```ex
query do
end
```

The snippet above is enough to trigger it.

**Comment by maartenvanvliet** [comment]
A Query definition is of the Object type and per the spec: 

> An Object type must define one or more fields.

So it's no surprise it yields invalid introspection results. There should probably be a check for this.

**Comment by benwilson512** [comment]
I know we require `query do`, I don't think we require fields.

**Comment by kdawgwilk** [comment]
Is there an existing phase that makes sense for this check to live or would a new phase be best?

**Comment by aphillipo** [comment]
My issue was that I had input_object and not object when copy pasting and forgot to delete the input_ so something ended up missing in my union type.
