### ISSUE TITLE
Error message when trying to pass string into Enum attribute/parameter is not very clear

### ISSUE THREAD

**Issue by vasspilka** [absinthe-graphql/absinthe#508]
Having a *User schema with binary list roles* l create the following object with enum type for Role
``` 
  object :user do
    field(:id, :id)
    field(:email, :string)
    field(:name, :string)
    field(:roles, list_of(:role))
  end

  enum(:role, values: [:admin, :overseer, :analyst, :data_scientist])
```

Not being experienced with absinthe I try a mutation like the following

```
mutation { inviteUser(email: "some@example.com", name: "Person", roles: ["ADMIN"]) {
  id
}}
```

That is incorrect, since `ADMIN` should not be in quotes `""`, and will fail with message `"Argument \"roles\" has invalid value [\"ADMIN\"].\nIn element #1: Expected type \"Role\", found \"ADMIN\"."` 

Maybe a clearer message could be written for this situation. Telling me what I typed and what are the available roles I should have written.

**Comment by benwilson512** [comment]
@vasspilka in general Absinthe sticks with the error messages from the reference implementation. As far as I know this is what the reference implementation has.
