### ISSUE TITLE
Allow returning data and errors from a resolver

### ISSUE THREAD

**Issue by drewolson** [absinthe-graphql/absinthe#512]
I've been working with graphql-java lately and they offer a nice feature that allows returning data _and_ errors from a resolver. You can see the implementation [here](https://github.com/graphql-java/graphql-java/blob/24691c2685cecdb72d891599294361bbca6d38e1/src/main/java/graphql/execution/DataFetcherResult.java).

What would your thoughts be about adding something equivalent in absinthe? I could see this being very useful in resolvers that compose data from different backing services that can succeed or fail independently.

I'm thinking something like:

```elixir
{:result, data, error}
{:result, data, [error1, error2]}
```

I'm unsure about the name `:result` but I do think a capability like this would be useful. If you agree, I'd be willing to try to PR something.

Thanks.

**Comment by benwilson512** [comment]
The specification is pretty clear about this: http://facebook.github.io/graphql/October2016/#sec-Errors-and-Non-Nullability

> If an error is thrown while resolving a field, it should be treated as though the field returned null, and an error must be added to the "errors" list in the response.

There's been a pretty reasonable analogy between raising a graphql error and raising an exception. Functions can raise an exception OR return successfully, but not both. If you want to return error information as well as result information the general convention is to have a specific object type that composes both.

**Comment by drewolson** [comment]
Interestingly, this same discussion came up there in regards to allowing multiple errors for a single path (which absinthe allows, correct?). I struggle to understand if this section of the spec is meant to apply only to non-nullable fields or to all fields. 

If you are indeed reading this section all applicable to all errors, why the choice to allow multiple errors for a given field and path?

**Comment by benwilson512** [comment]
Well so a more complete chunk of that spec reads:

> If an error is thrown while resolving a field, it should be treated as though the field returned null, and an error must be added to the "errors" list in the response.

> If the result of resolving a field is null (either because the function to resolve the field returned null or because an error occurred), and that field is of a Non-Null type, then a field error is thrown. The error must be added to the "errors" list in the response.

The second clause there handles "if the result is null and the field is non null". The only antecedent to the first clause is "if an error is thrown". If the "non null type" bit was implied then it would be very weird to mention it in the second clause but leave it out in the first.

Multiple errors per path can happen a couple of ways, one of which is articulated there by the second clause. If you have some error A on a field that is non null, this raises a second error B for that same field. Thus we have two errors, the original one leading to the null result, then the second one for the violation of the null constraint.

**Comment by drewolson** [comment]
Fair enough, I can understand that reading of the spec.

I do wonder if this behavior was an explicit decision by the GraphQL team or an implicit consequence of the choice to use exceptions for errors in the reference implementation. I don't understand what is lost by allowing resolution to return both errors and data.

For what it's worth, graphql-ruby [also allows](https://gist.github.com/drewolson/f20f96ffb9ac19275d19102c447a4a1e) this behavior.

I'll go ahead and close this issue for now. Thanks for the detailed response.

**Comment by benwilson512** [comment]
> I do wonder if this behavior was an explicit decision by the GraphQL team or an implicit consequence of the choice to use exceptions for errors in the reference implementation.

A fair question. I don't think the changes required to Absinthe would be particularly significant to support both, but at the same time I am reluctant to make and then therefore have to support those changes without more clarity from the spec in that regard.

**Comment by gullitmiranda** [comment]
I trying to create a middleware with list of ok values and error values, but if I put a error in resolution, the valid data is override by `nil`.

```elixir
  # middleware
  @spec call(Absinthe.Resolution.t(), term) :: Absinthe.Resolution.t()
  def call(%{state: :unresolved} = res, _opts) do
    %{success: value, errors: errors} = parse_results(res)
    errors = translate_errors(errors)

    %{res | state: :resolved}
    |> Resolution.put_result({:ok, value})
    |> Resolution.put_result({:error, errors})
  end

  # mutation field 
        field(:invites, list_of(:invite)) do
          middleware(HiveWeb.Schema.MultiResponse)
        end

  # result
{:ok,
 %{
   data: %{"createInvite" => %{"invites" => nil, "status" => "PARTIAL"}},
   errors: [
     %{
       errors: %{email: ["has invalid format"]},
       locations: [%{column: 0, line: 4}],
       message: "Input validation fails.",
       path: ["createInvite", "invites"]
     }
   ]
 }}
```

resulte expected
```elixir
{:ok,
 %{
   data: data: %{
                 "createInvite" => %{
                   "invites" => [
                     %{
                       "__typename" => "Invite",
                       "id" => "SW52aXRlOmU3MTZjOTdlLTc4ODEtNDhlOS04Y2I3LTIyY2IxN2Q4NmViOQ==",
                     }
                   ],
                   "status" => "PARTIAL"
                 }
               }
             },
   errors: [
     %{
       errors: %{email: ["has invalid format"]},
       locations: [%{column: 0, line: 4}],
       message: "Input validation fails.",
       path: ["createInvite", "invites"]
     }
   ]
 }}
```
is there a way to make this work? if so, how?

**Comment by benwilson512** [comment]
This is forbidden by the spec. If a field raises an error, then its return value is `nil`. Without a change in the spec this will not be possible.

**Comment by J3RN** [comment]
The latest version of the GraphQL specification (October 2021) removes the ambiguity present in the earlier (October 2016) version:

> Field errors are raised during execution from a particular field. This may occur due to an internal error during value resolution or failure to coerce the resulting value.
> 
> Field errors are typically the fault of GraphQL service.
> 
> **If a field error is raised, execution attempts to continue and a partial result is produced (see [Handling Field Errors](https://spec.graphql.org/October2021/#sec-Handling-Field-Errors)). The data entry in the response must be present. The errors entry should include all raised field errors.**

[Field errors](https://spec.graphql.org/October2021/#sec-Errors.Field-errors) (emphasis my own)

In sum: yes, returning both data and errors is both allowed and expected
