### ISSUE TITLE
Dataloader breaks in absinthe 1.4.7 => 1.4.8

### ISSUE THREAD

**Issue by jfrolich** [absinthe-graphql/absinthe#520]
The dataloader returns `nil` values that shouldn't be `nil`. It's late here so I will research it more thorough later, but the single change that reproduced the error is changing the version number of absinthe from 1.4.7 to 1.4.8.

**Comment by jfrolich** [comment]
I just confirmed the on_load functions received a dataloader with still pending batches.

**Comment by jfrolich** [comment]
It looks like https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/middleware/dataloader.ex#L18 is the culprit, a `pending_batches?` check should be enough.

**Comment by jfrolich** [comment]
#521

**Comment by benwilson512** [comment]
Merged.
