### ISSUE TITLE
Allow bare return values from resolvers

### ISSUE THREAD

**Issue by jfrolich** [absinthe-graphql/absinthe#527]
Currently if a resolver emits anything other than `{:ok, _}` or `{:error, _}` or *explicitly* calls middleware it will yield an error.

For some things we might want middleware to evaluate the value and decide wether it is `:ok` or an `:error`.

For instance %LazyLoader{}, where the `%Lazyloader{}` struct contains information what needs to be fetched from the database, so the middleware can efficiently query this (given other values).

I think the only thing that needs to happen is to raise errors on the expected value after the middle ware has executed. Or are there more complexities to this?

**Comment by benwilson512** [comment]
If the resolver doesn't return anything, then the %Resolution{} struct will be identical before and after the resolver, so what does the resolver even do?

**Comment by benwilson512** [comment]
Maybe I'm misunderstanding the proposal. Can you show some examples of resolvers or middleware that exhibit these characteristics

**Comment by jfrolich** [comment]
Some intermediate value that the middleware processes and converts to {:ok, val} or {:error, val}

**Comment by jfrolich** [comment]
This is not possible now because a resolver has to return {:ok, val} {:error, val}

**Comment by benwilson512** [comment]
I think there's confusion about how resolvers work. When you do 
```
resolver fn _, _, _ -> {:ok, "hello"} end
```

This compiles to

```
middleware Absinthe.Resolution, fn _, _ , _-> {:ok, "hello"} end
```

With that in mind, let's play out the scenario you have in mind.

The Absinthe.Resolution middleware has a `call/2` function per the Middleware behaviour:

```
def call(resolution, fun) do
  # simplified
  case fun.(resolution.source, resolution.arguments, resolution) do
    {:ok, value} ->
      %{resolution | state: :resolved, value: value}
    {:error, errors} ->
      %{resolution | state: :resolved, errors: errors}
    {:middleware, mfa} ->
      %{resolution | middleware: [mfa | resolution.middleware]}
  
    # if you want to support this
    value ->
      #what do you do here?
  end
end
```

The `call/2` function is passed a resolution struct as well as the resolver function, and per the `Absinthe.Middleware` contract it the `call/2` function needs to return a resolution struct. In the `:ok, :error, :middleware` tagged tuples there's a clear way to update the resolution struct so as to move foward.

If `result` can be any value, what should it do?

**Comment by jfrolich** [comment]
Good point. I guess it can be put in a different field (not sure about the name). With a check after middleware that this field is removed and nullified by the middleware? This makes it really explicit, but still a scenario that middleware modules can utilize.

Another approach is put the catch-all value in value (same as if it returned `{:ok, value}`). Middleware can then pattern match on the values they'd like to modify (and add an error if necessary).

I also often forget to return `{:ok, value}`, and just return `value`, arguably a good default/shorthand.
