### ISSUE TITLE
Ecto Best Practices guide has a missing reference or link

### ISSUE THREAD

**Issue by milmazz** [absinthe-graphql/absinthe#531]
Reading through the _Ecto Best Practices_ guide you will find the following paragraphs:

>The plugins/0 function has been around for a while, and specifies what plugins the schema needs to resolve. See more here:
>
>That's it! If you run a GraphQL query that hits that field, it will be loaded efficiently without N+1.

The first paragraph seems to have a missing reference or link after the _See more here:_ sentence.

**Comment by steffkes** [comment]
@benwilson512  since #548 is already merged, i'd guess this issue could be closed as well?
