### ISSUE TITLE
Schema validation is not performed when changing child schema and multiple modules syntax is used to import it

### ISSUE THREAD

**Issue by azhi** [absinthe-graphql/absinthe#535]
### Environment

* Elixir version (elixir -v): Elixir 1.6.2 (compiled with OTP 20)
* Absinthe version (mix deps | grep absinthe): * absinthe 1.5.0-dev (../../absinthe) (mix) (current HEAD, a0e2bbf)
* Client Framework and version (Relay, Apollo, etc): -

### Expected behavior

Compilation fails with error when schema is invalid

### Actual behavior

Compilation can be successful even when schema is invalid.

### Relevant Schema/Middleware Code

lib/schema.ex:
```elixir
defmodule App.Schema do
  use Absinthe.Schema

  import_types(App.A)
  import_types(App.{B, C})

  query do
    import_fields :a_queries
    import_fields :b_queries
    import_fields :c_queries
  end
end
```

lib/a.ex:
```elixir
defmodule App.A do
  use Absinthe.Schema.Notation
  object :a_queries do
    field :a, :integer do
      resolve fn _, _ -> {:ok, 1} end
    end
  end
end
```

lib/b.ex:
```elixir
defmodule App.B do
  use Absinthe.Schema.Notation
  object :b_queries do
    field :b, :integer do
      resolve fn _, _ -> {:ok, 2} end
    end
  end
end
```

lib/c.ex:
```elixir
defmodule App.C do
  use Absinthe.Schema.Notation
  object :c_queries do
    field :c, :integer do
      resolve fn _, _ -> {:ok, 3} end
    end
  end
end
```

Run `mix compile`, it will compile the schema with no issues (expected behavior for now).

Now change lib/c.ex to:
```elixir
defmodule App.C do
  use Absinthe.Schema.Notation
  object :c_queries do
    field :c, :integer do
      resolve fn _, _ -> {:ok, 3} end
    end
  end

  # duplicate object!
  object :b_queries do
    field :b, :integer do
      resolve fn _, _ -> {:ok, 5} end
    end
  end  
end
```

Run `mix compile`, it will successfully recompile only `lib/c.ex` -  not expected behavior.
Running `mix compile --force` will obviously yield an error.

**Comment by azhi** [comment]
The cause of the issue is how Absinthe deals with input AST in `Absinthe.Schema.Notation.import_types/1` macro.

When passing a module to this macro, it goes through `Macro.expand/2`, thus making it a compile-time dependency, which can be confirmed by `mix xref`:
```
$ mix xref graph --source lib/schema.ex
lib/a.ex (compile)
lib/app.ex (compile)
```

But when dealing with multiple modules syntax, it does a few `Module.concat`s manually, not creating a compile-time dependency.

I'll submit a PR momentarily that will fix this by doing `Macro.expand/2` on each of importing modules, thus creating compile-time dependencies on all children schemas:
```
$ mix xref graph --source lib/schema.ex
lib/a.ex (compile)
lib/app.ex (compile)
lib/b.ex (compile)
lib/c.ex (compile)
```

**Comment by soteras** [comment]
Hello :D 

I want to start help in this project. Is it possible set flags of level on each issue?
