### ISSUE TITLE
Wrong list of fields returned in common subfield of a union type

### ISSUE THREAD

**Issue by amcvitty** [absinthe-graphql/absinthe#546]
### Environment

* Elixir version (elixir -v): 1.6.0
* Absinthe version (mix deps | grep absinthe): 1.4.12
* Client Framework and version (Relay, Apollo, etc): n/a

### Expected behavior

When using fragments to select fields in a union type, I expect that the set of fields on the fragment for that type will be selected, even when both of the union subtypes have a field with the same name and type.

### Actual behavior

I reproduced the issue with a test repo based on the plate_slate example. This is the failing test. Both  MenuItem and Category have an addedBy field, which is of User type. However, it's not possible to select different fields from the User type. The field set from the first fragment is used for both MenuItem and Category. So the `title` field is missing from the result for the Category.

Curiously, renaming the field in one fragment makes it work.

https://github.com/amcvitty/absinthe-union-types/blob/master/test/plate_slate_web/schema/query/demonstrate_union_issue_test.exs:
```

  @query """
  query{
    search(matching: "an") {
      ... on MenuItem {
        id
        addedBy {
          name
        }
      }
      ... on Category {
        name
        description
        addedBy {
          name
          title
        }
      }
      __typename
    }
  }
  """
  test "search across union types with a common object subfield doesn't select all the fields" do
    response = get(build_conn(), "/api", query: @query)

    assert %{
             "data" => %{
               "search" => [
                 %{
                   "__typename" => "MenuItem",
                   "addedBy" => %{"name" => "Andy"},
                   "id" => _
                 },
                 %{
                   "__typename" => "Category",
                   # Here's the problem - the title here is missing from this Category/addedBy field
                   "addedBy" => %{"name" => "Andy", "title" => "Janitor"},
                   "description" => nil,
                   "name" => "Sandwiches"
                 }
               ]
             }
           } = json_response(response, 200)
  end
```

### Relevant Schema/Middleware Code

See example repo. I based the repo on the plateslate example 04-chp.flexibility/2-unions from this book https://pragprog.com/book/wwgraphql/craft-graphql-apis-in-elixir-with-absinthe

I added the "addedBy" field and the User type

    git clone https://github.com/amcvitty/absinthe-union-types
    mix deps.get
    mix ecto.create
    mix ecto.migrate
    mix test

**Comment by benwilson512** [comment]
Update: I've reproduced this, the issue is with the projection cache. If I disable the cache and have it compute the fields every time it gets the right answer. The cache introduces an error because it only uses the parent type + the path, as opposed to the stack of all parent types. We may need to alter how path information is stored.

**Comment by amcvitty** [comment]
Thanks Ben! 

🙏
