### ISSUE TITLE
wrong status code when schema parse error

### ISSUE THREAD

**Issue by mydearxym** [absinthe-graphql/absinthe#554]
### Environment

* Elixir version : 1.6.4
* Absinthe version : 1.4.2
* Client Framework and version: Apollo-client (latest)

### Expected behavior

should return a 200 status code with error filed contains parse error infos

### Actual behavior
when i query with missing arg, the server return a 400 status code, which cause graphql-client treat this as `Network-Error` instead of `GraphQL-Parse-Error` 

![image](https://user-images.githubusercontent.com/6184465/40285832-4c1cd444-5cd3-11e8-836f-9d08fac127e8.png)

a 400 status code is returned
![image](https://user-images.githubusercontent.com/6184465/40285907-fb4e6bb2-5cd3-11e8-924f-29c0fa5d173b.png)

### Relevant Schema/Middleware Code

```elixir
.... 
field :github_signin, :token_info do
   arg(:code, non_null(:string))
     
   resolve(&Resolvers.Accounts.github_signin/3)
end
....
```

**Comment by benwilson512** [comment]
The 400 status code was definitely what the spec required at some point in the past, but I haven't looked lately. Let me see if I can find the relevant bit.

**Comment by mydearxym** [comment]
thanks @benwilson512,  but i don't think there is relevant bit in the spec . 

quote from [this issue](https://github.com/graphql-python/graphene/issues/142)  
> As far as I can tell from the GraphQL spec there is no discussion of http response codes at all. The status codes of HTTP are strongly tied to rest principles. It's not clear to me whether GraphQL APIs should distinguish between 2XX and 4XX status codes.

> Most notably, you can batch multiple mutations into the same request to the server. If one successfully creates a resource (201), one mutates a resource (200), one fails validation (400) and another the target object does not exists (404), what should the return value from the API be?

> At the moment, GraphQL APIs seem to err on the side of 200 unless the server blows up, in which case 500.

related issue: [GraphiQL expects 200 status for errors](https://github.com/graphql/graphiql/issues/88)

**Comment by hubertlepicki** [comment]
I have created a PR to resolve that... but I am not 100% convinced what we should be doing here.

I am leaning towards returning 200 OK unless the server blows up, mostly because of good point above about batch mutations.

**Comment by mydearxym** [comment]
your thought about HTTP make sence,  but currently return 200 is best for the front-end tooling. what you think ? @benwilson512 @bruce

**Comment by benwilson512** [comment]
Will review the plug PR. Technically this is just a plug issue since Absinthe doesn't know anything about status codes, so closing this for now.
