### ISSUE TITLE
Allowed arbitrary type definition when passing vars in testing

### ISSUE THREAD

**Issue by lobo-tuerto** [absinthe-graphql/absinthe#555]
### Environment

* Elixir version (elixir -v): 1.6.4
* Absinthe version (mix deps | grep absinthe): 1.4.12
* Testing Framework: ExUnit

### Expected behavior

I expected to see an error complaining about the incorrect type being supplied.

### Actual behavior

The following piece of code is running without problems:

```elixir
@query """
query ($filter: Boolean) {
  users(filter: $filter) {
    email
  }
}
"""
@variables %{filter: %{email: "admin"}}
test "users field returns a list of users filtered by email, using a variable" do
  conn = post(build_conn(), "/api", query: @query, variables: @variables)

  assert json_response(conn, 200) == %{
           "data" => %{
             "users" => [
               %{"email" => "admin@email.com"}
             ]
           }
         }
end
```

Note that:

```elixir
query ($filter: Boolean) {
```

Should be:

```elixir
query ($filter: UserFilter) {
```

It seems to be working with whatever type you pass to it, as long as the type exists.
If the type doesn't exist it complains accordingly.

### Relevant Schema/Middleware Code

```elixir
input_object :user_filter do
  field(:name, :string)
  field(:email, :string)
  field(:is_active, :boolean)
  field(:type, :user_type)
end

field :users, list_of(:user) do
  arg(:filter, :user_filter)
  # ...
```

**Comment by lobo-tuerto** [comment]
Just tried it out in GraphiQL and it also works without problems.

Although I get a red line that indicates there is a problem with the type, but the query succeeds nonetheless.

![screenshot-2018-5-28 graphiql](https://user-images.githubusercontent.com/5730/40599376-7a0a103a-6212-11e8-98d8-257fdbffe2b0.png)

**Comment by benwilson512** [comment]
Not entirely sure when this was fixed, but I just added a test case to master showing that this issue seems to be fixed. https://github.com/absinthe-graphql/absinthe/commit/392426bd550fc65b4b0304d01813229ac4daaba6
