### ISSUE TITLE
Pattern arg_<int> for query/mutation arguments cause a invalid param error

### ISSUE THREAD

**Issue by Matsa59** [absinthe-graphql/absinthe#560]
### Environment

* Elixir version (elixir -v): 1.6.5
* Absinthe version (mix deps | grep absinthe): 1.4.2
* Client Framework and version (Relay, Apollo, etc): GraphQL request directly / graphiql

### Expected behavior

Arg that have the following pattern `arg_<int>`  should be transform to `arg<int>` for backend (like graphiQL).

### Actual behavior

Using an arg with the following pattern `arg_<int>` display `arg<int>` on graphiql. Requesting with the `arg<int>` pattern cause an error.

### Relevant Schema/Middleware Code

Object definition:
```elixir
defmodule BlogWeb.Schema.ContentTypes do
  use Absinthe.Schema.Notation

  object :post do
    field :id, :id
    field :title, :string
    field :body, :string
  end
end
```

Schema:
```elixir
defmodule BlogWeb.Schema do
  use Absinthe.Schema
  import_types BlogWeb.Schema.ContentTypes

  alias BlogWeb.Resolvers

  query do

    @desc "Get all posts"
    field :posts, list_of(:post) do
      arg :my_arg_2, :string
      resolve &Resolvers.Content.list_posts/3
    end
  end
end
```

On graphiQL you can write the following request :

```
query {
    posts(myArg2: "Example") {
        id
    }
}
```

But if you execute it you will have the following error from absinthe that tell you `In field \"myArg2\": Unknown field.`

EDIT : like https://github.com/absinthe-graphql/absinthe/issues/298 in some way

**Comment by benwilson512** [comment]
Indeed this is basically a dup of #298, your field names need to always work as

```
field == field |> Macro.camelize |> Macro.underscore
```

In this case:
```
"myArg2" |> Macro.underscore
"my_arg2"
```
