### ISSUE TITLE
Standalone GraphQL Playground

### ISSUE THREAD

**Issue by ChuckIrvine** [absinthe-graphql/absinthe#568]
Is it possible for me to use my locally deployed instance of graphql-playground with Absinthe? I tried pointing GraphQL Playground to  http://localhost:4000/graphiql and that didn't work. Thanks

**Comment by benwilson512** [comment]
You'd need to point it at `/graphql` not `graphiql`. Do note that subscriptions will not work since the locally deployed version won't be using the correct JS libraries. As a general note, let's try to direct "how to" style questions for the forum / slack.
