### ISSUE TITLE
Cache of query

### ISSUE THREAD

**Issue by jhonathas** [absinthe-graphql/absinthe#571]
Look how interesting, do we have something?

https://dev-blog.apollodata.com/automatic-persisted-queries-and-cdn-caching-with-apollo-server-2-0-bf42b3a313de

**Comment by benwilson512** [comment]
Hey @jhonathas, Absinthe does have https://hexdocs.pm/absinthe_plug/Absinthe.Plug.DocumentProvider.html#content which provides some measure of these features. Please follow up on the forums on slack, the issue tracker is not for questions.
