### ISSUE TITLE
Document execution fails for a Field with a `:name` attribute

### ISSUE THREAD

**Issue by easco** [absinthe-graphql/absinthe#574]
### Environment

* Elixir version (elixir -v):  

Elixir 1.6.6 (compiled with OTP 21)

* Absinthe version (mix deps | grep absinthe):

  absinthe 1.4.12 (Hex package) (mix)
  locked at 1.4.12 (absinthe) 50e7a700

* Client Framework and version (Relay, Apollo, etc):

None (direct call to Absinthe.run)

### Expected behavior

I created a field with a `:name` attribute.  I expected to see that name in the documentation for the field (which I did). I also expected that I could use that name in a query document and have it recognized as the name of the field.

### Actual behavior

When running a document that uses the field name in the correct spot, I receive an error like this:

    %{errors: [%{locations: [%{column: 0, line: 1}], message: "Cannot query field \"randomName\" on type \"RootQueryType\". Did you mean \"randomName\"?"}]}}

Note that the field name it told me it couldn't query ("randomName" in this case) is exactly the same as the field name it suggested.

If I don't provide a name and allow the system to generate the field's name from its field ID then parsing the document proceeds as expected

### Relevant Schema/Middleware Code

The following is an ExUnit test case that demonstrates the problem in a project that is built with Absinthe 1.4.12:

    defmodule AbsintheNameTest do
      use ExUnit.Case

      test "schema without name attribute" do
        defmodule UnnamedFieldSchema do
          use Absinthe.Schema

          query do
            field :check_my_pulse, :string do
              resolve(fn (_,_) -> {:ok, "Happy Day!"} end)
            end
          end
        end

        assert {:ok, %{data: %{"checkMyPulse" => "Happy Day!"}}} ==
          Absinthe.run("{ checkMyPulse }", UnnamedFieldSchema)
      end

      test "schema with name attribute" do
        defmodule NamedFieldSchema do
          use Absinthe.Schema

          query do
            field :check_my_pulse, :string, name: "randomName" do
              resolve(fn (_,_) -> {:ok, "Happy Day!"} end)
            end
          end
        end

        assert {:ok, %{data: %{"randomName" => "Happy Day!"}}} ==
          Absinthe.run("{ randomName }", NamedFieldSchema)
      end

      test "try to game the system" do
        defmodule GamesWithCapitalsSchema do
          use Absinthe.Schema

          query do
            field :do_the_aPI, :string do
              resolve(fn (_,_) -> {:ok, "Happy Day!"} end)
            end
          end
        end

        assert {:ok, %{data: %{"doTheAPI" => "Happy Day!"}}} ==
          Absinthe.run("{ doTheAPI }", GamesWithCapitalsSchema)
      end
    end

In the first test case I create a schema whose only query field (:check_my_pulse) does not include a "name:" option.  In the second test the schema should be identical except for the addition of a "name:" option.

In the last test case, I try to game the system with a field ID of `:do_the_aPI` with the intent that the field name in documentation and documents would be `doTheAPI` (with API in all caps).  This also fails to work and gives the error:

    %{errors: [%{locations: [%{column: 0, line: 1}], message: "Cannot query field \"doTheAPI\" on type \"RootQueryType\". Did you mean \"doTheAPI\"?"}]}

Where the suggested name and actual name match.

**Comment by maartenvanvliet** [comment]
Related to this issue: https://github.com/absinthe-graphql/absinthe/issues/298

I think you have to snake_case the name attribute
```
      query do
        field :check_my_pulse, :string, name: "random_name" do
          resolve(fn (_,_) -> {:ok, "Happy Day!"} end)
        end
      end
```

**Comment by benwilson512** [comment]
@maartenvanvliet is correct, the `name` attribute is still used by the adapter, so it should still be snake case.
