### ISSUE TITLE
Middlewares not called for subscriptions

### ISSUE THREAD

**Issue by mpoeter** [absinthe-graphql/absinthe#583]
### Environment

* Elixir version: 1.5.1
* Absinthe version: 1.4.12

I have several queries, mutations and subscriptions, and I have added some middleware to be executed _before_ the resolver. This works fine for the queries and mutations, but not for the subscriptions.

After a brief look at the Absinthe code, I found that the pipeline contains the following phases:
```Elixir
      # Execution
      {Phase.Subscription.SubscribeSelf, options},
      {Phase.Document.Execution.Resolution, options},
```
The middleware is called as part of `Phase.Document.Execution.Resolution`, but the subscription is already called in `Phase.Subscription.SubscribeSelf`.

Is this a bug or was this a deliberate design decision and if so, what was the reason for it?

### Expected behavior
Middlewares are called for subscriptions.

### Actual behavior
No middlewares are called for subscriptions.

**Comment by benwilson512** [comment]
Middleware are indeed called for subscriptions, but they're called when the subscription documents are run, not when they're setup. Middleware are run as part of the resolution phase, and the resolution phase is run when actually resolving a document, which doesn't happen until there's an event published with which to run subscriptions.

**Comment by mpoeter** [comment]
Oh, ok. That was a misinterpretation from my side.

Are there other ways to run custom code before the subscription is set up (i.e., before the call to `config`)? We are currently using middlewares to run perform gather some additional data for authenticated users. We would need this data in the call to `config` to verify if the user is actually allowed to subscribe to a certain event or not. How could we do this?

**Comment by benwilson512** [comment]
The standard option at the moment is to do this check inside the config call, since it has access to the context:

```
config fn args, %{context: context} ->
  if authorized?(context.current_user, :subscribe) do
    {:ok, topic: "foo"}
  else
    {:error, "unauthorized"}
  end
end
```

For what it's worth I do hope to come up with a solution that enables middleware to do this but it's challenging, since the runtime characteristics are very different. In the meantime you ought to be able to handle it via `config`.

**Comment by mpoeter** [comment]
Alright, thank you!

**Comment by RodolfoSilva** [comment]
> The standard option at the moment is to do this check inside the config call, since it has access to the context:
> 
> ```
> config fn args, %{context: context} ->
>   if authorized?(context.current_user, :subscribe) do
>     {:ok, topic: "foo"}
>   else
>     {:error, "unauthorized"}
>   end
> end
> ```
> 
> For what it's worth I do hope to come up with a solution that enables middleware to do this but it's challenging, since the runtime characteristics are very different. In the meantime you ought to be able to handle it via `config`.

Hi @benwilson512, have you discovered a better solution to this?
