### ISSUE TITLE
Adapter setting in config.exs is ignored

### ISSUE THREAD

**Issue by 1player** [absinthe-graphql/absinthe#587]
The documentation states that the default adapter can be configured in the application environment, quote from https://hexdocs.pm/absinthe/Absinthe.Adapter.html:

```
To set an adapter, you can set an application configuration value:

config :absinthe,
  adapter: YourApp.Adapter.TheAdapterName
```

But this configuration setting seems to be ignored at the moment.

Also, absinthe_plug should pull this configuration option if set. I'll open a bug report on that project too.

**Comment by benwilson512** [comment]
PR welcome.

**Comment by benwilson512** [comment]
In the end we're simply removing that example from the docs. Adapters work great as an argument passed to each call site, and minimizing Absinthe wide singleton config like that is definitely the way we want to go.
