### ISSUE TITLE
Pass on the context with the dataloader helper

### ISSUE THREAD

**Issue by ishitatsuyuki** [absinthe-graphql/absinthe#591]
The current [`dataloader`](https://github.com/absinthe-graphql/absinthe/blob/a3dbc29640d613928398626ad75a8f03203a1720/lib/absinthe/resolution/helpers.ex#L136) helper discards the context (by extracting the loader out) before the `query` function get access to it.

Context information like the current user is commonly useful during query, and there's no reason why we are not passing it on.

**Comment by benwilson512** [comment]
Can you elaborate on what should be different here? The `&query/2` function can get access to whatever you want in the context by passing it in when you create the source.

**Comment by ishitatsuyuki** [comment]
I originally thought that it maybe useful to automatically have some context passed  to the source, but now I see that such work should be done in the key_fun instead.
