### ISSUE TITLE
Absinthe hangs indefinitely when an interface returns itself in a field

### ISSUE THREAD

**Issue by kenips** [absinthe-graphql/absinthe#597]
I mentioned this to @benwilson512 on Slack a month or so and I totally forgot about this. Here's a [commit](https://github.com/kenips/absinthe/commit/f3ed6490d3f595e414d9a46272ce90c9374d35d6) demonstrating the infinite hangs. I am not sure if an interface _can_ define a field that returns itself, but I stumble upon it when I simply wanted all of the implementations to support returning their parents.

### Steps to reproduce
Take the patch from the commit above, then run `mix test test/absinthe/resolution_test.exs`.

### Environment
* Elixir version (elixir -v): 1.7
* Absinthe version (mix deps | grep absinthe): master
* Client Framework and version (Relay, Apollo, etc):

### Expected behavior
If this is supported, then expecting this to work. If not supported, expecting an error message.

### Actual behavior
Hangs indefinitely at compile time. Maybe infinite macro expansion. Curious what it is myself...

### Relevant Schema/Middleware Code
N/A

**Comment by binaryseed** [comment]
If these situations are intended to pass validation, I've got a PR that should clean this up: https://github.com/absinthe-graphql/absinthe/pull/819
