### ISSUE TITLE
Absinthe does not validate types on the way out

### ISSUE THREAD

**Issue by samphilipd** [absinthe-graphql/absinthe#603]
If submitting a bug, please provide the following:

### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.7.1 (compiled with Erlang/OTP 21)
```

* Absinthe version (mix deps | grep absinthe):

```
* absinthe 1.4.13 (Hex package) (mix)
  locked at 1.4.13 (absinthe) 81eb2ff4
* absinthe_metrics 0.9.0 (Hex package) (mix)
  locked at 0.9.0 (absinthe_metrics) 59b608f6
* absinthe_plug 1.4.5 (Hex package) (mix)
  locked at 1.4.5 (absinthe_plug) f63d52a7
* absinthe_phoenix 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (absinthe_phoenix) cea34e7e
```

* Client Framework and version (Relay, Apollo, etc):

N/A.

### Expected behavior

If I define a field type as `:integer` and send out a string, I would expect to see a runtime error.

### Actual behavior

Absinthe sends a string even though this is not allowed by the GraphQL schema.

**Comment by gen1321** [comment]
I agree, but what to we should do with more custom scalars. like an `:upload` or custom one like `:address`. My guess on that is: We should add a third function to `scalar` macro. like  `check(value)` so when it false it raises exception.

**Comment by lucaspolonio** [comment]
@gen1321 regarding custom scalars, Absinthe could require a `coerce_result` function similar to `graphql-ruby`'s implementation: http://graphql-ruby.org/type_definitions/scalars.html#custom-scalars

**Comment by halostatue** [comment]
GraphQL-Ruby’s `coerce_result` is the same as Absinthe’s `serialize`, and custom scalars can be as strict as is wanted there (although it might be better if custom scalar `parse` and `serialize` functions could return error tuples, not just `:error`).
