### ISSUE TITLE
Schema Notation bugs

### ISSUE THREAD

**Issue by benwilson512** [absinthe-graphql/absinthe#609]
General list of bugs folks are reporting on the new system:

- [x] ** (BadMapError) expected a map, got: []
     stacktrace:
       (elixir) lib/map.ex:391: Map.take/2
       (absinthe) lib/absinthe/subscription.ex:92: Absinthe.Subscription.get_subscription_fields/1
       (absinthe) lib/absinthe/subscription.ex:77: Absinthe.Subscription.publish/3
       (absinthe) lib/absinthe/subscription.ex:154: Absinthe.Subscription.call/2 
- [x] import_types Foo.{Bar, Baz} is allegedly broken

**Comment by bruce** [comment]
@benwilson512 RE `import_types`, I guess we're not testing using this: https://github.com/absinthe-graphql/absinthe/blob/01be95b540c3a2a4419fd2e8b117ef1f9eb8a569/test/support/fixtures/dynamic/import_types.ex#L83
