### ISSUE TITLE
import_types error doesn't throw error, but causes ambiguous errors for app

### ISSUE THREAD

**Issue by njwest** [absinthe-graphql/absinthe#610]
### Environment

* Elixir version (elixir -v): 1.7.3
* Phoenix version: 1.3.0
* Absinthe version (mix deps | grep absinthe): 1.4.13
* AbsinthePlug version: 1.4.5
* AbsintheEcto version: 0.1.3
* Client Framework and version (Relay, Apollo, etc): This problem does not relate to frontend clients 

### Expected behavior

When there is an  error with `import_types` in AppName.Schema (schema.ex, Absinthe.Schema), throw error regarding the problem in schema.ex. 

### Actual behavior

When there is an error in schema.ex (Absinthe.Schema), such as an import failure (attempting to import a module that doesn't exist, such as `import_types MyApp.Schema.NonexistentType`), the error that Elixir throws is: 

```elixir
** (CompileError) lib/app_name_web/views/error_view.ex:2: module AppNameWeb.Router.Helpers is not loaded and could not be found
    expanding macro: AppNameWeb.__using__/1
    lib/app_name_web/views/error_view.ex:2: AppNameWeb.ErrorView (module)
    (elixir) expanding macro: Kernel.use/2
    lib/app_name_web/views/error_view.ex:2: AppNameWeb.ErrorView (module)
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

### Notes

Fixed this error for my own app after finding [this StackOverflow error answer (the very last, least-upvoted answer)](https://stackoverflow.com/questions/40561203/module-myapp-router-helpers-is-not-loaded-and-could-not-be-found)

Unless I am missing something, this is a schema import error that is not caught by Absinthe that then creates ambiguous/misleading errors for Phoenix/Elixir

Not sure how to remedy this by adding error checking in Absinthe (am still Absinthe noob), but would try to if I could :P

**Comment by benwilson512** [comment]
This is definitely a weird situation. Technically, this is happening precisely _because_ of the error checking that happens in Absinthe. Basically, the schema tries to compile, but errors. This in turn prevents your router from compiling, because by routing to `Absinthe.Plug` there's now a dependency on the schema. With the router not compiling there's no helpers, and with no helpers it finally blows up where you see it.

I'm not entirely sure how to fix this, because I'm not sure why the Absinthe errors aren't showing up sooner and it's  bubbling up where it is. I need to investigate further. If you have the time to build a minimally representative example that would be immensely helpful.

**Comment by njwest** [comment]
Thank you for the response @benwilson512 , will commit an example project when I get a moment

**Comment by njwest** [comment]
Hiya @benwilson512 , just created an example Phoenix API repo that contains the error, documented in its Readme.md: https://github.com/njwest/AbsintheExample

**Comment by elbow-jason** [comment]
I just experienced this error. I forgot to `alias` the module for a struct that was used in a function of my Schema module.  Super confusing.

**Comment by elbow-jason** [comment]
I have an app named `service_discovery`.

I was able to change the error that was thrown to something more useful by putting `require ServiceDiscovery.Schema` into my `ServiceDiscoveryWeb` module. 

The top of my `service_discovery_web.ex` file:

```elixir
defmodule ServiceDiscoveryWeb do
  @moduledoc """
  ...docs here...
  """
  require ServiceDiscoveryWeb.Schema
```

My Schema module (with `Ecto.Changeset` not aliased to `Changeset`):
```elixir
defmodule ServiceDiscoveryWeb.Schema do
  use Absinthe.Schema
  import_types __MODULE__.ServiceTypes
  import_types __MODULE__.ServerTypes
  import_types __MODULE__.ServerStatusTypes
  import_types __MODULE__.KeyValue
#
  alias ServiceDiscoveryWeb.Resolvers

  query do

    @desc "Get all services"
    field :services, list_of(:service) do
      resolve &Resolvers.Service.list_services/3
    end
  end

  mutation do

    @desc "Create a service"
    field :create_service, type: :service do
      arg :name, non_null(:string)
      arg :permissions, :string
      arg :authentication, :string

      resolve fn _, args, _ ->
        args
        |> ServiceDiscovery.create_service()
        |> prepare_resolution()
      end
    end

  end

  defp prepare_resolution({:ok, _} = okay), do: okay
  defp prepare_resolution({:error, %Changeset{errors: errors}}), do: {:error, prepare_errors(errors)}

  defp prepare_errors(errors) when is_list(errors), do: Enum.map(errors, &prepare_error/1)

  defp prepare_error({key, {reason, meta}}) do
    %{
      message: "#{key} #{reason}",
      details: meta |> Enum.into(%{}) |> Map.merge(%{key: key, reason: reason})
    }
  end

end

```

The error that is produced:

```

== Compilation error in file lib/service_discovery_web/views/error_view.ex ==
** (CompileError)  deadlocked waiting on module ServiceDiscoveryWeb
    (elixir) src/elixir_dispatch.erl:207: :elixir_dispatch.expand_quoted/6
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6

== Compilation error in file lib/service_discovery_web/schema.ex ==
** (CompileError)  deadlocked waiting on struct Changeset
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
    lib/service_discovery_web/schema.ex:45: (module)
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6

== Compilation error in file lib/service_discovery_web/router.ex ==
** (CompileError)  deadlocked waiting on module ServiceDiscoveryWeb
    (elixir) src/elixir_dispatch.erl:207: :elixir_dispatch.expand_quoted/6
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6

== Compilation error in file lib/service_discovery_web/endpoint.ex ==
** (CompileError)  deadlocked waiting on module ServiceDiscoveryWeb.Router
    (plug) lib/plug/builder.ex:302: Plug.Builder.init_module_plug/4
    (plug) lib/plug/builder.ex:286: anonymous fn/5 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:284: Plug.Builder.compile/3
    (plug) lib/plug/builder.ex:140: Plug.Builder."MACRO-__before_compile__"/2
    (elixir) src/elixir_dispatch.erl:186: :elixir_dispatch.expand_macro_fun/6
    (elixir) src/elixir_dispatch.erl:171: :elixir_dispatch.expand_require/5
    (elixir) src/elixir_dispatch.erl:97: :elixir_dispatch.dispatch_require/6
    (stdlib) lists.erl:1263: :lists.foldl/3
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6

== Compilation error in file lib/service_discovery_web/controllers/page_controller.ex ==
** (CompileError)  deadlocked waiting on module ServiceDiscoveryWeb
    (elixir) src/elixir_dispatch.erl:207: :elixir_dispatch.expand_quoted/6
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6

== Compilation error in file lib/service_discovery_web.ex ==
** (CompileError)  deadlocked waiting on module ServiceDiscoveryWeb.Schema
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6

Compilation failed because of a deadlock between files.
The following files depended on the following modules:

             lib/service_discovery_web/views/error_view.ex => ServiceDiscoveryWeb
                       lib/service_discovery_web/schema.ex => Changeset
                       lib/service_discovery_web/router.ex => ServiceDiscoveryWeb
                     lib/service_discovery_web/endpoint.ex => ServiceDiscoveryWeb.Router
  lib/service_discovery_web/controllers/page_controller.ex => ServiceDiscoveryWeb
                              lib/service_discovery_web.ex => ServiceDiscoveryWeb.Schema

Ensure there are no compile-time dependencies between those files and that the modules they reference exist and are correctly named

```

This is obviously not a solution, but it at least gives a less cryptic error.

**Comment by benwilson512** [comment]
Yeah, I just don't understand why the errors from the schema aren't being raised. I'll look into it.

**Comment by benwilson512** [comment]
Will reopen if provided a modern example.
