### ISSUE TITLE
having access to connection in a resolver

### ISSUE THREAD

**Issue by jney** [absinthe-graphql/absinthe#613]
hello, i'd like to get a header inside one resolver. what's the way to go?
i know authorization is passed through a plug module, but i find a little a heavy to pass it to all resolvers because I only need in one resolver.

**Comment by benwilson512** [comment]
Hey,

The context is exactly the right place to put the header. Passing in the connection would be even heavier since now you'd have the connection in every resolver instead of just the header. If your concern about heaviness is performance then don't worry about it, it isn't any extra cost.
