### ISSUE TITLE
Absinthe.Subscription error when added on the supervisor

### ISSUE THREAD

**Issue by jhefreyzz** [absinthe-graphql/absinthe#617]
If submitting a bug, please provide the following:

### Environment

* Elixir version (elixir -v): Elixir 1.7.3
* Absinthe version (mix deps | grep absinthe): absinthe 1.4.13
* Client Framework and version (Relay, Apollo, etc): None

### Expected behavior

When adding the `{Absinthe.Subscription, [MyWeb.Endpoint]}` to supervisor  then run `mix phx.server`, will not return an error.
### Actual behavior
When adding the `{Absinthe.Subscription, [MyWeb.Endpoint]}` to supervisor  then run `mix phx.server`, will return an error.
```
The module Absinthe.Subscription was given as a child to a supervisor
but it does not implement child_spec/1.
```

**Comment by gen1321** [comment]
@jhefreyzz I wasn't able to reproduce issue with https://github.com/gen1321/absinthe_test_app and elixir 1.7.3. Can you push your code into repo?

**Comment by benwilson512** [comment]
This is handled in master now.
