### ISSUE TITLE
Bug with `desc("Description")` DSL?

### ISSUE THREAD

**Issue by azhi** [absinthe-graphql/absinthe#621]
### Environment

* Elixir version (elixir -v): Elixir 1.7.2 (compiled with Erlang/OTP 21)
* Absinthe version (mix deps | grep absinthe): * absinthe 1.5.0-alpha.0 (https://github.com/absinthe-graphql/absinthe.git) - current HEAD (d8b5797)
* Client Framework and version (Relay, Apollo, etc): -

### Expected behavior

Schema with `desc("Description")` DSL is compiled

### Actual behavior

Compilation fails with 

```
== Compilation error in file lib/schema.ex ==
** (CompileError) lib/schema.ex:5: undefined function desc/1
    expanding macro: Absinthe.Schema.Notation.object/2
    lib/schema.ex:4: App.Schema (module)
```

### Relevant Schema/Middleware Code

```elixir
defmodule App.Schema do
  use Absinthe.Schema

  object(:test) do
    desc("Description")
    field(:a, :string, resolve: fn _ -> {:ok, "a"} end)
  end

  query do
    field(:test, :test)
  end
end
```

I've checked CHANGELOG, it doesn't list this as a braking change. Is this a bug?

**Comment by gen1321** [comment]
@benwilson512 I don't think so.  as i understand that should be a `&description/1` instead of `&desc/1`. The difference between version 1.4 and 1.5 is that 1.4 just ignores it. Maybe we should create alias?

**Comment by benwilson512** [comment]
Ah yes that's correct. The supported options are `@desc "foo"` or `description("foo")`. The way 1.4 worked meant that it would ignore invalid function calls, which we no longer do.
