### ISSUE TITLE
enum value as: nil is silently ignored

### ISSUE THREAD

**Issue by olivermt** [absinthe-graphql/absinthe#632]
### Environment

* Elixir version (elixir -v): 1.7.2
* Absinthe version (mix deps | grep absinthe): 1.4
* Client Framework and version (Relay, Apollo, etc): apollo

### Expected behavior
```
enum :depositional_wiki_type do
    value(:gross_depositional_environment, as: "gross_depositional_environment")
    value(:depositional_environment, as: "depositional_environment")
    value(:depositional_sub_environment, as: "depositional_sub_environment")
    value(:architectural_element, as: "architectural_element")
    value(:not_set, as: nil)
  end
```` 

This ends up as "NOT_SET" string in changeset, not as nil.

**Comment by olivermt** [comment]
I was reading the wrong logger line... sorry!

**Comment by olivermt** [comment]
Actually disregard that, it does come in as NOT_SET, but the input object simply removes the field since the value is `as: nil`.

This is pretty strange behaviour, as it means we can never set enums to null.. is this intended or a bug?

**Comment by olivermt** [comment]
Just for brevitys sake, I have a (scrubber) plug that with some Logger use confirms it comes in as:

`"type" => "NOT_SET",`

Then in resolver when Logger printing the args the field is missing.

**Comment by benwilson512** [comment]
nil should really raise a schema error. The enum input should just be left
out or sent as null by the client.

**Comment by olivermt** [comment]
Hi!

I am sorry but I  don't understand what you mean.

With now GQL is specified at the moment you cant send nil as value for an enum, it will not pass apollo query validation in clientside. Setting the option value to "" or {null} (which turns into "" by apollo) is also getting blocked by absinthe schema wise.

Thats why I need to send NOT_SET which turns into nil, or I am not able to nil the field using ecto changesets.

I'm very open on instructions on how to nil an enum.

**Comment by benwilson512** [comment]
If an argument of any kind (enum, scalar, input object) is not marked as `non_null` within the schema, then the client can send `null` as the input, which will arrive in your resolver as `nil`.

```elixir
query do
  field :foo, :string do
    arg :input, :depositional_wiki_type
  end
end
```

```graphql
{
  foo(arg: null)
}
```

**Comment by olivermt** [comment]
Aha, well then I need to go raise an issue with apollo instead I guess, because setting a object key to `null` by explicitly looking for the "" the null <option> turns into scrubs the whole key from the variables.

Thanks for your time!

**Comment by benwilson512** [comment]
No problem! I'd double check your client version, apollo is usually pretty good about spec support so perhaps you're on a version that predates this spec change?
