### ISSUE TITLE
subscribe consume 100% os CPU

### ISSUE THREAD

**Issue by maxguzenski** [absinthe-graphql/absinthe#639]
### Environment

**Elixir version:**
Erlang/OTP 21 [erts-10.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.4 (compiled with Erlang/OTP 21)

**Absinthe version (mix deps | grep absinthe):**

* dataloader 1.0.4 (https://github.com/absinthe-graphql/dataloader.git) (mix)
* absinthe 1.4.13 (Hex package) (mix)
  locked at 1.4.13 (absinthe) 81eb2ff4
* absinthe_plug 1.4.6 (Hex package) (mix)
  locked at 1.4.6 (absinthe_plug) ac5d2d3d
* absinthe_phoenix 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (absinthe_phoenix) cea34e7e
* phoenix_pubsub 1.1.1 (Hex package) (mix)
  locked at 1.1.1 (phoenix_pubsub) 6668d787
* phoenix_html 2.12.0 (Hex package) (mix)
  locked at 2.12.0 (phoenix_html) 1fb3c2e4
* phoenix 1.4.0 (Hex package) (mix)
  locked at 1.4.0 (phoenix) 56fe9a80
* phoenix_live_reload 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (phoenix_live_reload) 3bb31a9f
* absinthe_phoenix 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (absinthe_phoenix) cea34e7e
* phoenix_ecto 4.0.0 (Hex package) (mix)
  locked at 4.0.0 (phoenix_ecto) c43117a1

**Client Framework and version (Relay, Apollo, etc):**
apollo, but graphql interface ("/graphql") can reproduce this issue as well.

### Actual behavior

I dont now how to debug this... but when I do a subscribe, then an unsubscribe and repeat this a couple of times, phoenix server just stop, beam.smp consume 100% of CPU.

this can be reproduced by graphql interface ... just write a subscribe and click in "play" 10x.

### Relevant Schema/Middleware Code

```elixir 
defmodule D4.Web.Schema.ThreadTypes do

  use D4.Web, :schema

  object :recipient do
    field :id, :id
    field :status, :integer
    field :unread_count, :integer
    field :received_at, :naive_datetime
    field :read_at, :naive_datetime
    field :deleted_at, :naive_datetime
    field :user_id, :integer
    field :user, :user, resolve: dataloader(:users)
  end

  object :message do
    field :id, :id, resolve: fn(m, _, _) -> {:ok, m.uuid || m.id} end
    field :text, :string
    field :created_at, :naive_datetime
    field :user_id, :integer
    field :user, :user, resolve: dataloader(:users)
  end

  object :thread do
    field :id, :id
    field :messages_count, :integer

    field :updated_at, :naive_datetime
    field :created_at, :naive_datetime

    field :recipients, list_of(:recipient) # resolve: dataloader(:recipients)
    field :last_message, :message, resolve: one_dataloader(:messages)

    field_page :messages, :message_page, first: 20 do
      resolve &list_messages/3
    end

    field :from, :recipient, resolve: fn thread, _, %{context: %{current_user: cuser}} ->
      thread.recipients
      |> Enum.find(fn r -> r.user_id != cuser.id end)
      |> get_ok
    end

    field :me, :recipient, resolve: fn thread, _, %{context: %{current_user: cuser}} ->
      thread.recipients
      |> Enum.find(fn r -> r.user_id == cuser.id end)
      |> get_ok
    end
  end

  object :thread_and_message do 
    field :thread, :thread 
    field :message, :message
  end

  object_page :message
  object_page :thread

  enum :thread_kind do
    value :inbox
    value :liked
    value :mutual
    value :unread
    value :archived
  end


  object :thread_queries do
    field_page :threads, :thread_page, first: 20 do
      arg :kind, :thread_kind, default_value: :inbox
      auth_resolve &list/3
    end

    field_page :messages, :message_page, first: 20 do
      arg :thread_id, :id
      auth_resolve &list_messages/3
    end

    field :thread, :thread do
      arg :id, :id
      arg :user_id, :id
      auth_resolve &get/3
    end
  end


  object_payload :thread
  object_payload :message

  object :thread_mutations do
    field :thread_read, :thread_payload do
      arg :id, non_null(:id)
      auth_resolve &read/3
    end

    field :thread_archive, :thread_payload do
      arg :id, non_null(:id)
      auth_resolve &archive/3
    end

    field :thread_delete, :thread_payload do
      arg :id, non_null(:id)
      auth_resolve &delete/3
    end

    # todo: mark thread as read!
    field :message_create, :message_payload do
      arg :thread_id, non_null(:id)
      arg :id, non_null(:id)
      arg :text, non_null(:string)
      auth_resolve &create_message/3
    end
  end



  object :thread_subscriptions do 
    field :on_thread_update, :thread do 
      arg :id, non_null(:id)

      config fn arg, info -> 
        {:ok, topic: arg.id}
      end

      trigger [:thread_read, :thread_achive, :thread_delete], topic: fn 
        %{ok: true, node: %D4.Thread{}=thread} -> ["#{thread.id}"]
        _ -> []
      end

      resolve fn %{node: %D4.Thread{}=thread}, _, _ -> 
        {:ok, thread}
      end
    end

    field :on_message_add, :message do 
      arg :thread_id, non_null(:id)

      config fn arg, info -> 
        {:ok, topic: arg.thread_id}
      end

      trigger [:message_create], topic: fn 
        %{ok: true, node: %D4.Message{}=message} -> [message.message_thread_id]
        _ -> []
      end

      resolve fn %{node: %D4.Message{}=message}, _, _ -> 
        {:ok, message}
      end
    end
  end



  @doc """
  """
  def get(_, %{id: id}, %{context: %{current_user: cuser}}) do
    id
    |> D4.Helpers.parse_int
    |> D4.Threads.get(cuser)
    |> get_ok
  end

  def get(_, %{user_id: uid}, %{context: %{current_user: cuser}}) do
    uid
    |> D4.Users.get!(cuser)
    |> D4.Threads.get_by_user(cuser)
    |> get_ok
  end

  @doc """
  """
  def list(_, params, %{context: %{current_user: cuser}}) do
    cuser
    |> D4.Threads.list(params)
    |> get_ok
  end

  @doc """
  """
  def list_messages(%D4.Thread{}=thread, params, %{context: %{current_user: cuser}}) do
    thread
    |> D4.Threads.list_messages(cuser, params)
    |> get_ok
  end

  def list_messages(_, %{thread_id: tid}=params, %{context: %{current_user: cuser}}) do
    tid
    |> D4.Threads.get!(cuser)
    |> D4.Threads.list_messages(cuser, params)
    |> get_ok
  end

  @doc """
  """
  def create(_, %{user_id: uid}, %{context: %{current_user: cuser}}) do
    uid 
    |> D4.Users.get!(cuser)
    |> D4.Threads.get_or_insert(cuser)
    |> get_payload
  end

  @doc """
  """
  def create_message(_, %{thread_id: tid, id: uuid, text: text}, %{context: %{current_user: cuser}}) do
    tid 
    |> D4.Threads.get!(cuser)
    |> D4.Threads.insert_message(cuser, %{uuid: uuid, text: text})
    |> get_payload
  end

  @doc """  
  """
  def delete(_, %{id: id}, %{context: %{current_user: cuser}}) do
    id
    |> D4.Threads.get!(cuser)
    |> D4.Threads.delete(cuser)
    |> get_payload 
  end

  @doc """  
  """
  def read(_, %{id: id}, %{context: %{current_user: cuser}}) do
    id
    |> D4.Threads.get!(cuser)
    |> D4.Threads.read(cuser)
    |> get_payload 
  end

  @doc """  
  """
  def archive(_, %{id: id}, %{context: %{current_user: cuser}}) do
    id
    |> D4.Threads.get!(cuser)
    |> D4.Threads.archive(cuser)
    |> get_payload 
  end
end
```

apollo link 
```js
const socket = new PhoenixSocket('/socket', { params: { token: window.cuserToken } })
const abssocket = AbsintheSocket.create(socket)
const websocketLink = createAbsintheSocketLink(abssocket)

const apolloLink = new ApolloLink.split(
  operation => hasSubscription(operation.query),
  ApolloLink.from([onLinkError, websocketLink]),
  ApolloLink.from([onLinkError, httpLink])
)

const client = new ApolloClient({
  link: apolloLink,
  cache: new InMemoryCache()
}) 
```

**Comment by benwilson512** [comment]
If you have `iex -S mix phx.server` open and do `:observer.start`, head to the processes tab and then sort by the "reds" column. Which process has the most? What is its current function?

**Comment by benwilson512** [comment]
Also per the issue template please provide all of the various version info required.

**Comment by benwilson512** [comment]
I'm curious to see what observer shows for you, I did the rapid play / stop in the book example project without CPU growth.

**Comment by maxguzenski** [comment]
Before: 
<img width="839" alt="captura de tela 2018-11-22 as 21 51 27" src="https://user-images.githubusercontent.com/6819/48924623-7f701f80-eea1-11e8-8049-e83336dc3fd3.png">


After (befero freeze):
<img width="846" alt="captura de tela 2018-11-22 as 21 55 58" src="https://user-images.githubusercontent.com/6819/48924632-957de000-eea1-11e8-9e30-540636623647.png">


After freeze (erlang stop to respond, so I dont know if this is updated info)
<img width="846" alt="captura de tela 2018-11-22 as 22 01 27" src="https://user-images.githubusercontent.com/6819/48924699-35d40480-eea2-11e8-8ff7-75cc84035f86.png">

**Comment by maxguzenski** [comment]
I updated first post with more env info.

**Comment by benwilson512** [comment]
Weird, the top item is actually just the phoenix code reloading server. If you mash the play button for a regular query does the same thing happen or just with subscriptions?

**Comment by benwilson512** [comment]
A segmentation fault is very very weird. That makes it seem like something is off with your erlang install. Absinthe has no NIFs so there's nothing it can do to cause a segfault.

**Comment by maxguzenski** [comment]
I have a aws instance to test as well, I'll deploy there my code and see.

**Comment by maxguzenski** [comment]
At aws , running with prod config... I got "ets_alloc: Cannot allocate 9127109480 bytes of memory (of type "db_term")."

**Comment by maxguzenski** [comment]
Some times I got this error: 

```
[debug] INCOMING "unsubscribe" on "__absinthe__:control" to Absinthe.Phoenix.Channel
  Parameters: %{}
[error] GenServer #PID<0.1193.0> terminating
** (FunctionClauseError) no function clause matching in Absinthe.Phoenix.Channel.handle_in/3
    (absinthe_phoenix) lib/absinthe/phoenix/channel.ex:41: Absinthe.Phoenix.Channel.handle_in("unsubscribe", %{}, %Phoenix.Socket{...lot...})
(phoenix) lib/phoenix/channel/server.ex:293: anonymous fn/4 in Phoenix.Channel.Server.handle_info/2
    (d4_web) lib/d4_web/endpoint.ex:1: D4.Web.Endpoint.instrument/4
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by benwilson512** [comment]
Is anything publishing? or is the app completely at rest except for the subscribe / unsubscribe?

**Comment by maxguzenski** [comment]
No, only my is using it now... so is just sub/unsub many times, nothing else.

**Comment by benwilson512** [comment]
If you're able to create an app that shows this behaviour where you can push up the full code that'd be very helpful.

Ecto shouldn't be a factor here if you aren't publishing, subscribing won't cause any database access unless you do some in the config function which I don't see you doing. The Phoenix version should be largely irrelevant here too unless you can also create the problem by simply pushing a large volume of messages via a channel.

**Comment by maxguzenski** [comment]
OK, I will try... but take a look on this images:

Here, elixir is not responding:
<img width="955" alt="captura de tela 2018-11-22 as 22 56 35" src="https://user-images.githubusercontent.com/6819/48925390-34a6d580-eeaa-11e8-9907-97c1f4df243e.png">

Here, elixir came back after few seconds:
<img width="955" alt="captura de tela 2018-11-22 as 22 56 42" src="https://user-images.githubusercontent.com/6819/48925408-5e5ffc80-eeaa-11e8-91fa-6765d37a33b8.png">

**Comment by benwilson512** [comment]
This is all super weird. Basically none of the code showing up here is Absinthe code. The `Registry.PIDPartition0`  process is just an Elixir registry, and the second image is part of erlang itself I guess? One thing to note is that the memory usage overall is absolutely nuts. Elixir.Logger there is using 4 gigs in both images. IN the first image the erlang TLS Process one is using 2.7 gigs.

I'm quite at a loss here.

**Comment by maxguzenski** [comment]
I tried a test project and I can't reproduce this issue... I'll keep testing.

**Comment by maxguzenski** [comment]
I fixed it.

I've a very complex dataloader with a lot of anonymous functions. I don't know if this issue was because build that was slow or because it was big on Absinthe context (maybe both)... but I rewrite it and everything is working now.

Thanks a lot for your time!

**Comment by Velychkanych** [comment]
Good afternoon to all !!! How to implement server-side unsubscrider in graphql

**Comment by Velychkanych** [comment]
Good afternoon to all !!! How to implement server-side unsubscrider in graphql ???

**Comment by benwilson512** [comment]
Hi @Velychkanych please direct questions to the elixir forum or slack. The issue tracker is for issues.
