### ISSUE TITLE
Logging subscription broadcast timing?

### ISSUE THREAD

**Issue by schabou** [absinthe-graphql/absinthe#653]
Looking into tracking the delay between when a change in the data happens and the eventual `publish_subscription` broadcast that sends a message out to each subscribed user, there's currently no easy way to retrieve that information.

Being able to measure how long it takes for the system to process an update and push it out to subscribed users would be nice to have from a performance benchmarking / monitoring perspective.

**Comment by benwilson512** [comment]
Absinthe should probably integrate with Telemetry to emit events. Notably, in this particular case all that Absinthe can measure is the time required to run / broadcast on a specific document topic. There may be multiple actual processes subscribed to that topic. Broadcasting to those would be handled by PhoenixPubSub so Absinthe isn't able to emit events at that level of granularity.

PR is welcome with a telemetry integration.

**Comment by benwilson512** [comment]
Telemetry is now included in Absinthe.
