### ISSUE TITLE
Handle Sec-Websocket-Protocol response header for Apollo client

### ISSUE THREAD

**Issue by Acidic9** [absinthe-graphql/absinthe#661]
If submitting a bug, please provide the following:

### Environment

* Elixir version (elixir -v): 1.7.4
* Absinthe version (mix deps | grep absinthe): 1.4.13
* Client Framework and version (Relay, Apollo, etc): Apollo

### Expected behavior

Connect to Absinthe GraphQL websocket with Apollo from Vue app and handling the `Sec-Websocket-Protocol` header.

### Actual behavior

```
WebSocket connection to 'ws://localhost:4000/ws/websocket' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
```

![Imgur](https://i.imgur.com/ZLWKrlO.png)

The Apollo client sends the `Sec-WebSocket-Protocol: graphql-ws` header, but the Absinthe server doesn't handle this and doesn't return the `Sec-Websocket-Protocol` header.

**Comment by benwilson512** [comment]
The core absinthe project doesn't concern itself with any transport. Right now the only websocket based transport that exists is in absinthe_phoenix which expects the client to use the phoenix channels library. You can find an integration here https://github.com/absinthe-graphql/absinthe-socket/tree/master/packages/socket-apollo-link

If you don't want to use that package then you'll need to write a handler for the apollo specific protocol.

**Comment by ivan-kolmychek** [comment]
As a side-note, it also breaks things that are powered by Apollo that are made by third parties, like [Altair GraphQL client](https://github.com/imolorhe/altair).

**Comment by benwilson512** [comment]
@ivan-kolmychek as noted before, this is the wrong project for this kind of issue. Absinthe does not do transports.

**Comment by hubertlepicki** [comment]
@benwilson512 @ivan-kolmychek do you folks maybe know if the protocol is identical to what happens through @absinthe/socket / Phoenix socket or it's a different protocol too? 

I am currently using the not really maintained @absinthe/* socket and link packages with React and Apollo, but I would love be able to connect using plain Apollo with graphql-ws
