### ISSUE TITLE
list of non_null returns null

### ISSUE THREAD

**Issue by BlueHotDog** [absinthe-graphql/absinthe#664]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.1.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.7.4 (compiled with Erlang/OTP 21)
```
* Absinthe version (mix deps | grep absinthe):
```
* absinthe 1.4.13 (Hex package) (mix)
  locked at 1.4.13 (absinthe) 81eb2ff4
* absinthe_plug 1.4.6 (Hex package) (mix)
  locked at 1.4.6 (absinthe_plug) ac5d2d3d
```
* Client Framework and version (Relay, Apollo, etc):
None

I've the following obj:
  ```
object :organization do
    field(:id, non_null(:id))
    field(:urls, list_of(non_null(:string)))
  end
```

And the following resolution:
```
%{
    :id => 3,
    :urls => [nil]
  }
```

### Expected behavior

Error

### Actual behavior
```
{
        "id": "3",
        "urls": null
}
```

### Relevant Schema/Middleware Code

none, new project.

I'm happy to open a PR, but need some pointers as to where to write the tests and where to start digging as this is not a small project..

**Comment by benwilson512** [comment]
The current behaviour is what we believe the specification requires. It's always possible we're wrong, but if you wish to change how this works you'll need to provide references to the spec.

**Comment by BlueHotDog** [comment]
@benwilson512 Not sure about the spec, but the official documentation state that it should not be valid.
https://graphql.org/learn/schema/#lists-and-non-null
Here is the relevant excerpt:
```
The Non-Null and List modifiers can be combined. For example, you can have a List of Non-Null Strings:

myField: [String!]
This means that the list itself can be null, but it can't have any null members. For example, in JSON:

myField: null // valid
myField: [] // valid
myField: ['a', 'b'] // valid
myField: ['a', null, 'b'] // error
Now, let's say we defined a Non-Null List of Strings:

myField: [String]!
This means that the list itself cannot be null, but it can contain null values:

myField: null // error
myField: [] // valid
myField: ['a', 'b'] // valid
myField: ['a', null, 'b'] // valid
You can arbitrarily nest any number of Non-Null and List modifiers, according to your needs.
```

By Error i mean, GraphQL error. meaning the result is invalid.

**Comment by Adzz** [comment]
@BlueHotDog What happens if you make it:

```elixir
field(:urls, non_null(list_of(non_null(:string))))
```

**Comment by benwilson512** [comment]
@BlueHotDog `myField: ['a', null, 'b'] // error` is exactly what is happening. An `Error` in this context is a graphql error not an actual Elixir exception. Absinthe adds a graphql error and then per https://facebook.github.io/graphql/draft/#sec-Errors-and-Non-Nullability propagates `null` up to the first nullable field. In your case that's the `urls` field itself. If you want that field to be non null you need the outer non null mentioned by @Adzz .

Notably though that'll just mean that the `null` keeps getting pushed upward till it hits a nullable field. And in none of those cases does it entail an Elixir exception.
