### ISSUE TITLE
Custom scalar of type object error

### ISSUE THREAD

**Issue by Zyclotrop-j** [absinthe-graphql/absinthe#670]
### Environment

* Elixir version: Elixir 1.7.4 (compiled with Erlang/OTP 19)
* Absinthe version: absinthe 1.4.13
* Client Framework and version: GraphiQL

### Expected behaviour
Query:
```
    mutation {
        createObject(something: {s: "text"}) {
            something
        }
    }
```

where the incomming data 
`arg(:something, :json)`, `:json` being a custom scalar (see below)

Expected successful query with a return value of `{"something": {"s": "text"}`

### Actual behaviour

Error is returned
```
{
  "errors": [
    {
      "message": "Argument \"something\" has invalid value {s: \"text\"}.\nIn field \"s\": Unknown field.",
      "locations": [
        {
          "line": 2,
          "column": 0
        }
      ]
    }
  ]
}
```

### Relevant Schema/Middleware Code

Mutation:
  ```
    mutation do
      field :create_object, type: :myanything do
        arg(:something, :json)
```

Custom scalar:
```
          scalar :json, name: "Json" do
            description("""
            Conerts anything to a json-serializeable value
            """)
                serialize(&encode/1)
                parse(&decode/1)
            end

            [....code for extract......]

            defp decode(val) do
                value = extract(val) # extract parses through the input data
                # log for testing that conversion worked:
                IO.inspect({:ok, value}) # {:ok, %{"s" => "text"}}
                {:ok, value}
            end

          defp encode(value) do
            IO.puts("encode")
            value
          end
```

The custom scalar works as expected, decode returns the right value. However the value returned in `{:ok, value}` never reaches the resolver.

Surprisingly the following query (code unchanged) works:
```
    mutation {
        createObject(something: "text") {
            something
        }
    }
```
returning 
```
{"something": "text"}
```

Side note: A working implementation in GraphQL.js see https://github.com/taion/graphql-type-json

Last but not least, I found this issue unanswered here: https://elixirforum.com/t/defining-scalar-type-with-absinthe/16935

**Comment by benwilson512** [comment]
The issue is that Absinthe does not, as of now, permit scalars to overwrite GraphQL syntax. The fact that GraphQL-JS does probably means we'll have to, but right now the rule is that the only things that can be treated as customs scalars are things that parse as scalars. `{s: "text"}` parses as an input object and consequently can't be treated as a scalar.

**Comment by binaryseed** [comment]
This one is interesting.. There's a lot of flexibility gained by being more lax, but it's not according to the spec. There's even a proposal to add an optional `ofType` to custom scalars to specify it's serialization scalar type.

https://github.com/graphql/graphql-spec/pull/521

@benwilson512 When you say this means we'll "have to", what do you mean? Should it be configurable perhaps? tbh I just put together a branch that allows this for a particular use case I'm mulling over.

**Comment by binaryseed** [comment]
If this something we want to be configurable? I tweaked a few phases to enable this in our api since we had a strong need for it.

**Comment by benwilson512** [comment]
Maybe, but I want to re-look at it after the 1.5 release
