### ISSUE TITLE
Document how to test scalars

### ISSUE THREAD

**Issue by tcoopman** [absinthe-graphql/absinthe#674]
By looking into the code I found out how to write a [test for a custom scalar](https://github.com/absinthe-graphql/absinthe/blob/0b6fc8756527d8d1f38c22c7389627e187404c98/test/absinthe/type/built_ins/scalars_test.exs#L17)

It would be nice if:

1. The `__absinthe_type__` could be put public on some helper function.
2. This was documented somewhere

**Comment by benwilson512** [comment]
Hey @tcoopman does https://hexdocs.pm/absinthe/Absinthe.Schema.html#lookup_type/3 do what you want?

**Comment by tcoopman** [comment]
Thanks, going to check that out.
Is there a reason you don't use that in the tests?
