### ISSUE TITLE
Proposal: base subscription document ID on subscription topic 

### ISSUE THREAD

**Issue by arkgil** [absinthe-graphql/absinthe#675]
Hello 👋 

Today I stumbled upon something which I think *might* be unintuitive for other folks as well.

Let's say I have a schema with the following subscription:

```elixir
subscription do
  field :userUpdates do
    config fn _, _ ->
      {:ok, topic: "#{:rand.uniform(100)}"
    end
  end
end
```

This is probably one of the worst methods to achieve this, but the intention here is to have a separatate subscription topic for any subscription query submitted by the client.

Now, when Absinthe executes the subscription query (either by simply using `Absinthe.Phoenix.Socket` or invoking `Absinthe.run/3`) it returns a following map

```elixir
%{"subscribed" => topic}
```

where topic can be used to subscribe to updates pushed to that subscription. But this topic is not the same as the one provided in the return value of `config` - it's a document ID generated by Absinthe. When we publish data to a subscription, Absinthe translates the topic returned by `config` to a document ID and notifies every process subscribed to that document ID.

The issue I found is that Absinthe doesn't rely on user provided topic when computing document ID - it relies only on the operation blueprint. If the blueprint happens to be the same, which is the case when you invoke the same operation with the same arguments providing the same context, the document ID will be the same. This implies that even if I submit two exactly same subscription queries, even when the topic returned by `config` is different, effectively I will be subscribed to two subscriptions.

I think that document ID could also rely on the user provided topic. This way returning different topic for subscriptions will actually create different subscriptions.

What do you think about it? Is there something I have missed, which invalidates this proposal? Thanks!

**Comment by benwilson512** [comment]
Hey! Good points. I believe this is handled by https://github.com/absinthe-graphql/absinthe/pull/654 but maybe you can read through it and make sure your specific issues are addressed?

**Comment by arkgil** [comment]
@benwilson512 sorry, I've looked through issues but haven't checked the PRs.. Thanks!
