### ISSUE TITLE
Can't define complexity of object

### ISSUE THREAD

**Issue by gabrielpra1** [absinthe-graphql/absinthe#687]
### Environment

* Elixir version (elixir -v): 1.8.1
* Absinthe version (mix deps | grep absinthe): 1.4.14
* Client Framework and version (Relay, Apollo, etc): Does not apply

### Expected behavior

The [docs](https://hexdocs.pm/absinthe/complexity-analysis.html) say that we can define the complexity of an object, as shown in the example:

```
object :person do
  field :name, :string
  field :age, :integer
  # constant complexity for this object
  complexity 3
end
```

### Actual behavior

However, when I try to define the complexity of an object:

```
@desc "Account balance"
object :account_balance do
  field :total, :decimal
  field :available, :decimal
  field :blocked, :decimal

  complexity 20
end
```

I get the following error:

```
== Compilation error in file lib/sppyns_web/schema/account.ex ==
** (Absinthe.Schema.Notation.Error) Invalid schema notation: `complexity` must only be used within `field`
    (absinthe) lib/absinthe/schema/notation.ex:1622: Absinthe.Schema.Notation.do_recordable!/4
    (absinthe) expanding macro: Absinthe.Schema.Notation.complexity/1
    lib/sppyns_web/schema/account.ex:77: SppynsWeb.Schema.Account (module)
    (absinthe) expanding macro: Absinthe.Schema.Notation.object/2
    lib/sppyns_web/schema/account.ex:67: SppynsWeb.Schema.Account (module)
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
** (exit) shutdown: 1
    (mix) lib/mix/tasks/compile.ex:102: Mix.Tasks.Compile.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (iex) lib/iex/helpers.ex:104: IEx.Helpers.recompile/1
```

Is this a bug in Absinthe or just outdated docs?

**Comment by binaryseed** [comment]
I suspect this is just a documentation issue. The code specifically designates the placement of complexity to be limited to fields:

https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/schema/notation.ex#L563

**Comment by binaryseed** [comment]
Fixed the docs over here: https://github.com/absinthe-graphql/absinthe/pull/817
