### ISSUE TITLE
Resolution Helpers example may be innacurate

### ISSUE THREAD

**Issue by shamshirz** [absinthe-graphql/absinthe#689]
https://github.com/absinthe-graphql/absinthe/blob/fa207be01d8f2e4697ff9f0aaec320a5bec56562/lib/absinthe/resolution/helpers.ex#L91

Should this be using `Dataloader.get(…)` instead of `load`?

**Comment by benwilson512** [comment]
Yes, PR welcome!

**Comment by binaryseed** [comment]
fixed in #697
