### ISSUE TITLE
Schema compilation does not fail while missing middleware module

### ISSUE THREAD

**Issue by jeanparpaillon** [absinthe-graphql/absinthe#690]
### Environment

* Elixir version (elixir -v): 1.8.1
* Absinthe version (mix deps | grep absinthe): 1.4.14

### Expected behavior

Let have the following object:
```elixir
field :field1 do
  policy MyPolicy, :check 
end
```

`policy` is a macro provided by AbsintheAuth library. I forgot to insert `use AbsintheAuth` in my module so the macro is not available.

The schema MUST NOT compile.

### Actual behavior

The schema compiles with no error.

**Comment by benwilson512** [comment]
This shouldn't / won't cause a compilation error any more than any other reference to a module which doesn't exist will. This will result in an error at runtime, but not compile time.

**Comment by jeanparpaillon** [comment]
I'm using a macro which does not exist. The elixir compiler will complain, so I don't understand why Absinthe should "hide" the error.

**Comment by benwilson512** [comment]
Oh. Did you try this on the 1.5 alpha?

**Comment by jeanparpaillon** [comment]
Will give a try, thanks
