### ISSUE TITLE
updating to 1.4.15 fails

### ISSUE THREAD

**Issue by bitboxer** [absinthe-graphql/absinthe#691]
### Environment

```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.3 (compiled with OTP 20)
```

### Expected behavior

Compiling of absinthe works without failing

### Actual behavior

I am trying to upgrade my project to 1.4.15, but sadly it fails on Travis and locally with:

```
Compiling 2 files (.erl)
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:59: illegal pattern
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:60: variable 'Error' is unbound
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:60: variable 'Stacktrace' is unbound
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:63: variable 'Stacktrace' unsafe in 'try' (line 60)
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:64: variable 'Error' unsafe in 'try' (line 60)
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:64: variable 'Stacktrace' unsafe in 'try' (line 60)
could not compile dependency :absinthe, "mix compile" failed. You can recompile this dependency with "mix deps.compile absinthe", update it with "mix deps.update absinthe" or clean it with "mix deps.clean absinthe"
The command "mix coveralls.travis" exited with 1.
```

More details in [this PR](https://github.com/signdict/website/pull/332) and this output on [Travis](https://travis-ci.com/signdict/website/builds/102774059).

**Comment by benwilson512** [comment]
This is quite odd, there are nearly no changes between 1.4.14 and 1.4.15. Elixir 1.6.3 is reasonably old at this point, does it compile with a newer version?

**Comment by bitboxer** [comment]
it bumps from 1.4.13 to 1.4.15. I think the problem is in .13, that one also fails. This also fails in 1.7.4.

**Comment by benwilson512** [comment]
Waaait so here's what's weird:
```
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools
```
Why is my `.asdf` in there? And it says erlang 21.2.2. Waaat?

**Comment by benwilson512** [comment]
Aha! The hex publish process is picking up a build artifact. Let me push a new version.

**Comment by benwilson512** [comment]
Apparently there were some backwards incompatible changes to how yecc works in a recent erlang version that changed how the build artifacts were created. These got picked up by hex. 1.4.16 should fix this.

**Comment by bitboxer** [comment]
Awesome. Thanks. Dependabot already created a new PR that is green: https://github.com/signdict/website/pull/334

**Comment by benwilson512** [comment]
Sweet.
