### ISSUE TITLE
absinthe 1.4.15 compilation fails on Fedora 29

### ISSUE THREAD

**Issue by strzibny** [absinthe-graphql/absinthe#692]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 (compiled with Erlang/OTP 20)
* Absinthe version (mix deps | grep absinthe): 1.4.15
* Client Framework and version (Relay, Apollo, etc): not applicable

### Expected behavior

Compilation goes without problem (as it does for me with version `1.4.13`)

### Actual behavior

When I compile a Phoenix project (or also when I run just `mix deps.compile absinthe`) I am getting following error both with `1.4.15` and `1.4.14`:
```
==> absinthe
Compiling 2 files (.erl)
/Users/ben/.asdf/installs/erlang/21.0.4/lib/parsetools-2.1.7/include/yeccpre.hrl:59: illegal pattern
/Users/ben/.asdf/installs/erlang/21.0.4/lib/parsetools-2.1.7/include/yeccpre.hrl:60: variable 'Error' is unbound
/Users/ben/.asdf/installs/erlang/21.0.4/lib/parsetools-2.1.7/include/yeccpre.hrl:60: variable 'Stacktrace' is unbound
/Users/ben/.asdf/installs/erlang/21.0.4/lib/parsetools-2.1.7/include/yeccpre.hrl:63: variable 'Stacktrace' unsafe in 'try' (line 60)
/Users/ben/.asdf/installs/erlang/21.0.4/lib/parsetools-2.1.7/include/yeccpre.hrl:64: variable 'Error' unsafe in 'try' (line 60)
/Users/ben/.asdf/installs/erlang/21.0.4/lib/parsetools-2.1.7/include/yeccpre.hrl:64: variable 'Stacktrace' unsafe in 'try' (line 60)
could not compile dependency :absinthe, "mix compile" failed. You can recompile this dependency with "mix deps.compile absinthe", update it with "mix deps.update absinthe" or clean it with "mix deps.clean absinthe"
```
Note I am using Erlang 20 from Fedora 29 and Elixir installed by `exenv`. Not sure how to get more info as I am starting with Elixir this week. Can I provide more details?

**Comment by strzibny** [comment]
This also happens to me with `1.5.x` alpha releases.

**Comment by strzibny** [comment]
Possible cause: https://github.com/jeremyjh/dialyxir/issues/197#issuecomment-405549463

**Comment by benwilson512** [comment]
Can you talk about your build process? Absinthe 1.4.14 has been out for a while, your linked issue seems to indicate you're using docker?

**Comment by benwilson512** [comment]
as with https://github.com/absinthe-graphql/absinthe/issues/691 the paths listed show my `.asdf` path and a different erlang version. @bruce have you seen anything like this?

**Comment by strzibny** [comment]
The build process is `mix deps.get` and `mix deps.compile` on an existing Phoenix project, no Docker.

I just tried to build it outside of that and getting this:

```
$ mix archive.install hex absinthe 1.4.15
Resolving Hex dependencies...
Dependency resolution completed:
New:
  absinthe 1.4.15
* Getting absinthe (Hex package)
Resolving Hex dependencies...
Dependency resolution completed:
New:
  dataloader 1.0.6
  decimal 1.7.0
* Getting dataloader (Hex package)
* Getting decimal (Hex package)
==> decimal
Compiling 1 file (.ex)
Generated decimal app
==> dataloader
Compiling 4 files (.ex)
Generated dataloader app
==> absinthe
Compiling 2 files (.erl)
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:59: illegal pattern
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:60: variable 'Error' is unbound
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:60: variable 'Stacktrace' is unbound
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:63: variable 'Stacktrace' unsafe in 'try' (line 60)
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:64: variable 'Error' unsafe in 'try' (line 60)
/Users/ben/.asdf/installs/erlang/21.2.2/lib/parsetools-2.1.8/include/yeccpre.hrl:64: variable 'Stacktrace' unsafe in 'try' (line 60)
$ echo $?
1
```

**Comment by benwilson512** [comment]
Apparently there were some backwards incompatible changes to how yecc works in a recent erlang version that changed how the build artifacts were created. These got picked up by hex. 1.4.16 should fix this. This is a ultimately I think a dup of the other issue so I'm gonna close this.

**Comment by strzibny** [comment]
Just want to say thank you, can confirm `1.4.16` compiles without issues.
