### ISSUE TITLE
Proposal: Node local version of Absinthe.Subscription.publish/3

### ISSUE THREAD

**Issue by darrenclark** [absinthe-graphql/absinthe#706]
### Background

The app I'm working on is proxying updates from an external source and exposing these updates as GraphQL subscription fields.

Each Elixir node in our cluster has a process monitoring the external source and then publishes updates to the related GraphQL field.  Since each Elixir node is independently monitoring the external source, we only need to publish subscription updates to the local node.

### Proposal

To "officially" support this use case, I was hoping to either:

- add a public `Absinthe.Subscription.publish_local/3` function, or
- add docs to `Absinthe.Subscription.Local.publish_mutation/3` function

Thoughts?  I'm happy to make a PR with the preferred approach (or another approach)

**Comment by benwilson512** [comment]
I'm inclined to say we should just document the Local module. PR welcome

**Comment by bruce** [comment]
Sounds good to me as well. @darrenclark, please reach out in your PR if you'd like assistance.

**Comment by darrenclark** [comment]
Cool, will do.
