### ISSUE TITLE
Dataloader equivalent (or alternative approach)

### ISSUE THREAD

**Issue by AndrewIngram** [absinthe-graphql/absinthe#72]
I discussed this with @benwilson512 in Slack briefly, but having thought about it further, I don't think that the solution to n+1 queries suggested in [this page](http://absinthe-graphql.org/guides/ecto-best-practices/) will work well enough to be a generalised solution.

Essentially the solution proposed right now is to use the AST (passed to every resolve function) to look ahead and work out what relations will be followed, and use that information to preload those relationships (with Ecto).

The issue is this is a very Ecto-centric approach to GraphQL, it won't work at all with a service-oriented architecture, and won't work with any kind of backend that doesn't support joins, or backends which use several different storages. The main use case I have right now is integrating elasticsearch - I could have a Product type, with related categories, tags, users etc; and I may retrieve the products and facets from elasticsearch, then want to retrieve their relations from my postgresql database.

[Dataloader](https://github.com/facebook/dataloader) takes the approach of letting you define loaders, that you call with individual IDs, which are aggregated and turned into a single request to whatever backend you may have. The results are then passed back to the relevant callers. I don't know enough about Elixir to know whether this approach is possible (the JS implementation detail relies on certain details about how JavaScript works which probably don't exist in Elixir), so an alternative might be needed (the idea that springs to mind is the ability to define a `resolve_batch` function against a field). But what's clear to me is that every language that implements a GraphQL server, also needs a solution  to this problem.

**Comment by AndrewIngram** [comment]
Looks like Sangria has first-class concepts of Deferred resolvers (what i'm asking for) and Projections (what is already possible, but could be made simpler) which might be worth adopting: http://sangria-graphql.org/learn/#deferred-values-and-resolver

**Comment by bruce** [comment]
@AndrewIngram The "how" of dataloader certainly isn't a direct port to Elixir/Erlang, but I'm confident we have better tools on hand for, eg, concurrency to apply to an implementation. Dataloader has been on our list of ecosystem tools to look into next, as I know that others in the GraphQL/JS space rely on it.

**Comment by benwilson512** [comment]
I'll add that I'm very excited by the options pursued by Sangria, as I think those concepts are going to be more easily applicable to Elixir.

**Comment by bruce** [comment]
:+1:

**Comment by AndrewIngram** [comment]
I agree about Sangria's approach in general, it seems to be the most mature GraphQL implementation right now. The original graphql-js was intended purely as a reference implementation and it's starting to show.

**Comment by bruce** [comment]
Also see https://github.com/Shopify/graphql-batch for some similar concepts

**Comment by bruce** [comment]
Tagging this as "roadmap" and closing it, but merely for temporary archival purposes. We know this and a number of other issues are big ticket items we need to address; we've got some of the foundational pieces going in now, and let's create more focused, actionable issues/PR discussion around this (eg, on deferred resolution, which I know @benwilson512 is very interested in as an approach).

**Comment by axelson** [comment]
Just to close the loop here Absinthe now has a dataloader built-in: https://github.com/absinthe-graphql/dataloader

I believe it can also be considered feature-complete (for the majority of use-cases at least), although I'm not 100% sure on that.
