### ISSUE TITLE
Mutations fail without  `use Absinthe.Phoenix.Endpoint` in the phx app Endpoint.ex module

### ISSUE THREAD

**Issue by jacobparry** [absinthe-graphql/absinthe#721]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 (compiled with Erlang/OTP 20)
* Absinthe version (mix deps | grep absinthe): 
absinthe 1.4.13 
absinthe_relay 1.4.6
absinthe_plug 1.4.6
absinthe_phoenix 1.4.3

### Expected behavior

A simple mutation succeeding for creating a user and returning it to the Graphiql interface.

Mutation:
```
mutation ($input: CreateUserInput!) {
  createUser(input: $input) {
    id
  }
}
```
Variables:
```
{
  "input": {
    "age": 21,
    "email": "test@test.com",
    "username": "new_user_1",
    "password": "super_safe_password"
  }
}
```
Result: 
```
{
  "data": {
    "createUser": {
      "id": "18"
    }
  }
}
```

### Actual behavior
Without `use Absinthe.Phoenix.Endpoint` in the Endpoint.ex module, it errors.

SyntaxError: Unexpected token < in JSON at position 0
POST /playground/graphiql
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function UiWeb.Endpoint.publish_mutation/3 is undefined or private
        (ui) UiWeb.Endpoint.publish_mutation("__absinthe__:proxy:1", %Db.Models.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, age: 21, email: "test@test.com", id: 19, inserted_at: ~N[2019-04-25 04:30:23], password: "super_safe_password", updated_at: ~N[2019-04-25 04:30:23], username: "new_user_1"}, [])
        (absinthe) lib/absinthe/subscription.ex:138: Absinthe.Subscription.publish_remote/3
        (absinthe) lib/absinthe/subscription.ex:76: Absinthe.Subscription.publish/3
        (absinthe) lib/absinthe/subscription.ex:145: Absinthe.Subscription.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:209: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:168: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:53: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe) lib/absinthe/pipeline.ex:274: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:421: Absinthe.Plug.run_query/4
        (absinthe_plug) lib/absinthe/plug.ex:247: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:39: Phoenix.Router.Route.call/2
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (ui) lib/ui_web/endpoint.ex:1: UiWeb.Endpoint.plug_builder_call/2
        (ui) lib/plug/debugger.ex:122: UiWeb.Endpoint."call (overridable 3)"/2
        (ui) lib/ui_web/endpoint.ex:1: UiWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:34: Phoenix.Endpoint.Cowboy2Handler.init/2

### Relevant Schema/Middleware Code

I haven't enabled subscriptions yet at all. We have been working through the book and just started on mutations. 

Here is a github repo that you can use to replicate the issue. https://github.com/jacobparry/elixir_mycreditperks
It is an umbrella app with 4 apps. The `ui` app is the phoenix app and the `api` app contains all of the graphql schema stuff.

In order to replicate the issue, all you have to do is comment out the `use Absinthe.Phoenix.Endpoint` line in the Endpoint.ex module.

Run: `mix reset` to set up the database.
Then, run `iex -S mix phx.server` and navigate to localhost:4000/playground/graphiql

Mutation:
```
mutation ($input: CreateUserInput!) {
  createUser(input: $input) {
    id
  }
}
```
Variables:
```
{
  "input": {
    "age": 21,
    "email": "test@test.com",
    "username": "new_user_1",
    "password": "super_safe_password"
  }
}
```

**Comment by benwilson512** [comment]
Hey @jacobparry I ran your project and it seemed to work fine:

![image](https://user-images.githubusercontent.com/247817/56752066-7ab3de00-6755-11e9-8ebd-d274794a38cb.png)

Notably, you have subscriptions sort of half setup. You've got Absinthe.Phoenix.Socket here https://github.com/jacobparry/elixir_mycreditperks/blob/master/my_credit_perks_umbrella/apps/ui/lib/ui_web/channels/user_socket.ex#L4 but no endoint setup. This may be be what's going on? Not sure why that wouldn't cause an issue for me though.
