### ISSUE TITLE
Passthrough Adapter Still Breaks Introspection? (Master branch)

### ISSUE THREAD

**Issue by mmendez512** [absinthe-graphql/absinthe#728]
Hey Guys,

I'm aware that Passthrough Adapter breaks introspection but talking today on slack it seems like there's a fix that's been merged in the master branch from this PR: https://github.com/absinthe-graphql/absinthe/pull/711

So I updated my projection to use all of the Absinthe dependencies to use their respective master branches  and I'm still seeing the same introspection errors in GraphiQL after it loads up.

So I just want to double check about the fix. If not, is there a workaround I can do to resolve this? I want to use my project as GraphQL API Gateway and need to pass in the camelCase fields to respective microservices in the resolvers, since they're expecting them like that. 

### Environment

* Elixir version (elixir -v): 1.8.1
* Absinthe version (mix deps | grep absinthe):  using master, as suggested from slack

From mix file:

 {:absinthe, git: "https://github.com/absinthe-graphql/absinthe.git", override: true},
 {:absinthe_plug, git: "https://github.com/absinthe-graphql/absinthe_plug.git", override: true},
 {:absinthe_phoenix, git: "https://github.com/absinthe-graphql/absinthe_phoenix.git", override: true}

* Client Framework and version (Relay, Apollo, etc):  None, right now. Using Graphiql currently.

### Expected behavior

Introspection not breaking when using adapter: Absinthe.Adapter.Passthrough

### Actual behavior
Getting errors like this, in reference to the case of the introspection fields:

"message": "Cannot query field \"ofType\" on type \"__Type\". Did you mean \"of_type\"?"

**Comment by binaryseed** [comment]
I can't seem to reproduce this, so I'm closing the issue. If you are finding it still is a problem in 1.5, please let us know and provide a reproduction case... Thanks!
