### ISSUE TITLE
Compilation fails on latest master inside Absinthe.Blueprint.Schema.build_types/3

### ISSUE THREAD

**Issue by archseer** [absinthe-graphql/absinthe#730]
@binaryseed compilation works for us on b61acbbf26b16e45398f46ef5012cf8c8864d33f (just before telemetry was merged), but not on 8ff081647bff240c80b259a6032204d1c652c1a1 (telemetry merge commit).

It's inside a larger schema, but the error points to the `use` macro.

```
** (FunctionClauseError) no function clause matching in Keyword.merge/3

    The following arguments were given to Keyword.merge/3:

        # 1
        true

        # 2
        true

        # 3
        #Function<12.52116511/3 in Absinthe.Blueprint.Schema.update_private/2>

    Attempted function clauses (showing 1 out of 1):

        def merge(keywords1, keywords2, fun) when is_list(keywords1) and is_list(keywords2) and is_function(fun, 3)

    (elixir) lib/keyword.ex:763: Keyword.merge/3
    (elixir) lib/keyword.ex:776: Keyword.do_merge/6
    (elixir) lib/keyword.ex:776: Keyword.do_merge/6
    (elixir) lib/map.ex:752: Map.update!/3
    lib/absinthe/blueprint/schema.ex:135: Absinthe.Blueprint.Schema.build_types/3
    expanding macro: Absinthe.Schema.Notation.__before_compile__/1
    schema/foo.ex:1: Viking.GraphQL.Schema.Foo (module)
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by benwilson512** [comment]
@archseer this appears to be related to updating the `private` attribute on something. Can you provide any information about how you're using `private` or `meta` ?

**Comment by archseer** [comment]
I don't see either being used in that schema (we do use `absinthe_relay` though). I'll take some time tomorrow and see if I can make a minimal reproduction.

**Comment by benwilson512** [comment]
That would be very helpful, thanks!

**Comment by archseer** [comment]
I think this can be closed, the issue was that we had a `resolve` clause defined twice:

```elixir
  object(:mutations) do
    payload(field(:request)) do
      input do
        field(:id, non_null(:id))
      end

      output do
        field(:requested, :boolean)
      end

      resolve(
        Helpers.parse_node_ids(&(Resolvers.request/3,
          request_id: :request
        )
      )

      resolve(&Resolver.request/3)
    end
end
```

It was a bug on our end, but for some reason the code would compile fine before.

**Comment by benwilson512** [comment]
Absinthe 1.5 is more strict about compilation, but there are situations where it doesn't have very good error messages yet. Thanks for finding the root cause, let me see what I can do about having it error in a better way.

**Comment by praveenperera** [comment]
For anyone getting here by searching the error:

I had the same thing because for some reason I had both in me `schema.ex`

This was compiling with Absinthe 1.4

```elixir
  use Absinthe.Schema
  use Absinthe.Schema.Notation
``` 

For me I had to just remove: ` use Absinthe.Schema.Notation`

```diff
  use Absinthe.Schema
-  use Absinthe.Schema.Notation
```

**Comment by josethz00** [comment]
still having this issue

**Comment by josethz00** [comment]
fixed by modifying my `root.ex` :
```elixir
defmodule JthomazDevWeb.Schema.Types.Root do
  use Absinthe.Schema.Notation
  alias JthomazDevWeb.Resolvers.Admin, as: AdminResolver
  import_types JthomazDevWeb.Schema.Types.Admin

  object :root_query do

    field :get_admin, type :admin do
      arg :id, non_null(:id)

      resolve &AdminResolver.get/2
    end

  end
end

```

just removed the `type` indicator
```elixir
  object :root_query do

    field :get_admin, type :admin do
      arg :id, non_null(:id)

      resolve &AdminResolver.get/2
    end

  end
```

**Comment by benwilson512** [comment]
You should only be calling `import_types` from the root schema module, there isn't any value in importing it into individual notation files, and tends to introduce complications.
