### ISSUE TITLE
Compilation fails on telemetry with compiled document

### ISSUE THREAD

**Issue by maartenvanvliet** [absinthe-graphql/absinthe#734]
Not sure whether this belongs in the `absinthe_plug` or `absinthe` repo. 

I wanted to try out telemetry on the latest master branch of absinthe, but when I tried compiling the project it failed because of a precompiled document.

I reproduced it in the `absinthe_plug` by moving the precompiled document from an `.exs` file to an `.ex` file, so they will be compiled along with the project. See this commit
https://github.com/absinthe-graphql/absinthe_plug/commit/11ab73ae97732c5ce02a4d084ab9eba9040770b9

I think the precompilation of the document happens and telemetry is triggered, but telemetry expects something to be available in the runtime which is not there because it is being compiled.

@binaryseed you may know what's happening?

### Environment

* Elixir version (elixir -v):
`Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.2 (compiled with Erlang/OTP 19)`

* Absinthe version (mix deps | grep absinthe):
`absinthe (https://github.com/absinthe-graphql/absinthe.git) (mix)`

* Client Framework and version (Relay, Apollo, etc):
not relevant

### Expected behavior

That compiled documents would work as before.

### Actual behavior

Compilation of the project failed with
```
22:40 $ mix test
Compiling 23 files (.ex)

== Compilation error in file test/support/literal_documents.ex ==
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:telemetry_handler_table, [:absinthe, :execute, :operation, :start])
    
...../absinthe_plug/deps/telemetry/src/telemetry_handler_table.erl:47: :telemetry_handler_table.list_for_event/1

....../absinthe_plug/deps/telemetry/src/telemetry.erl:114: :telemetry.execute/3
    lib/absinthe/phase/telemetry.ex:18: Absinthe.Phase.Telemetry.run/2
    lib/absinthe/pipeline.ex:354: Absinthe.Pipeline.run_phase/3
    lib/absinthe/plug/document_provider/compiled/writer.ex:37: anonymous fn/4 in Absinthe.Plug.DocumentProvider.Compiled.Writer.quoted_compiled_lookups/1
    (stdlib) maps.erl:257: :maps.fold_1/3
    lib/absinthe/plug/document_provider/compiled/writer.ex:30: Absinthe.Plug.DocumentProvider.Compiled.Writer.quoted_compiled_lookups/1
```

### Reproduce 

Check out this commit and run `mix test`
https://github.com/absinthe-graphql/absinthe_plug/commit/11ab73ae97732c5ce02a4d084ab9eba9040770b9

**Comment by maartenvanvliet** [comment]
I was able to resolve it by removing the Telemetry phase from the pipeline in the document compilation. See https://github.com/maartenvanvliet/absinthe_plug/commit/bb2a30165cc2ec092d32e84ac206cc273d9b3ef9

Is this the proper solution? If so I'll file a PR on `absinthe_plug`

**Comment by binaryseed** [comment]
Hmm that might work, I'll have to dig in a bit more, we'd still want telemetry to kick in when actually executing a query

**Comment by benwilson512** [comment]
Yeah the precompilation process needs to remove telemetry from the pipeline used to prepare the doc, and then add it to the pipeline that remains for execution.

**Comment by binaryseed** [comment]
Got a PR to fix this, thanks!

https://github.com/absinthe-graphql/absinthe_plug/pull/209
