### ISSUE TITLE
Mutation type is ignored

### ISSUE THREAD

**Issue by fuelen** [absinthe-graphql/absinthe#751]
### Precheck
The following mutation doesn't care about the type and renders object as is:
```elixir
    field :log_out, :boolean do
      resolve fn _, _ -> {:ok, %{action: :performed}} end
    end
```
query:
```graphql
mutation logout {
  logOut
}
```

### Environment

* Elixir version (elixir -v): 1.8.1
* Absinthe version (mix deps | grep absinthe): 1.4.16

### Expected behavior
Some kind of error

### Actual behavior
query result:
```json
{
  "data": {
    "logOut": {
      "action": "performed"
    }
  }
}
```

**Comment by benwilson512** [comment]
This is the same issue as https://github.com/absinthe-graphql/absinthe/issues/603
