### ISSUE TITLE
SDL schema order

### ISSUE THREAD

**Issue by binaryseed** [absinthe-graphql/absinthe#765]
Currently, the order of items defined in a SDL based schema is not preserved.

@bruce is going to investigate

**Comment by benwilson512** [comment]
Preserved in what sense?

**Comment by binaryseed** [comment]
If one defines a schema using SDL, the order that items were defined is lost when stored as blueprint structs.

I found this when doing the Render SDL work - I wanted to compare the input & output SDL, and had to re-order the items to match the order they wound up in as structs

**Comment by benwilson512** [comment]
Ah. This is somewhat at odds with the implication of #759 wherein the expectation is that things come out in sorted order. Would it work always do sorted order vs original order? Original order + schema stitching seems largely impossible.
