### ISSUE TITLE
SDL Rendering: support arbitrary schema directives

### ISSUE THREAD

**Issue by binaryseed** [absinthe-graphql/absinthe#766]

**Comment by jessedrelick** [comment]
I am curious if this is related to the issue I mentioned here:

https://github.com/absinthe-graphql/absinthe/issues/387#issuecomment-606795861

**Comment by kdawgwilk** [comment]
What is actually missing to support this?  I dug in a bit and it appears everything is in place to support this based on this
https://github.com/absinthe-graphql/absinthe/blob/72ff9f91fcc0a261f9965cf8120c7c72ff6e4c7c/lib/absinthe/schema/notation/sdl_render.ex#L45-L47
The only directives that are not rendered are those built-ins listed here
https://github.com/absinthe-graphql/absinthe/blob/72ff9f91fcc0a261f9965cf8120c7c72ff6e4c7c/lib/absinthe/schema/notation/sdl_render.ex#L21-L26

**Comment by binaryseed** [comment]
This Issue isn't really the core need, I'm going to close it and create a more meaningful one

**Comment by binaryseed** [comment]
https://github.com/absinthe-graphql/absinthe/issues/1003

**Comment by binaryseed** [comment]
FYI, SDL rendering of Type System Directives was added in https://github.com/absinthe-graphql/absinthe/pull/1010
