### ISSUE TITLE
Enum constructed from list of values from another module

### ISSUE THREAD

**Issue by youroff** [absinthe-graphql/absinthe#767]
I'm trying to dynamically define an Enum type. Well, not dynamically per se, it's all determined at compile time, but the set of possible values is maintained in another module. Apparently it's possible to pass a list of values like this:
```
enum :my_type, values: [:yay, :nay]
```

But it's treated as AST, not value, so when I try doing something like this, it blows up:
```
enum :my_type, values: AnotherModule.list_of_atoms()
```

Absinthe DSL is pretty amazing and definitely one of the most expressive in Elixir world, but isn't there should be less magical way to construct definitions (kinda manually)?

For now I solved it in an ugly ass hacky way and obviously not happy with this "solution":
```
Code.eval_string("enum :my_type, values: #{inspect AnotherModule.list_of_atoms()}", [], __ENV__)
```

What's a proper way of handling things like this?  

### Environment

* Elixir version (elixir -v): 1.9.0
* Absinthe version (mix deps | grep absinthe): 1.4.16

**Comment by binaryseed** [comment]
This should be possible with Absinthe 1.5. The docs show how to manipulate the schema structs...

https://hexdocs.pm/absinthe/1.5.0-beta.2/Absinthe.Schema.html

And this test has further examples:

https://github.com/absinthe-graphql/absinthe/blob/master/test/absinthe/schema/manipulation_test.exs

**Comment by BenMorganIO** [comment]
First, this is a poor answer on "docs show how to", second this does not work on Absinthe 1.5.

**Comment by binaryseed** [comment]
This is now supported in Absinthe 1.6
