### ISSUE TITLE
Add support for subscriptions

### ISSUE THREAD

**Issue by ashneyderman** [absinthe-graphql/absinthe#78]
and an example of its use.

**Comment by benwilson512** [comment]
Hey!

We are also very interested in subscriptions. Unfortunately the challenge at the moment is that strictly speaking subscriptions aren't even in the draft spec, and the first and foremost goal of this particular library is to implement the spec.

What that means is that this isn't on the short list of items to add at the moment as far as I know. I'll leave it to @bruce to decide if it still makes sense to keep this issue around until it is.

**Comment by bruce** [comment]
@benwilson512 I told him to add it in Slack. ;-)

My reasoning: "I think in this case it makes sense to go past the draft spec, since there is code in the wild."

**Comment by benwilson512** [comment]
doh! Carry on :+1:

**Comment by bruce** [comment]
This post is a good source reference, btw: http://graphql.org/blog/subscriptions-in-graphql-and-relay/

More reason I think it's worth adding: "We’re actively building out the event-based subscription approach described above. We’ve built out live liking and commenting features on our iOS and Android apps using that approach, and are continuing to flush out its functionality and API."
