### ISSUE TITLE
Atoms ending in numbers do not parse correctly (ie. address_line_1)

### ISSUE THREAD

**Issue by Eein** [absinthe-graphql/absinthe#781]
### Environment

* Elixir version (elixir -v): 1.9.1
* Absinthe version (mix deps | grep absinthe): 1.4.16
* Client Framework and version (Relay, Apollo, etc): Apollo

### Expected behavior

When using addresses, there may be a shipping_address column in the database called address_line_1 and address_line_2
You would expect these to be query-able with addressLine1 and addressLine2

### Actual behavior

When you query for addressLine1 it  recommends that you query for addressLine1 (or addressLine2 if it exists)
ie:
request
```
{
  user {
    shippingAddresses {
      addressLine1
    }
  }
}
```
response
```
{
  "errors": [
    {
      "locations": [
        {
          "column": 0,
          "line": 6
        }
      ],
      "message": "Cannot query field \"addressLine1\" on type \"ShippingAddress\". Did you mean \"addressLine2\" or \"addressLine1\"?"
    }
  ]
}
```

# Notes
This problem can be corrected by using the following in your Ecto.Schema
```
    field :address_line1, :string, [source: :address_line_1]
    field :address_line2, :string, [source: :address_line_2]
```

and in your types:

```
    field :address_line1, :string
    field :address_line2, :string
```

----

If this is expected behavior - feel free to ignore and close this issue (it'll be good for people searching for a solution to the same issue), if not I'd be willing to write a test case and pr in the next couple weeks to rectify this issue. 

The first discussion is identifying any cases where `_integer` would not count as a case to not break any existing apps. This would likely have to be released in a breaking version for safety.

**Comment by benwilson512** [comment]
Hey @Eein, the error message is definitely not great, and it's one we hope to catch at schema build time. The functionality here though is largely correct, since we simply rely on `Macro.underscore`, which doesn't add a `_` prior to numbers. There are no plans to change that, in part because if you wish to make that work differently you can already do so by using a custom adapter.

**Comment by Eein** [comment]
Awesome! Thanks! Ill close this then :)
