### ISSUE TITLE
Taking in an arbitrary input object from a Scalar

### ISSUE THREAD

**Issue by satom99** [absinthe-graphql/absinthe#788]
We are in the need to be able to take in an arbitrary input object as an argument
to one of our queries. For that reason, I figured doing so from a custom Scalar
would be our best bet.

However, when accepting an input object from the scalar and returning a success
tuple, Absinthe does complain that the given input object has unknown fields even
though we are in a custom scalar - and not within a defined input object per se.

---

Consider the following scalar implementation:
```elixir
defmodule Example.Type.Custom do
    use Absinthe.Schema.Notation

    alias Absinthe.Blueprint.Input.Object

    scalar :custom do
        parse(&decode/1)
    end

    defp decode(%Object{}) do
        {:ok, %{}}
    end
    defp decode(_term) do
        :error
    end
end
```
And the following defined query field:
```elixir
        field :example, :string do
            arg :test, :custom
            resolve fn _params, _resolution ->
                {:ok, "success"}
            end
        end
```
Queried the following way:
```gql
query{
  example(
    test:{
      a:4
    }
  )
}
```
Resulting in the following error:
```json
{
  "errors": [
    {
      "locations": [
        {
          "column": 0,
          "line": 3
        }
      ],
      "message": "Argument \"test\" has invalid value {a: 4}.\nIn field \"a\": Unknown field."
    }
  ]
}
```

**Comment by benwilson512** [comment]
Hey @satom99 

This has come up before, and the stance we've taken is the there's nothing in the spec to suggest that custom scalars are allowed to re-interpret GraphQL syntax. `{a: 4}` simply is an input object, it can't be anything else. The usual answer for allowing arbitrarily shaped data is to accept a JSON scalar: `example(test:"{\"a\":4}")`.

**Comment by kdawgwilk** [comment]
Should we reopen this based on https://github.com/absinthe-graphql/absinthe/pull/1069#issuecomment-839925601

**Comment by benwilson512** [comment]
I don't think so, it is really superseded by #1069 and I don't want to split the discussion.
