### ISSUE TITLE
Apollo Federation

### ISSUE THREAD

**Issue by fbjork** [absinthe-graphql/absinthe#790]
Are there any plans on supporting Federation (https://www.apollographql.com/docs/apollo-server/federation/introduction/)?

**Comment by benwilson512** [comment]
Hi @fbjork yes work to enable schema stitching is in progress.

**Comment by conradwt** [comment]
@benwilson512 Did you mean Apollo Federation because Federation has replaced the now deprecated, Schema Stitching?

**Comment by benwilson512** [comment]
@conradwt sure, we have been using the term "schema stitching" to simply loosely refer to the idea of aggregating several different schemas into one queryable schema, we were not planning to copy Apollo's implementation verbatim.

At the current moment the main focus has simply been on making Absinthe schemas easier to construct in a data driven way. 1.5 will release with those features, and then the Absinthe core team will look at tools to provide the "gateway" style features that Apollo Federation has. There are some examples of this already within the community I believe.

**Comment by d-led** [comment]
I guess, now one can simply use the GraphQL Mesh to transform an existing endpoint into a Federation-conforming one https://graphql-mesh.com/docs/transforms/federation/

as for stitching, one can do it externally: https://graphql-mesh.com/docs/getting-started/mesh-transforms/#usage-example

also relevant for #387

**Comment by d-led** [comment]
update: stitching has gotten easier: See an example here https://github.com/d-led/graphql_mesh_federation_test. Adding federation might have gotten better as well

**Comment by amacciola** [comment]
@d-led Schema stitching and federation are not the same though

```
Each system has a unique strategy for combining sub-services:

- Federation services are aware of each other’s data while the gateway is a generic agent that combines them. The gateway configures itself by reading SDLs from each service, and may be reloaded on the fly with new SDLs.

- Stitching services remain unaware of each other while the gateway loads and combines their schemas. Recent development has added SDL annotations that allow stitched schemas to also be reloaded on the fly.
```

So is it not possible to leverage Apollo Federation while also using Absinthe Elixir ?

**Comment by d-led** [comment]
> So is it not possible to leverage Apollo Federation while also using Absinthe Elixir ?

Mesh should, at least in principle, be able to add a Federation implementation to an existing nonconforming schema: https://www.graphql-mesh.com/docs/transforms/federation
via https://github.com/0xR/graphql-transform-federation

**Comment by benwilson512** [comment]
Apollo federation is not built in, but I don't see anything standing in the way of someone writing a library that enabled it on top of Absinthe. At this point Absinthe has exposed 100% complete control over how schemas are built, when schemas are built, and how queries are executed.

**Comment by coryodaniel** [comment]
If you are still interested in doing this, here is an [example](https://github.com/coryodaniel/federated-absinthe) of federating absinthe using the GraphQL Mesh library.

**Comment by kdawgwilk** [comment]
Or if you would like to give federation with absinthe a go try out this library https://github.com/DivvyPayHQ/absinthe_federation and give us some feedback 😊
