### ISSUE TITLE
How to run middleware on every query/mutation (NOT introspections)

### ISSUE THREAD

**Issue by samphilipd** [absinthe-graphql/absinthe#798]
Hi Ben

This isn't an issue, more of a question.

I want to run a middleware on every resolution that will ensure that a Policy was called.

Unfortunately this breaks introspection. Is there a way of specifying a middleware globablly that runs ONLY on user-defined fields?

I tried to add as `middleware` under the `query do` stanza but it didn't work.

Thanks!

**Comment by benwilson512** [comment]
Hi @samphilipd are you trying to do it on EVERY field or just fields on the root query object? Keep in mind that in:

```
object :user do
  field :name, :string
end
```

`:name` is also a field. If you want to do it only on fields with the root query object you can pattern match on the args to `def middleware`.

```
def middleware(%{identifier: :query}, _, middleware) do
  [Auth | middleware]
end
def middleware(_, _, middleware) do
  middleware
end
```
