### ISSUE TITLE
Cannot run Absinthe.Schema.introspect in compile phase because of telemetry

### ISSUE THREAD

**Issue by jfrolich** [absinthe-graphql/absinthe#807]
```
Compiling 1 file (.ex)
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:telemetry_handler_table, [:absinthe, :execute, :operation, :start])
    /Users/Jaap/Documents/development/family-five/server/deps/telemetry/src/telemetry_handler_table.erl:47: :telemetry_handler_table.list_for_event/1
    /Users/Jaap/Documents/development/family-five/server/deps/telemetry/src/telemetry.erl:114: :telemetry.execute/3
    lib/absinthe/phase/telemetry.ex:18: Absinthe.Phase.Telemetry.run/2
    lib/absinthe/pipeline.ex:366: Absinthe.Pipeline.run_phase/3
    lib/absinthe.ex:110: Absinthe.run/3
    lib/mix/tasks/compile.schema_json.ex:12: Mix.Tasks.Compile.SchemaJson.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:73: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:53: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:24: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:40: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.ex:96: Mix.Tasks.Compile.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/app.start.ex:58: Mix.Tasks.App.Start.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/run.ex:128: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
```

Would be great to have an option to drop the  telemetry phase. Otherwise generating a schema on compile is not possible anymore.

**Comment by benwilson512** [comment]
"Run in compile time" is unfortunately difficult to determine since you can compile anything at any time. A telemetry: false option to `run` and by extension `introspect` might be enough?

**Comment by binaryseed** [comment]
I opened a ticket in `telemetry` to see if those ETS lookups should be protected against.. Ideally `telemetry` can be installed everywhere without having to opt-out all over the place.

**Comment by binaryseed** [comment]
I'm curious about your mix task...

```
lib/mix/tasks/compile.schema_json.ex:12: Mix.Tasks.Compile.SchemaJson.run/1
```

That doesn't look like it comes from Absinthe itself... All the mix tasks defined in Absinthe will start all deps with `Application.ensure_all_started(:absinthe)`

https://github.com/absinthe-graphql/absinthe/blob/master/lib/mix/tasks/absinthe.schema.json.ex#L78

If this is a custom task, I'd recommend doing the same

**Comment by jfrolich** [comment]
> "Run in compile time" is unfortunately difficult to determine since you can compile anything at any time. A telemetry: false option to `run` and by extension `introspect` might be enough?

That would be perfect

**Comment by jfrolich** [comment]
> I opened a ticket in `telemetry` to see if those ETS lookups should be protected against.. Ideally `telemetry` can be installed everywhere without having to opt-out all over the place.

Yes that would probably be even better.

**Comment by jfrolich** [comment]
> @jfrolich I'm curious about your mix task...
> 
> ```
> lib/mix/tasks/compile.schema_json.ex:12: Mix.Tasks.Compile.SchemaJson.run/1
> ```
> 
> That doesn't look like it comes from Absinthe itself... All the mix tasks defined in Absinthe will start all deps with `Application.ensure_all_started(:absinthe)`
> 
> https://github.com/absinthe-graphql/absinthe/blob/master/lib/mix/tasks/absinthe.schema.json.ex#L78
> 
> If this is a custom task, I'd recommend doing the same

It's a task that runs at compile time with the compilers option in the `mix.exs`.

**Comment by binaryseed** [comment]
> so that's not an option unfortunately 

Why wouldn't you be able to call `Application.ensure_all_started(:absinthe)`?

**Comment by jfrolich** [comment]
> > so that's not an option unfortunately
> 
> Why wouldn't you be able to call `Application.ensure_all_started(:absinthe)`?

Because it runs in the compile stage, so the application can't (shouldn't) be running.

**Comment by binaryseed** [comment]
Telemetry PR was merged, we'll bump when a release is published!

**Comment by jfrolich** [comment]
Fantastic!
