### ISSUE TITLE
Allow set custom error path

### ISSUE THREAD

**Issue by virtual-light** [absinthe-graphql/absinthe#809]
### Environment

```
Elixir 1.9.0 (compiled with Erlang/OTP 22)
```
```
absinthe 1.4.16 (Hex package) (mix)
absinthe_relay 1.4.6 (Hex package) (mix)
absinthe_plug 1.4.7 (Hex package) (mix)
```

According to GQL specification [Error Response Format](https://graphql.github.io/graphql-spec/June2018/#sec-Errors) and examples from specification[[1]](https://graphql.github.io/graphql-spec/June2018/#example-90475)[[2]](https://graphql.github.io/graphql-spec/June2018/#example-08b62), nested errors should be flatten and `path` field should be used to specify the specific field that caused the error. 

```
If an error can be associated to a particular field in the GraphQL result, 
it must contain an entry with the key path that details the path 
of the response field which experienced the error. 
This allows clients to identify whether a null result is intentional or caused by a runtime error.
```

As I know, currently it is impossible to set custom error's `path` with absinthe, so this feature can be useful to format errors in a way recommended by GQL specification.

**Comment by virtual-light** [comment]
I think syntax can look like:

```elixir
{:error, %{message: "My error", path: ["my", "custom", "path", 0, "field"]}}
```

So, if custom `path` was provided, it should override the `path` that has been generated by
absinthe.

I can work on it to provide PR if there are no disagreement.

**Comment by benwilson512** [comment]
Hi @virtual-light I am a little confused about this request. When does an error happen in Absinthe where the path is not set correctly? Why should a user ever be able to make the path something other than Absinthe determines?

**Comment by binaryseed** [comment]
I'm going to close this - Absinthe does set the path according to the GraphQL spec, and I don't think we'd want a "custom" path...

Please re-open if we've mis-understood this.
