### ISSUE TITLE
Ambiguous AST Parsing

### ISSUE THREAD

**Issue by parkerduckworth** [absinthe-graphql/absinthe#812]
### Environment

* Elixir version: `1.8.1`
* Absinthe version: `1.4.16`
* Client framework and version: `cowboy 2.7.0`

### Expected behavior

When making GraphQL calls that include non-object types (enum, scalar, union), these types should be parsed into the Absinthe AST using their respective Absinthe type counterparts, e.g. `Absinthe.Type.Enum`, `Absinthe.Type.Scalar` etc.

### Actual behavior

A non-object type is represented as the generic `Absinthe.Type.Field`, making it necessary to use a cache of existing type names to match against when parsing the Absinthe AST.

### Relevant Schema/AST Code

Given this query,
```GraphQL
query {
  allItems {
    id  
    status
  }
}
```

Where `status` is an enum, 
```elixir 
	enum :item_status do
	    description "The status of the item"
	    value :unavailable, as: "UNAVAILABLE"
            value :available, as: "AVAILABLE"
	end
```

The `Absinthe.Blueprint.Document.Field` for `status` is as follows,
```
%Absinthe.Blueprint.Document.Field{
  alias: nil,
  argument_data: %{},
  arguments: [],
  complexity: nil,
  directives: [],
  errors: [],
  flags: %{},
  name: "status",
  schema_node: %Absinthe.Type.Field{
    __private__: [],
    __reference__: %{
      identifier: :status,
      location: %{
        file: "/<path>/item_types.ex",
        line: 8
      },
      module: <Module Name>.Graphql.SchemaTypes.Item
    },
    args: %{},
    complexity: nil,
    config: nil,
    default_value: nil,
    deprecation: nil,
    description: nil,
    identifier: :status,
    middleware: [{Absinthe.Middleware.MapGet, :status}],
    name: "status",
    triggers: [],
    type: :item_status
  },
  selections: [],
  source_location: %Absinthe.Blueprint.Document.SourceLocation{
    column: nil,
    line: 4
  },
  type_conditions: []
}
```

Where I would have expected `schema_node: %Absinthe.Type.Field` to be `schema_node: %Absinthe.Type.Enum`.

Thanks for taking a look into this issue, I really appreciate you all for providing and maintaining this lib.

-- Parker

**Comment by benwilson512** [comment]
Hi @parkerduckworth I think you're misunderstanding how the structure works here. Notice how the the `%Absinthe.Type.Field{}` struct has `type: :item_status`. When representing the query, the `status` field in the request maps to a `status` type field which contains LOTS of information about that field, not just its type. For xample it includes the middleware information, where in the file to find it, and so on.

**Comment by parkerduckworth** [comment]
@benwilson512  thanks for the explanation!
