### ISSUE TITLE
Placement checking for schema notation macros

### ISSUE THREAD

**Issue by binaryseed** [absinthe-graphql/absinthe#820]
We need to check the `@placement` annotations when building the schema based on macros

`master`:
* https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/schema/notation.ex#L1751

Logic in `1.4`:
* https://github.com/absinthe-graphql/absinthe/blob/v1.4.16/lib/absinthe/schema/notation.ex#L1608

**Comment by binaryseed** [comment]
@bruce Does this logic need to be re-worked or just pulled in ?

**Comment by benwilson512** [comment]
@binaryseed it needs to be reworked, the 1.4 placement checking logic relied on introspecting the 1.4 module attributes that were used during schema compilation. Those are completely reworked and there's really no introspectable concept of a "current" scope at the moment. We probably need to add an extra module attribute that we use just to track scope. It can be much simpler than before, we don't need to track _which_ object's scope we're in, just that we're in an object scope.

Something that basically just amounted to `[:field, :object, :schema]` would probably do fine, and then we pop the scope whenever we emit `:close`.

**Comment by binaryseed** [comment]
Got a PR together to implement this! #822
