### ISSUE TITLE
Nonexistent `Blueprint.Document.Resolution.node_t()` type used

### ISSUE THREAD

**Issue by tanguilp** [absinthe-graphql/absinthe#834]
The `Blueprint.Document.Resolution.node_t()` type is used in several files as a type but it doesn't exist. Example: https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/blueprint/result/list.ex#L17

This generates warnings when using Dialyzer.

**Comment by binaryseed** [comment]
I looked at this and I'm guessing it's meant to be `Absinthe.Blueprint.Execution.node_t`

Would you say that's right @benwilson512 ?
