### ISSUE TITLE
1.5.0-rc.2: Can't extend query type

### ISSUE THREAD

**Issue by aspett** [absinthe-graphql/absinthe#844]
### Environment

* Elixir version (elixir -v): 1.9.4
* Absinthe version (mix deps | grep absinthe): * absinthe 1.5.0-rc.2 (https://github.com/absinthe-graphql/absinthe.git) (mix)
* Client Framework and version (Relay, Apollo, etc): N/A

### Expected behavior

Expected that I can extend the Query type successfully using `import_sdl/1`. Hoping this is just a misunderstanding / lack of guide. I noticed extending types in the kitchen sync graphql tests works fine. :thinking: 

### Actual behavior

```
** (Protocol.UndefinedError) protocol Absinthe.Blueprint.Draft not implemented for %Absinthe.Language.TypeExtensionDefinition{definition: %Absinthe.Language.ObjectTypeDefinition{description: nil, directives: [], fields: [%Absinthe.Language.FieldDefinition{arguments: [], complexity: nil, description: nil, directives: [], loc: %{column: 3, line: 2}, name: "test_two", type: %Absinthe.Language.NamedType{loc: %{column: 13, line: 2}, name: "String"}}], interfaces: [], loc: %{column: 8, line: 1}, name: "Query"}, loc: %{column: 1, line: 1}} of type Absinthe.Language.TypeExtensionDefinition (a struct)
    lib/absinthe/blueprint/draft.ex:1: Absinthe.Blueprint.Draft.impl_for!/1
    lib/absinthe/blueprint/draft.ex:4: Absinthe.Blueprint.Draft.convert/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    lib/absinthe/schema/notation/sdl.ex:14: Absinthe.Schema.Notation.SDL.parse/4
    lib/lab_fulfillment_service_web/schema.ex:66: (module)
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7

```

### Relevant Schema/Middleware Code

```elixir

  use Absinthe.Schema


  query(name: "Query") do
    field :test_one, :string
  end

  import_sdl """
  extend type Query {
    test_two: String
  }
  """

  def hydrate(%Absinthe.Blueprint{}, _) do
    %{
      Query: %{
        test_one: [
          resolve: &resolve/3
        ],
        test_two: [
          resolve: &resolve/3
        ]
      }
    }
  end

  def hydrate(_, _) do
    []
  end

  defp resolve(_, _, _) do
    {:ok, "test"}
  end

```

**Comment by benwilson512** [comment]
I'm pretty sure the kitchen sink can only be _parsed_ right now, I don't see code for making extensions actually happen yet at all. The language of https://github.com/absinthe-graphql/absinthe/pull/821 seems to indicate that we're gonna tackle extending the macro world first, then add SDL support.

**Comment by binaryseed** [comment]
Correct, this isn't supported yet, and I don't think we're aiming for it to be in the initial 1.5 release

**Comment by benwilson512** [comment]
@binaryseed maybe we should explicitly raise or return some kind of error if extend is used that makes it clear it isn't supported yet?
