### ISSUE TITLE
Custom parse errors for scalars

### ISSUE THREAD

**Issue by evanreierson** [absinthe-graphql/absinthe#856]
In [the custom scalars guide](https://github.com/absinthe-graphql/absinthe/blob/master/guides/custom-scalars.md) it says:

> It's important to note that---currently---the correct result from a scalar's parse function in the event of the error is a lone atom, :error, not an error tuple with a reason. In a future version of Absinthe, custom parse errors may be supported. 

I think this is an important feature because clients should be able to know why a scalar isn't parsing to make debugging easier for them.

I am interested in implementing this feature, but I will need a bit of guidance because I am fairly new to elixir, absinthe, and open source contributions in general.

**Comment by benwilson512** [comment]
Hi @evanreierson the first place to start would be to sort out if the GraphQL spec allows for custom parsing error messages, or if the language is still standardized. When we first wrote this there was particular language that scalars which failed to parse were supposed to use. Maybe that's changed now, you'd have to check.

**Comment by evanreierson** [comment]
Thanks @benwilson512, I did not find this standardized language for custom parsing in the most recently published or draft version of the spec. It just says to return a query error when input coercion goes wrong or return a field error when result coercion fails.

In the [Response Errors section](http://spec.graphql.org/June2018/#sec-Errors) though, there is some language that seems to suggest that providing the ability to be more descriptive with error messages is encouraged.

> If the data entry in the response is not present, the errors entry in the response must not be empty. It must contain at least one error. The errors it contains should indicate why no data was able to be returned.

> Every error must contain an entry with the key message with a string description of the error intended for the developer as a guide to understand and correct the error.

These quotes are referring to the top level error ( "... Expected type X, found Y.") but there is also the option to add extensions, where we could put more details on why the coercion failed:

> GraphQL services may provide an additional entry to errors with key extensions. This entry, if set, must have a map as its value. This entry is reserved for implementors to add additional information to errors however they see fit, and there are no additional restrictions on its contents.

I may be missing something but I believe this feature would comply with the spec as long as we put the additional info in extensions. How should I continue?

**Comment by evanreierson** [comment]
I did some more digging into Absinthe errors and the GraphQL spec and it appears that Absinthe errors might be out of sync with the spec. This might need to be addressed in another issue or maybe it's not a problem, but:

![image](https://user-images.githubusercontent.com/31623887/74281036-ef530b80-4cda-11ea-9393-3c038c99d773.png)
[source](https://spec.graphql.org/June2018/#sec-Errors)

The [Absinthe docs on errors](https://github.com/absinthe-graphql/absinthe/blob/edaeab194ab675c1d5ffdd51510cd13e258038a5/guides/errors.md#basic-errors) are "discouraged" by the spec because it doesn't use an "extensions" field for additional details.

@benwilson512 do you think I should
a) open a new issue to discuss this in more detail,
b) work on a fix for the documentation but not the actual implementation,
c) ignore it because it is possible to adhere to the spec, just not enforced,
or proceed otherwise?

Since custom scalar errors are pretty intimate with Absinthe errors in general, we might want to resolve this before continuing with the current issue. Thanks!

**Comment by seivan** [comment]
Out of curiosity, what happens if a custom scalar just raises, like `:integer`
```
raise Absinthe.SerializationError, """
  Value #{inspect(n)} is not a valid integer
"""
```
Wouldn't that be handled by Absinthe and go through the proper channels?

**Comment by evanreierson** [comment]
Good idea! I just tried it with an Elixir raise ArgumentError though and it appears that the error is not caught/transformed by Absinthe later down the line. There is a full blown error and stack trace as opposed to the graphql-formatted error the client receives if :error is returned in the parse function. Do you think I could get different behaviour with a custom exception? 

I don't think that would be ideal though anyway because raising an exception goes against the principle of treating errors as data.

**Comment by seivan** [comment]
Well, here's the thing. You can't escape raising in your resolvers or middlewarse, sooner or later you're going to have a code that internally, somewhere deep will throw. 
There's a lot that can go wrong apart from failing to parse a custom scalar, there is a lot of movable parts apart from APIs that are documented to throw, like missing function patterns, guards and cases that don't tackle default by design. 

In those cases, I would rather Absinthe itself tackles it, however you can always implement a middleware that runs your resolvers for you in a try/catch.
This would also protect you within other middlewares

Though that won't protect in `before_exec/send/3`, but not sure about where the parsing happens. If it happens in a middleware, then it might just work. 

What I miss from old timey Rails style controllers were the ability to capture exceptions at BaseController and format the error to something digestable before returning a response. 
For those cases where you didn't match, you'd send a generic one until you get a better response.

**Comment by seivan** [comment]
Also noticed that Absinthe itself tackles when its own types are wrong.

```elixir
Absinthe.run("{ add(x: 10, y: hey) }", MySchema)
```

Expecting two integers, passing "hey" instead and I get 

```elixir
{:ok,
 %{
   errors: [
     %{
       locations: [%{column: 0, line: 1}],
       message: "Argument \"y\" has invalid value hey."
     }
   ]
 }}
```

**Comment by benwilson512** [comment]
@seivan this is correct, `hey` is an enum type not a scalar type, so the scalar parse function won't even run.

**Comment by seivan** [comment]
Ok... I also noticed this worked when `b` is `list_of(:integer)` but extracting it from `[b] = arg.b` before running `div/2`

```elixir
iex[nonode@nohost](2)> Absinthe.run("{ div(a: 10, b: 2) }", CalcSchema) 
{:ok, %{data: %{"div" => 5.0}}}
iex[nonode@nohost](4)> Absinthe.run("{ div(a: 10, b: [2]) }", CalcSchema)
{:ok, %{data: %{"div" => 5.0}}}
```

Does that mean that Absinth will try as many lexers(?) it can?

**Comment by benwilson512** [comment]
Scalar parsing doesn't happen at the lexer / parser level, it happens during query validation. As for that specific example, that looks like a bug, I don't think we should be unwrapping the list there.

**Comment by seivan** [comment]
Just to be clear you're not unwrapping the list, I am doing that from the argument before passing it to my function within a resolver.
The issue is that it's defined as a `list_of(:integer)` and I pass a `2` and it works.

**Comment by benwilson512** [comment]
Oh, that is part of the spec. List args are allowed to receive unwrapped values as long as the value is compatible with the inner type of `list_of(t)`.

**Comment by benwilson512** [comment]
@evanreierson please feel free to follow up with a PR adding custom error messages.

**Comment by dylan-chong** [comment]
Hey @evanreierson, was any progress made on this issue?

**Comment by evanreierson** [comment]
> Hey @evanreierson, was any progress made on this issue?

Hi @dylan-chong, Unfortunately, I did not make any further progress on this issue because I was in a rush and decided to use another GraphQL framework (in another programming language) with this feature already implemented. Sorry for the inconvenience and good luck!
