### ISSUE TITLE
Atom option for Utils.camelize

### ISSUE THREAD

**Issue by AdamBrodzinski** [absinthe-graphql/absinthe#86]
I was using the `Absinthe.Utils.camelize` function and thought it would be nice to have an option to return an atom instead of a binary. Is this something that you would be interested in? If so I would be happy to PR tomorrow.

Example:

```elixir
    # pass in as opt
    Absinthe.Utils.camelize("foo", lower: true, atom: true)
    >>> :foo

    # instead of piping after
    Absinthe.Utils.camelize("foo", lower: true)
    |> String.to_existing_atom
    >>> :foo
```

**Comment by bruce** [comment]
While I know it might save a bit of typing, `camelize` currently gets used a _lot_ at runtime to adapt documents/results; would rather we keep it as simple as possible to avoid any additional checks (occurring for, eg, each node in an AST). We actually have some ideas on adapters that will make this less of an issue (eg, adapting the schema internally instead, and probably locking it to a single adapter so we can do it at compile-time), but for the short term we're very concerned about adapter performance.

**Comment by AdamBrodzinski** [comment]
No prob! just thought i'd check. To be honest adding an extra line is no biggie :smile: :+1: 

Keep up the great work!
