### ISSUE TITLE
Allow altering of absinthe mutation/query arguments error output for non-null fields. 

### ISSUE THREAD

**Issue by mitcheaton1** [absinthe-graphql/absinthe#876]
If submitting a bug, please provide the following:

### Environment

* Elixir version 1.9.1
* Absinthe version absinthe 1.5.0-rc.3
* Phoenix 1.4

### Expected behavior

I have an error library for returning errors which includes some things under an extensions key in the error return as stated should be used in the graphql spec. https://spec.graphql.org/June2018/#sec-Errors

For pretty much everything I can return my own custom errors except when passing null for fields that are non-null in graphql mutations and queries. It seems i cant access the error return there, and cant pass in my extensions attribute. 

### Actual behavior
a mutation like 
```
 mutation ($email: String!, $firstName: String!, $lastName: String!) {
    createUser(email:$email, firstName:$firstName, lastName:$lastName) {
      user {
        firstName
        lastName
        email
      }
    }
  }
```
returns

```
       %{
             "errors" => [
               %{
                 "message" => "In argument \"lastName\": Expected type \"String!\", found null.",
                 "locations" => [%{"line" => 2, "column" => 50}]
               },
               %{
                 "message" => "Variable \"lastName\": Expected non-null, found null.",
                 "locations" => [%{"line" => 1, "column" => 49}]
               }
             ]
           }
```

But i would like to inject my payload here so i get something like 

```
 %{
             "errors" => [
               %{
                "extensions" => ....
                 "message" => "In argument \"lastName\": Expected type \"String!\", found null.",
                 "locations" => [%{"line" => 2, "column" => 50}]
               },
               %{
                 "extensions" => ....
                 "message" => "Variable \"lastName\": Expected non-null, found null.",
                 "locations" => [%{"line" => 1, "column" => 49}]
               }
             ]
           }
```

Can I handle this at the middleware or pluging level?

**Comment by benwilson512** [comment]
Hi @mitcheaton1, this would need to be handled with a custom phase added to the pipeline. These are validation errors, not resolution errors, so resolution level solutions won't apply here, since resolution never happens.
