### ISSUE TITLE
1.5 release discussion

### ISSUE THREAD

**Issue by benwilson512** [absinthe-graphql/absinthe#886]
@binaryseed @bruce Let's take a beat and sort out what we want in place for a 1.5 release, and what we want to communicate with subsequent release numbers.

In my view 1.5 is basically good to go. We achieved a complete rework of the schema internals, and we have covered the ground we need to support certain new use cases.

It is entirely possible that we'll need more changes to support fancier SDL or extend or w/e that forces some minor breaking changes, and for that we can do a 1.6.

In particular, I really don't mind if we need to do a 1.6 in a month or two because handling `extend` or handling a `:persistent_term` schema backend required some meaningful changes. We aimed for too much with 1.5 I think.

**Comment by binaryseed** [comment]
I agree that 1.5 is ready to go!

**Comment by benwilson512** [comment]
Agreed. I'm gonna try to handle this https://github.com/absinthe-graphql/absinthe/issues/887 today, and I want to provide some clarity WRT hydrate in the docs, and then I think we cut a release.

**Comment by bgentry** [comment]
Related to the release discussion, I wanted to make sure my question about the `use_parent` breaking change was seen before making a decision on the release: https://github.com/absinthe-graphql/absinthe/pull/882#issuecomment-605300660

**Comment by benwilson512** [comment]
I've added two other bugs that have been around for a while to the 1.5 milestone. Working on them now.

**Comment by binaryseed** [comment]
@benwilson512 Seems like all that's left is a little documentation for the `hydrate` additions, would you say that's right?

**Comment by benwilson512** [comment]
@binaryseed I'm trying to finish https://github.com/absinthe-graphql/absinthe/issues/683. In theory it could be a breaking change for anyone who was sending in the right data but accidentally had the wrong variable type specified.

**Comment by binaryseed** [comment]
I just pushed up PRs to fix two issues that have been recently reported:

* https://github.com/absinthe-graphql/absinthe/pull/910
* https://github.com/absinthe-graphql/absinthe/pull/909

**Comment by benwilson512** [comment]
Ok! I think Absinthe itself is good to go. Absinthe.Phoenix however needs updates to work with Phoenix 1.5. Technically, we could just go ahead and cut Absinthe 1.5 right now and say that we still only support Phoenix 1.4. I don't really like that though.

I'm working on Absinthe.Phoenix 2.0 which will support Phoenix 1.5. That should be done today. If it isn't done this week we should just go ahead and release Absinthe 1.5 regardless.

**Comment by benwilson512** [comment]
We did it, it's out!

**Comment by binaryseed** [comment]
Amazing!!
