### ISSUE TITLE
SDL import error

### ISSUE THREAD

**Issue by benwilson512** [absinthe-graphql/absinthe#887]
Importing this sdl https://gitlab.com/zo-team/ZenPub-Server/-/blob/develop/lib/valueflows/graphql/schemas/observation.gql#L475

and then using `import_fields :observation_mutations` results in this error https://gist.github.com/mayel/f2d700b8cdfa4a39f03d2f316b017c75 when introspection is run.

**Comment by mayel** [comment]
Thanks for looking into it! 

Please note that those definitions depend on a few others, also available at https://gitlab.com/zo-team/ZenPub-Server/-/tree/develop/lib/valueflows/graphql/schemas

**Comment by benwilson512** [comment]
Thanks!

**Comment by benwilson512** [comment]
The issue is that union types aren't having their `types` properly correctly transformed from blueprint type references to atoms.
