### ISSUE TITLE
Incorrect type spec in Absinthe.Blueprint.Execution 

### ISSUE THREAD

**Issue by software-opal** [absinthe-graphql/absinthe#900]
I've noticed this error when running dialyzer over a project that depends on Absinthe:
```
:0:unknown_type Unknown type: Result.Object.t/0.
```

I think it comes from [this reference to `Result.Object.t()` in Absinthe.Blueprint.Execution](https://github.com/absinthe-graphql/absinthe/blob/cf46de10c10e155b413e8609d49e32da2999a839/lib/absinthe/blueprint/execution.ex#L49). I think it'd just be a matter of changing it to be the fully qualified path, but I'm not able to pull it down and check.

**Comment by software-opal** [comment]
I should have clarified, I'm using Absinthe 1.4.16(which is the latest available on hex), which doesn't appear to contain [this line](https://github.com/absinthe-graphql/absinthe/blame/cf46de10c10e155b413e8609d49e32da2999a839/lib/absinthe/blueprint/execution.ex#L30) from #699.

After adding that one line to my dependency folder and recompiling everything, dialyzer now gives a new error:
```
:0:unknown_type Unknown type: Absinthe.Blueprint.Document.Resolution.node_t/0.
```
Which appears to be caused by these lines in [`Absinthe.Blueprint.Result.Object`](https://github.com/absinthe-graphql/absinthe/blob/cf46de10c10e155b413e8609d49e32da2999a839/lib/absinthe/blueprint/result/object.ex#L18), [`Absinthe.Blueprint.Result.List`](https://github.com/absinthe-graphql/absinthe/blob/cf46de10c10e155b413e8609d49e32da2999a839/lib/absinthe/blueprint/result/list.ex#L17), and [`Absinthe.Blueprint.Result.Leaf`](https://github.com/absinthe-graphql/absinthe/blob/cf46de10c10e155b413e8609d49e32da2999a839/lib/absinthe/blueprint/result/leaf.ex#L17). This is noted as an [internal change towards the end of the Changelog entry for 1.4.0](https://github.com/absinthe-graphql/absinthe/blob/v1.4/CHANGELOG.md#v140).

Fixing those lines to use `Blueprint.Execution.node_t()` instead of `Blueprint.Document.Resolution.node_t()` now produces no dialyzer errors.

**Comment by benwilson512** [comment]
Hi @software-opal can you try this again on the 1.5.0 RC? We've made a bunch of fixes to the type annotations within that release.

**Comment by software-opal** [comment]
I'm sorry I didn't reply sooner, I've tried to upgrade the project I'm working on to the 1.5.0 release candidate, but was not able to get it to work; probably due to some dependencies not being compatible. I wasn't able to track down the cause of the issue in the time I had available.

**Comment by benwilson512** [comment]
No worries!
