### ISSUE TITLE
Subscriptions manual is confusing

### ISSUE THREAD

**Issue by margusp2heathmont** [absinthe-graphql/absinthe#911]
Hello!

https://hexdocs.pm/absinthe/subscriptions.html

To setup Subscriptions using this manual, I am not successful. Errors that I had:

1. MyApp.PubSub vs MyApp.Endpoint - what should be content of both this files
2. MyApp.Web MyAppWeb GitHunt.Web is cross used - should the naming really be like this?
3. Example schema is not valid, as field needs to be in object.

In overall, this manual is really confusing and I was unable to get subscriptions to work.

**Comment by benwilson512** [comment]
Hi @margusp2heathmont, please don't use the issue tracker to ask questions. If you can identify concrete errors in the guides then that's fine, but questions should be directed at elixirforum.com or other elixir help sites.
