### ISSUE TITLE
Non-null error behavior inconsistent with GraphQL spec?

### ISSUE THREAD

**Issue by davidye** [absinthe-graphql/absinthe#912]
### Environment

* Elixir version (elixir -v): 1.9.4
* Absinthe version (mix deps | grep absinthe): 1.5.0-rc.5
* Client Framework and version (Relay, Apollo, etc): Apollo

### Expected behavior

I have the following schema:

```
object :user do
  field :id, non_null(:uuid)
  field :email, non_null(:string) do
    resolve &AccountsResolver.user_email/3
  end
end

query do
  field :user, non_null(:user) do
    arg :name, non_null(:string)
    resolve &AccountsResolver.user/2
  end
end
```

When a viewer does not have permission to view a user's email, the resolver returns {:error, :forbidden} which violates the non_null(:string) constraint. According to the spec here http://spec.graphql.org/draft/#sec-Errors-and-Non-Nullability, looks like this violation should propagate upwards and therefore return:

```
{
  "data": null,
  "errors": [
    ...
  ]
}
```

### Actual behavior

The actual result I get is:

```
{
  "data": {
    "user": {
      "email": null
    }
  },
  "errors": [
    ...
  ]
}
```

**Comment by davidye** [comment]
Interestingly, I have a separate query where everything works as expected:

```
query do
  field :me, non_null(:user) do
    resolve &AccountsResolver.me/2
  end
end
```

When resolver returns {:error, :forbidden}, the response, the result appears to be correct:

```
{
  "data": null,
  "errors": [
    ...
  ]
}
```

**Comment by benwilson512** [comment]
Interesting, I swear we have a test case to verify error propagation upwards. I'll look into it.

**Comment by benwilson512** [comment]
Hi @davidye I added a test case here https://github.com/absinthe-graphql/absinthe/commit/b884951532821c77d7bd69bf880c8a858ffc6dae.

This test case seems to reproduce your use case exactly, where you have a nested set of non null fields, and then deep within that a null is returned. The null value propagates all the way up to data.

Happy to reopen if you can provide a test case illustrating the issue you're seeing.
