### ISSUE TITLE
Meta fileds doesn't get printed with mix absinthe.schema.json

### ISSUE THREAD

**Issue by bernardo-martinez** [absinthe-graphql/absinthe#920]
### Environment

* Elixir version (elixir -v): `Elixir 1.9.1`
* Absinthe version (mix deps | grep absinthe):`absinthe 1.4.16`
* Client Framework and version (Relay, Apollo, etc): none

### Expected behavior

Would be great if we can have the [meta](https://hexdocs.pm/absinthe/Absinthe.Schema.Notation.html#meta/1) fields within the generated objects 

### Actual behavior

They are not outputted

### Relevant Schema/Middleware Code
I've tried two cases, under an object and under a query (which is basically an object):

```
object(:user) do
    meta(cache: true, ttl: 22_000)
   ...
end
```

and:
 
```
query do
    field(:user, :user) do
      meta(cache: true, ttl: 22_000)
      ...
   end
```
Thanks!

**Comment by binaryseed** [comment]
Hi there! The `absinthe.schema.json` task renders result of the standard GraphQL Introspection query:

https://github.com/absinthe-graphql/absinthe/blob/512d12cf40dc53963d306ef68a266817035d7d26/lib/mix/tasks/absinthe.schema.json.ex#L98

The `meta` fields are a concept internal to Absinthe, they aren't part of the GraphQL spec, so this isn't something we will be able to do out of the box...

**Comment by bernardo-martinez** [comment]
Oh I see, thanks man so I will close this as this is no part of graphql spec...
