### ISSUE TITLE
Max integer size in Absinthe is much larger than GraphQL's 

### ISSUE THREAD

**Issue by AntJanus** [absinthe-graphql/absinthe#921]
If submitting a bug, please provide the following:

### Environment

* Elixir version (elixir -v): 1.8.2
* Absinthe version (mix deps | grep absinthe): 1.4.16
* Client Framework and version (Relay, Apollo, etc): N/A -- using a custom-built client

### Expected behavior

When entering an integer bigger than the largest supported number by a 32-bit integer, Absinthe should return that it's an invalid integer  based on [GraphQL's typing](https://graphql.org/learn/schema/#scalar-types) and [GraphQL spec](https://spec.graphql.org/June2018/#sec-Int)

### Actual behavior

Absinthe validates numbers larger than 32-bit integers as integers which causes issues in other parts of the application that expect a 32-bit integer.

### Relevant Schema/Middleware Code

No relevant middleware code but I checked out the reasoning behind this in: https://github.com/absinthe-graphql/absinthe/blob/9f7350a6d4d7e31d553d436348d373e2b896db10/lib/absinthe/type/built_ins/scalars.ex

Where it mentions an adherence to the [IEEE754 standard](https://en.wikipedia.org/wiki/IEEE_754) standard for *double precision*. However, that standard directly clashes with the GraphQL spec.

IEEE 754 max integer is: 9,007,199,254,740,991
GraphQL max integer is: 2,147,483,647 

Anything over 2,147,483,647 should be a different type in a GraphQL schema (even if that doesn't map 1-to-1 in Elixir). The [GraphQL spec on Integers](https://spec.graphql.org/June2018/#sec-Int) suggests using a String or custom scalar instead.

**Comment by benwilson512** [comment]
Hi @AntJanus, you are absolutely right :)

Making this change is a little tricky. I'd like to find a way to deprecate and warn people via a patch release, with the aim to remove support for integers large than 2^32 in a 1.6 release. If we have users that are accidentally relying on this support right now, I don't want to break their applications in a patch release.

**Comment by AntJanus** [comment]
@benwilson512 is that something I could help with? I'd love to give back since we use Absinthe heavily at work :) (slowly rewriting our backend APIs with it).
