### ISSUE TITLE
[Bug] PersistentTerm Argument Error In Releases

### ISSUE THREAD

**Issue by derekbrown** [absinthe-graphql/absinthe#926]
### Environment

* Elixir version (elixir -v): Elixir 1.9.1 (Erlang/OTP 22)
* Absinthe version (mix deps | grep absinthe): 1.5.0
* Client Framework and version (Relay, Apollo, etc): n/a

### Expected behavior

Persistent Term schema loads in build released with `mix release`

### Actual behavior

Released build results in following error:
```
Application myapp exited: MyApp.start(:normal, []) returned an error: shutdown: failed to start child: {Absinthe.Schema, MyApp.GraphQL.Schema}
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :persistent_term.get({Absinthe.Schema.PersistentTerm, MyApp.GraphQL.Schema})
            (absinthe) lib/absinthe/schema/persistent_term.ex:96: Absinthe.Schema.PersistentTerm.get/1
            (absinthe) lib/absinthe/schema/persistent_term.ex:90: Absinthe.Schema.PersistentTerm.__absinthe_prototype_schema__/1
            (absinthe) lib/absinthe/schema/manager.ex:9: Absinthe.Schema.Manager.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### Relevant Information

- Unreleased application starts up fine in all environments.
- Order of Schema in the supervision tree ruled out as cause.
- From conversation via Slack, @benwilson512 believes it to be related to the Schema's [prototype lookup](https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/schema/manager.ex#L9
) in the schema manager. 
- "Mix makes that work accidentally pretty reliably because the loading of the schema module also sets the persistent term as part of the static check process, but that always fails in releases which don't load code that way."

**Comment by derekbrown** [comment]
Circling back here. Tried to fix myself by switching the `ensure_loaded?` checks to `ensure_loaded` checks (in both `persistent_term.ex` and `populate_persistent_term.ex`) to no avail. Was hoping to submit a PR for this. After trying to debug in release mode, it seems as if the schema isn't _put_ into persistent_term storage when released? Any reason why this would be?

**Comment by benwilson512** [comment]
Hey folks, can you all try https://github.com/absinthe-graphql/absinthe/pull/936 and see if it fixes your issue?

**Comment by binaryseed** [comment]
Feel free to re-open if you continue to see this issue after the fix above...
