### ISSUE TITLE
Providing functions to meta no longer works

### ISSUE THREAD

**Issue by gabrielpra1** [absinthe-graphql/absinthe#928]
### Environment

* Elixir version (elixir -v): 1.10.2
* Absinthe version (mix deps | grep absinthe): 1.5.1
* Client Framework and version (Relay, Apollo, etc): Not relevant

### Expected behavior

I expected the following to work (works in 1.4.16):

```elixir
object :user do
  field :email, :string do
    meta([private: & !&1.is_email_public])
  end
end
```

When inspecting the `meta[:private]` field in 1.4.16, in a middleware:

```elixir
def call(resolution, [object: %Type.Object{fields: fields} = object, field: field]) do
  fields[field] |> Type.meta(:private) |> IO.inspect() 
end
```

I get the function: `#Function<5.7636899/1 in Rajska.FieldAuthorizationTest.Schema.__absinthe_type__/1>`

### Actual behavior

In 1.5.1, however, with the same code I'm getting the AST instead of the function:

```elixir
{:&, [line: 84],
 [
   {:case, [optimize_boolean: true],
    [
      {{:., [line: 84], [{:&, [line: 84], [1]}, :is_email_public]},
       [no_parens: true, line: 84], []},
      [
        do: [
          {:->, [],
           [
             [
               {:when, [],
                [
                  {:x, [counter: {Rajska.FieldAuthorizationTest.Schema, 61}],
                   Kernel},
                  {{:., [], [:erlang, :orelse]}, [],
                   [
                     {{:., [], [:erlang, :"=:="]}, [],
                      [
                        {:x,
                         [counter: {Rajska.FieldAuthorizationTest.Schema, 61}],
                         Kernel},
                        false
                      ]},
                     {{:., [], [:erlang, :"=:="]}, [],
                      [
                        {:x,
                         [counter: {Rajska.FieldAuthorizationTest.Schema, 61}],
                         Kernel},
                        nil
                      ]}
                   ]}
                ]}
             ],
             true
           ]},
          {:->, [], [[{:_, [], Kernel}], false]}
        ]
      ]
    ]}
 ]}
```

Was this change intentional? By providing the AST instead of the actual value, it's now hard to use more complex structures in the `meta`, such as functions and maps, which is something some libraries depend upon.

**Comment by moperacz** [comment]
any news about this?

**Comment by tlvenn** [comment]
Hi, I am wondering if the work @Hermanverschooten did to fix meta on fields would not actually fix this issue as well. Can you try to reproduce on master ? Thanks.

**Comment by benwilson512** [comment]
@tlvenn do functions work if you use the persistent term backend?

**Comment by gabrielpra1** [comment]
@tlvenn I tried it again with the master version and still getting the same error, both when using the shortcut syntax and the `meta/1` syntax 😢 

I still not sure if this is how it's supposed to work, but I fixed my problem by evaluating the AST at runtime before trying to execute the function: https://github.com/jungsoft/rajska/pull/30/commits/01f716a3e96761b2acdbc123c0a831b68f63d82c.

@benwilson512 Should we evaluate the AST inside Absinthe or is it expected that the library clients do that on their own, like I did in that commit?

**Comment by stavro** [comment]
Duplicate issue that was already closed for this: https://github.com/absinthe-graphql/absinthe/issues/737

I still think it's a valuable property to keep, but apparently the complexity wasn't worth it, from @benwilson512 .

**Comment by benwilson512** [comment]
Hey folks. I believe as we prep to switch to using `:persistent_term` as the backend in the next release this will be come possible.

**Comment by binaryseed** [comment]
This can be accomplished in 1.5 using `hydrate`. Here's an example of dynamic Enum value hydration in the absinthe tests:

https://github.com/absinthe-graphql/absinthe/blob/master/test/absinthe/schema/hydrate_dynamic_values_test.exs

In your case, you can set the meta:

```elixir
{:meta, dynamic_meta()}
```

Documented here: https://hexdocs.pm/absinthe/Absinthe.Schema.html#c:hydrate/2
