### ISSUE TITLE
Insert middleware "just before" Absinthe.Resolution one.

### ISSUE THREAD

**Issue by hickscorp** [absinthe-graphql/absinthe#929]
Hello,

Please note that this entry is for a feature request as outline with an earlier conversation with @benwilson512, it is not a bug.

Imagine the following scenario.

A middleware definition that adds a `Authorize` module globally for all `%Object{}` resolutions:

```
  def middleware(mw, field, object),
    do: filter(mw, :auth, field, object)
  defp filter(mw, :auth, _field, %Absinthe.Type.Object{}),
    do: [Authorize | mw]
  defp filter(mw, _kind, _field, _object),
    do: mw
```

And then within the schema definition, somewhere in a mutation, a `Fetch` middleware module such as something like this:

```
    payload field :write_something do
      input do
        field :id, non_null(:id)
      end
      output do
        field :result, non_null(:result)
      end
      middleware Fetch, field: :id, into: :target, allow_nil: false
      resolve &StuffResolver.write_something/2
    end
```

In our use case, we would like `Authorize` to run *after* `Fetch`, because `Authorize` will need the result of what `Fetch` did to determine whether or not the user can perform the mutation.

As of now, there is no way to say "insert this middleware just before the `Absinthe.Resolution` middleware, and it makes it cumbersome to achieve what we would like to do. The only solution we found is a bit of a workaround, if anyone is interested. The following function reverse-traverses the list of middlewares and divides it into two stacks, which breaking point is the last use of `Fetch`, and then it inserts `Authorize` in the middle. Not very good looking but it fits the job:

```
  def middleware(mw, _field, _object = %Absinthe.Type.Object{}) do
    {_, head, tail} =
      mw
      |> Enum.reverse()
      |> Enum.reduce({false, [], []}, fn m, {found, head, tail} ->
        if found || match?({{Fetch, :call}, _}, m) do
          {true, [m | head], tail}
        else
          {false, head, [m | tail]}
        end
      end)
    head ++ [Authorize] ++ tail
  end
```

or in a more condensed form:

```
  def middleware(mw, _field, _object = %Absinthe.Type.Object{}) do
    {_, head, tail} =
      mw
      |> Enum.reverse()
      |> Enum.reduce({false, [], []}, fn
        m, {true, head, tail} -> {true, [m | head], tail}
        {{TTWeb.Middleware.Fetch, :call}, _} = m, {_, head, tail} -> {true, [m | head], tail}
        m, {_, head, tail} -> {false, head, [m | tail]}
      end)

    head ++ [Authorize] ++ tail
  end
```

Instead of this, we would very much enjoy a better way of managing middleware.

**Comment by binaryseed** [comment]
Seems like this could be further simplified using `Enum.split_while/2`, perhaps something like:

```elixir
{head, tail} = Enum.split_while(middleware, &(!match?({{Fetch, :call}, _}, &1)))
head ++ [Authorize] ++ tail
```

Given that, I'm going to close this issue - looks like everything needed to accomplish this is already in place :)
