### ISSUE TITLE
1.5 changelog is possibly missing a breaking change related to starting subscriptions

### ISSUE THREAD

**Issue by sgtpepper43** [absinthe-graphql/absinthe#930]
There was a change to the docs between 1.4 and 1.5 [here](https://github.com/absinthe-graphql/absinthe/commit/72ef10684970f3552077dd2277d730999c8686b5) where starting the Subscription worker changed from 
```elixir
{Absinthe.Subscription, [MyAppWeb.Endpoint]}
```
to
```elixir
{Absinthe.Subscription, MyAppWeb.Endpoint}
```
We just bumped to 1.5, and got a cryptic `no function clause matching in :elixir_aliases.do_concat/2` error, and eventually realized this was the problem. I don't know exactly _what_ changed, why it worked before, or why it doesn't work now, but it seems like it needs a breaking change line in the changelog, or at least a note or something, so that the next person to run into this doesn't have the same problems we had. Totally willing to do a PR for that, I just don't have any context about it.

**Comment by benwilson512** [comment]
Hi @sgtpepper43, I think we should probably just do a patch to 1.5 to enable both. Will handle.

**Comment by binaryseed** [comment]
I believe this was fixed in https://github.com/absinthe-graphql/absinthe/pull/936/files#diff-31a502606090ff98e0c793579dcf490c4dac9cf4bee60a22b4cac9cda4b4fe9d
