### ISSUE TITLE
Providing function to descriptions no longer works

### ISSUE THREAD

**Issue by bjunc** [absinthe-graphql/absinthe#935]
### Environment

* Elixir version (elixir -v): `Elixir 1.9.1`
* Absinthe version (mix deps | grep absinthe): `1.5.1`
* Client Framework and version (Relay, Apollo, etc): `n/a`

### Expected behavior

Previously (eg. `1.4.16`), I could pass a function to a field's description. We do this since many fields share the same description, and it keeps things dry (eg. objects and input objects often have the same description). It also cuts down on the schema noise.

### Actual behavior

I'm not a macro wizard, but it seems `1.5` changed the way the macro works for descriptions (and maybe others?). The String trim logic is now attempting to trim a quoted function; which throws an error.

Maybe related to #928 ?

### Relevant Schema/Middleware Code

`n/a`

**Comment by binaryseed** [comment]
This can be accomplished in 1.5 using `hydrate`. Here's an example of dynamic Enum value hydration in the absinthe tests:

In your case, you can set the description:

```elixir
{:description, dynamic_description()}
```

Documented here: https://hexdocs.pm/absinthe/Absinthe.Schema.html#c:hydrate/2

**Comment by dylan-chong** [comment]
Duplicate of #946

**Comment by bjunc** [comment]
That works, thanks.

Still experimenting with the "best" way to do this, but I'm currently doing something like this (for someone who stumbles onto this):

```elixir
# AppWeb.Schema

def hydrate(
    %Absinthe.Blueprint.Schema.FieldDefinition{identifier: field_name},
    [%Absinthe.Blueprint.Schema.ObjectTypeDefinition{identifier: parent_object} | _]
  ),
    do:
      {:description,
        __MODULE__.Descriptions.description("field:#{parent_object}.#{field_name}")}

def hydrate(%Absinthe.Blueprint.Schema.ObjectTypeDefinition{identifier: object}, _),
  do: {:description, __MODULE__.Descriptions.description("type:#{object}")}

def hydrate(_node, _ancestors), do: []

```

```elixir
# AppWeb.Schema.Descriptions

def description(identifier) when is_binary(identifier) do
  case identifier do
    identifier
      when identifier in [
        "field:foo.bar",
        "field:create_foo_input.bar",
        "field:update_foo_input.bar"
      ] ->
        "The quick brown fox"

    _unsupported_description ->
      nil
  end
end
```
