### ISSUE TITLE
Bug: Calling methods in enum values fails to compile

### ISSUE THREAD

**Issue by sheharyarn** [absinthe-graphql/absinthe#945]
### Environment

**Elixir:** v1.9.2 (compiled with Erlang/OTP 20)
**Absinthe:** v1.5.1

### Relevant Code

Since upgrading to Absinthe 1.5, I can no longer call functions in `value/2`'s attribute in the enum do block:

```elixir
enum :notification_type do
  value :create, as: Notifications.Create.name()
  value :update, as: Notifications.Update.name()
  value :delete, as: Notifications.Delete.name()
end
```

Where the `name()` methods above just return plain strings.

### Expected behavior

For the application to compile and work correctly. The above code was working for me until I upgraded to Absinthe 1.5.

### Actual behavior

The app fails to compile with the following error:

```elixir
== Compilation error in file lib/slab_graphql/schema/notification/notification_schema.ex ==
** (Absinthe.Schema.Notation.Error) Invalid Enum value for :create. Must be a literal term, dynamic values must use `hydrate`
    lib/absinthe/schema/notation.ex:1380: Absinthe.Schema.Notation.handle_enum_value_attrs/2
    lib/absinthe/schema/notation.ex:1400: Absinthe.Schema.Notation.record_value!/3
    expanding macro: Absinthe.Schema.Notation.value/2
    lib/slab_graphql/schema/notification/notification_schema.ex:41: Slab.GraphQL.Schema.NotificationSchema (module)
    expanding macro: Absinthe.Schema.Notation.enum/2
    lib/slab_graphql/schema/notification/notification_schema.ex:40: Slab.GraphQL.Schema.NotificationSchema (module)
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

---

I looked into [`hydrate`](https://hexdocs.pm/absinthe/Absinthe.Schema.html#c:hydrate/2) but couldn't exactly figure out how to use it resolve this issue.

**Comment by binaryseed** [comment]
Hello! Here's an example of doing this with `hydrate` in the absinthe tests:

https://github.com/absinthe-graphql/absinthe/blob/master/test/absinthe/schema/hydrate_dynamic_values_test.exs

**Comment by sheharyarn** [comment]
Hey @binaryseed, thanks for the update and info on using hydrate as a workaround to handle this, but I think this issue should not be closed just yet as the actual bug still remains.

This was possible in previous versions of Absinthe, and should remain supported in the future as well. One reason is that calling the function directly in the enum definition is intuitive as it closely mirrors the Elixir DSL. The other reason is that the current workaround using `hydrate` is too hacky, complicated and confusing, and seems just too unnecessary given we only want to dynamically load a value from a function.

I think even if calling the function directly will not be supported in the future, there should still be an easier alternative to accomplish it.

**Comment by benwilson512** [comment]
@sheharyarn to be clear, this was NOT an explicit feature in previous versions of absinthe, it worked by accident, and in plenty of situations it would not work the way you expect.

We have some plans around features to enable arbitrary function calls within schemas, but it largely requires that we make the transition to persistent_term as the default backend.
