### ISSUE TITLE
Use compile-time functions or module attributes in schemas

### ISSUE THREAD

**Issue by sheharyarn** [absinthe-graphql/absinthe#946]
### Environment

**Elixir:** v1.9.2 (compiled with Erlang/OTP 20)
**Absinthe:** v1.5.1

### Overview

When using module attributes or functions in `enum`, the code fails to compile. This bug was previously recorded in #448 and was marked resolved in `master` and closed, but after upgrading to Absinthe 1.5 still doesn't work.

This is different from #945 where functions could previously be called in the `value/2` attributes in `enum`'s `do` block.

### Relevant Code

Examples of code that cause the compilation to fail:

```elixir
enum :post_type, values: MyApp.Post.Type.__enum_map__()
```

```elixir
@post_types [:abc, :def, :ghi]
enum :post_type, values: @post_types
```

### Expected behavior

For the application to compile and work correctly.

### Actual behavior

The code fails with the following error (when used with the module attribute)

```elixir
== Compilation error in file lib/my_app_gql/schema/post_schema.ex ==
** (Protocol.UndefinedError) protocol Enumerable not implemented for {{:., [], [Module, :__get_attribute__]}, [], [MyApp.GraphQL.Schema.PostSchema, :post_types, 21]} of type Tuple
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:3023: Enum.map/2
    (elixir) lib/keyword.ex:873: Keyword.update/4
    expanding macro: Absinthe.Schema.Notation.enum/2
    lib/my_app_graphql/schema/post_schema.ex:21: MyApp.GraphQL.Schema.PostSchema (module)
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

### Previous Workarounds

Before Absinthe 1.5, the workarounds mentioned in #448 would allow getting around the problem, but now they don't work either:

```elixir
post_type_enum =
  quote do
    enum :post_type, values: unquote(MyApp.Post.Type.__enum_map__())
  end

Macro.expand_once(post_type_enum, __ENV__)
```

**Comment by benvp** [comment]
I just had the same issue using a macro defined directly inside the type module but if I extract it into it's own module and define the macro there it does compile properly.

```elixir
defmodule MyApp.GraphQL.Schema.Macros do
  defmacro currency_enum do
    quote do
      enum :currency, values: unquote(Money.Currency.known_current_currencies())
    end
  end
end

defmodule MyApp.GraphQL.Schema.Types do
  require MyApp.GraphQL.Schema.Macros
 
  MyApp.GraphQL.Schema.Macros.currency_enum()

  # ...other type definitions...
end
```

**Comment by sheharyarn** [comment]
Wanted to confirm @benvp's recommendation. An absinthe codebase where I had defined it within the same module did not work, but works in a different project where I was importing a custom helper from another module:

```elixir
defmodule Hutti.GraphQL.Helpers do

  @doc "Generate an Absinthe Notation Enum from an EctoEnum definition"
  defmacro enum_from_ecto(name, module) when is_atom(name) do
    name   = Macro.expand(name,   __CALLER__)
    module = Macro.expand(module, __CALLER__)
    values = module.__enum_map__()

    quote do
      enum(unquote(name), values: unquote(values))
    end
  end

  # ...
end
```

**Comment by youroff** [comment]
Is there a good reason to capture `values` as AST at all in this case? But anyways, here's our dirty but compact workaround:

**Comment by dylan-chong** [comment]
I'm actually going to have a go at making a PR to get the old 1.4 behaviour back (Being able to evaluate the functions at compile time)

@benwilson512 Do you remember why you decided to with the `hydrate` solution in 1.5, removing eval capabilities?

**Comment by dylan-chong** [comment]
I've had a go at making 1.5 eval code. My solution was to disable the explicit raises in notation.ex when a value is a tuple (e.g. a function call AST), marking it with metadata, and  in compile.ex in `build_types`, walk the AST and `Code.eval_quoted` any marked nodes can get expanded out. Can elaborate more on this later if needed

The problem with the approach is that compile.ex puts the resulting AST in a module called `YourSchema.Compiled`. This means that any private functions, aliases, imported functions and module attributes won't work. 1.4 worked fine because it put the AST in the `YourSchema` module.

@benwilson512 Thoughts?

**Comment by benwilson512** [comment]
@dylan-chong another option would be to use `{:unquote, [], [val]}` more liberally so that the unquote ends up happening in the `Blueprint` module.

**Comment by dylan-chong** [comment]
Oh that's a neat trick! Any thoughts on the `YourSchema.Compiled` comment?

**Comment by benwilson512** [comment]
@dylan-chong If you use `{:unquote` it won't be an issue because it gets unquoted inside the `__absinthe_blueprint__` function which remains inside the `YourSchema` module instead of the `YourSchema.Compiled` module.

**Comment by dylan-chong** [comment]
Holy crap you're right! That's magical! 🙏 
Tests for local function calls and module attributes are working! Amazing!
The test file is not compiling for this:

    value :module_function_call, as: -1, description: Absinthe.Type.EnumTest.hello("Bobby")

Is this because the nested module (TestSchema) is compiled before the outer module (EnumTest)?
Do we need some sort of `Code.ensure_compiled?` check somewhere?
That sounds iffy

**Comment by benwilson512** [comment]
@dylan-chong Yes that is why, and no that can't be avoided. All functions called within the schema must exist in modules outside the schema, and outside any modules that wrap the schema.

**Comment by dylan-chong** [comment]
Interesting. Thanks, I'll try and put up a PR in the next couple weeks with some tests too

**Comment by binaryseed** [comment]
Hi folks, here's an example of dynamic values using `hydrate`:

https://github.com/absinthe-graphql/absinthe/blob/master/test/absinthe/schema/hydrate_dynamic_values_test.exs

Hopefully this addresses the various needs in this thread...

**Comment by dylan-chong** [comment]
Thanks for replying @binaryseed 

the hydrate function doesn't suit our needs. We have a thousand+ fields that look like the following

```
  object :order do
    field(:id, non_null(:string), description: Descriptions.external_id_from_provider("order"))
    field(:provider, non_null(:string), description: Descriptions.provider("order"))
    field(:profile_id, :uuid,
      description: Descriptions.profile_id("order") <> @profile_id_description
    )
    field(:sid, :uuid, description: "Deprecated. Please use `profile_id`.")
```

This would be incredibly tedious to do for all our fields. Not to mention, hydrate is not the most convenient api

We do need to keep the values inline, otherwise we're going to have to stay with Absinthe 1.4

Re this:

> Thanks, I'll try and put up a PR in the next couple weeks with some tests too

I've had to push it back, but still keen to get around to it at some point (unless someone beats me to it)

**Comment by dylan-chong** [comment]
PR #1005 for fixing the descriptions part of the problem (Fixes 95% of the function evaluation problems, but not enum values just yet). Will continue with those in the future

**Comment by dylan-chong** [comment]
As per the comments in #1005, the descriptions are now evaluated, but the following are not:

- enum values (as a list)
- enum value (singular values)
- field/arg default_value

i've had a go at

**Comment by dylan-chong** [comment]
@benwilson512 @binaryseed Is enum value evaluation something that you'd plan to do in the future?

**Comment by benwilson512** [comment]
@dylan-chong yes, I hope to have something out this week addressing it.

**Comment by sheharyarn** [comment]
> Has this been fixed? I need something like this because I'm getting the values for the enums from config

@matheuscamarques you can still use a macro as suggested in some of the comments above, if you find the blueprint compilation process too complicated
