### ISSUE TITLE
Time in ISO format not accepted

### ISSUE THREAD

**Issue by thojanssens** [absinthe-graphql/absinthe#956]
Passing a valid ISO time like "22:15" to Absinthe gives the following error:

> "Argument \"input\" has invalid value $timeSlot.\nIn field \"endTime\": Expected type \"Time!\", found \"22:45\".

https://en.wikipedia.org/wiki/ISO_8601#Times
> Either the seconds, or the minutes and seconds, may be omitted from the basic or extended time formats for greater brevity
> but decreased accuracy; the resulting reduced accuracy time formats are:[24]

> [hh][mm] in basic format or [hh]:[mm] in extended format, when seconds are omitted.
> [hh], when both seconds and minutes are omitted.

Can we allow to pass a time in the [hh]:[mm] format?

**Comment by benwilson512** [comment]
Hi @thojanssens the absinthe type utilizes the built in `Time.from_iso8601`. I recommend you take this up with the elixir standard library, or use your own time scalar.
