### ISSUE TITLE
Memory leak with hexadecimal on mutation

### ISSUE THREAD

**Issue by samuelmanzanera** [absinthe-graphql/absinthe#957]
### Environment

* Elixir version (elixir -v): 1.10.2
* Absinthe version (mix deps | grep absinthe): absinthe 1.5.2
* Client Framework and version (Relay, Apollo, etc): fetch

### Expected behavior

I have a GraphQL Endpoint which expected some parameters in a mutation as hexadecimal. 

### Actual behavior

The thing is when I want send the mutation with the some hex around 8, 9 MB, the server seems to suffer a memory leak.
It brings the binary heap up to 1GB and more - which is strange due to the 9MB bytes from the data sent.

Which had the effect to bring down the application on the production server (OOM killed the process).

It tried it on Linux and Mac, the same issue around (except on my Mac, I had enought memory so I didn't figure out on the dev environment.

Maybe there is an issue around the parsing and some recursion if it kept the previous binary chunks parsed from the request

So to fix it I replaced the mutation by a POST Phoenix endpoint (REST), and the problem did not appear

### Relevant Schema/Middleware Code

```elixir
 mutation do
    field :create, :boolean do
     arg(:id, :hex)
     arg(:data, :data)
     arg(:signature, :hex)
     arg(:publicKey, :hex)

      resolve(fn _, _ ->
         {:ok, true}
      end)
end
```

with custom type 
```elixir
input_object :data do
    field(:content, :hex)
end
```

and with the custom scalar type hex

```elixir
scalar :hex do
   serialize(&Base.encode16/1)
   parse(&parse_hex/1)
end

defp parse_hex(%Absinthe.Blueprint.Input.String{value: value}), do: Base.decode16(value)
defp parse_hex(_), do: :error
```

**Comment by pmargreff** [comment]
Hello @samuelmanzanera, Absinthe is not efficient on a matter of memory, mainly because it expands your interactions (mutations and queries) to an AST.  

First, when you say leak, you say it gets the memory, and even after your response is sent it doesn't release this chunk of memory? or it only captures the memory while your request is being processed? 

If it's the second case, the point is how Absinthe holds your structures (in your case hexadecimal fields). As immutability result, when your data need to be manipulated (by Absinthe internals) it is always created new data, so if you have multiple steps your information can be duplicated multiple times, it's probably the reason for your memory spikes. 

If you can provide a functional reproduction (in a small repo), I can try to help to debug it, to find out if it's a leak or if we can optimize somewhere to get a better memory efficiency. 

[This issue also touches in the behavior that you're seeing](https://github.com/absinthe-graphql/absinthe/issues/573), besides the main problem isn't the same, IMO they're related.

**Comment by samuel-uniris** [comment]
Thanks. Yes Indeed it's more the second case. While the request is processed (even without resolver job or functions calls) the memory is rising. 

So force to admit is in the absinthe internals that they have multiple operations on top of that memory allocation. Which explained probably the binary heap increase.

It will provide a repo example but the most of it is showed in the example I provided above.

**Comment by benwilson512** [comment]
> Absinthe is not efficient on a matter of memory,
While sort of true, it shouldn't use 1gb for a simple query.

As a minor note @samuel-uniris your example is invalid, you have an object type as an input. It also references a `hash` scalar which is different from the presented `hex` scalar.

Here is a complete example I ran based on your code:

```
defmodule Foo do
  use Absinthe.Schema

  query do
  end

  mutation do
    field :create, :boolean do
      arg(:id, :hex)
      arg(:data, :data)

      resolve(fn _, _ ->
        {:ok, true}
      end)
    end
  end

  input_object :data do
    field(:content, :hex)
  end

  scalar :hex do
    serialize(&Base.encode16/1)
    parse(&parse_hex/1)
  end

  defp parse_hex(%Absinthe.Blueprint.Input.String{value: value}), do: Base.decode16(value)
  defp parse_hex(_), do: :error
end

hex_val = "asdf" |> Base.encode16

query = """
mutation ($id: Hex, $data: Data) {
  create(id: $id, data: $data)a
}
"""

Absinthe.run(query, Foo, variables: %{
  "id" => hex_val,
  "data" => %{"content" => hex_val}
})
```

This returned immediately and did not lead to any memory growth.

Are you sure this is related to the scalars? We've seen memory issues where people are putting the entire `resolution` ( the third arg to a resolver) struct into dataloader or batch functions. Something about the compiled schemas causes unbounded memory growth when the BEAM tries to copy that value from one process to another.

**Comment by samuelmanzanera** [comment]
Thanks @benwilson512 to correct me. I updated the example. 
For the resolution I didn't include this parameter inside the resolver.

Did you try with much more data like few MB ?
Otherwise is it possible the issue is coming from the http layer ? Plug ?

**Comment by benwilson512** [comment]
Sure, I created a random string 1mb long and then base16 encoded it to create a hex_val 2mb long:
```
hex_val = Stream.repeatedly(fn -> ?A..?Z |> Enum.random end) |> Enum.take(1_000_000) |> to_string |> Base.encode16
byte_size(hex_val)
#=> 2000000
```

It also worked fine. It's hard to say where the issue is coming from. Can you reproduce this locally?

**Comment by samuel-uniris** [comment]
Locally I do not repoduce it with the Absinthe library only, so I suppose with HTTP layer it may produce the bug.
So maybe about Absinthe.Plug.Parser.

**Comment by benwilson512** [comment]
If you can provide a reproduceable example I'm happy to look into it more.
