### ISSUE TITLE
Hexdocs html has broken links to markdown files

### ISSUE THREAD

**Issue by johnshaughnessy** [absinthe-graphql/absinthe#966]
The absinthe docs on hexdocs have broken links pointing to markdown files. (Example: The link with text, "add arguments to our queries" in the following section: https://hexdocs.pm/absinthe/our-first-query.html#next-step ) 

The opposite problem exists for people reading the markdown files on github, and was partially addressed in this PR: https://github.com/absinthe-graphql/absinthe/pull/955/files
(The same link mentioned above does work, in this case: https://github.com/absinthe-graphql/absinthe/blob/master/guides/tutorial/start.md#first-step )

I don't know what the solution is - an ideal scenario might have markdown files pointing to other markdown files and html files pointing to html files, but I do not know enough about the doc-generation process to assist with this.

### Environment

* Elixir version (elixir -v): N/A
* Absinthe version (mix deps | grep absinthe): 1.5.2
* Client Framework and version (Relay, Apollo, etc): N/A

### Expected behavior

Links in hexdocs should work.

### Actual behavior

Some links in hexdocs are broken.

### Relevant Schema/Middleware Code

N/A

**Comment by binaryseed** [comment]
This should be fixed in https://github.com/absinthe-graphql/absinthe/pull/993
