### ISSUE TITLE
Raise compile time Error if field type is not provided

### ISSUE THREAD

**Issue by chess4ever** [absinthe-graphql/absinthe#967]
### Environment

* Elixir version (elixir -v): 1.10.3
* Absinthe version (mix deps | grep absinthe): 1.4.16

### Expected behavior

Raise compile time Error or give some kind of warning.

### Actual behavior

It silently ignores the field declared without the type.

### Relevant Schema/Middleware Code
```elixir
object :person do
    field :name, :string
    field :age
 end
```

**Comment by benwilson512** [comment]
Hi @chess4ever, this is no longer an issue on 1.5.

```
iex(1)> defmodule Foo do
...(1)> use Absinthe.Schema.Notation
...(1)> object :person do
...(1)>     field :name, :string
...(1)>     field :age
...(1)>  end
...(1)> end
** (CompileError) iex:5: undefined function field/1
    (absinthe 1.5.2) expanding macro: Absinthe.Schema.Notation.object/2
    iex:3: Foo (module)
```
