### ISSUE TITLE
Current recommendation for ordered results in GraphQL response

### ISSUE THREAD

**Issue by calebmer** [absinthe-graphql/absinthe#969]
Absinthe orders GraphQL responses alphabetically, I’d like to order responses in query order (at least in dev) to improve readability. It looks like there’s a lot of conversation on this topic:

- https://github.com/absinthe-graphql/absinthe/issues/352
- https://github.com/absinthe-graphql/absinthe/pull/445
- https://github.com/absinthe-graphql/absinthe_tutorial/pull/1

Is the current recommendation to use the code from https://github.com/absinthe-graphql/absinthe_tutorial/pull/1 in new projects? Have any of the updates mentioned there been made? Is there a more up-to-date recommendation?

**Comment by binaryseed** [comment]
We don't have a more up to date example, but would still recommend using the general approach of replacing `Absinthe.Phase.Document.Result` phase.
