### ISSUE TITLE
SDL generation task doesn't render interfaces

### ISSUE THREAD

**Issue by emeryotopalik** [absinthe-graphql/absinthe#977]
### Environment

* Elixir version (elixir -v): all
* Absinthe version (mix deps | grep absinthe): 1.5 or less

### Expected behavior

I would expect interfaces to be rendered like:
```
interface Interface { ... }
type ImplementingType implements Interface { ... }
```

### Actual behavior

It renders:
```
interface Interface { ... }
type ImplementingType  { ... }
```

**Comment by emeryotopalik** [comment]
I outlined a failure case in the tests: https://github.com/absinthe-graphql/absinthe/compare/master...emeryotopalik:failing_sdl_generation

**Comment by binaryseed** [comment]
Thanks!
