### ISSUE TITLE
Block introspection query on Absinthe layer

### ISSUE THREAD

**Issue by neslinesli93** [absinthe-graphql/absinthe#986]
Hi, I am trying to upgrade to Absinthe 1.5 and I've stumbled upon an issue regarding the introspection query. So far I've been using a middleware to block the introspection query, but since [this PR](https://github.com/absinthe-graphql/absinthe/pull/893) it doesn't work anymore: the middlewares are invoked at compile-time with all my queries, mutations and types and the introspection query is not one of them.

Is there a programmatic way do accomplish this, without having to do it at the http layer? Thanks

**Comment by binaryseed** [comment]
Can you describe what it is that you are trying that does not work?

**Comment by binaryseed** [comment]
I'd recommend using a `@pipeline_modifier` in your schema module..

Here's an example test that demonstrates modifying introspection:

https://github.com/absinthe-graphql/absinthe/blob/master/test/absinthe/schema/manipulation_test.exs#L235
