### ISSUE TITLE
Discussion about improving Dataloader

### ISSUE THREAD

**Issue by Un3qual** [absinthe-graphql/absinthe#991]
I am currently experiencing an issue with Dataloader, where a deeply nested field has its query run multiple times because its parent also has to be resolved with Dataloader. In exploring to try and fix it, I realized it may require rearchitecting how Absinthe resolves fields. I'm not as familiar with absinthe's internals as I am with Dataloader's, so I'm hoping someone from this repo with more knowledge of Absinthe can look into implementing a fix or point me in the right direction. Also, this issue isn't specific to Dataloader. Absinthe's built in batching has this issue too.

I have created an issue for this with a lot more detail at absinthe-graphql/dataloader#112 and a forum post [here](https://elixirforum.com/t/can-absinthe-resolve-children-before-siblings/35540).
I hope I'm in the right place. My sincere apologies if I'm not.

**Comment by benwilson512** [comment]
@Un3qual very interesting ideas, but please see my post on the other issue.
